/* FindIt commerce UI v6 — responsive complete price comparison + branch/online clarity. */
(()=>{
'use strict';
if(window.__finditCommerceUiV4)return;window.__finditCommerceUiV4=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const state=()=>{try{return window.finditState||window.state||{}}catch{return{}}};
const ident=()=>state()?.result?.identification||{};
const norm=v=>String(v||'').toLowerCase().replace(/\b(\d+)\s*(ml|mg|g|kg|l|oz|rolls?|pack|ply|gb|tb)\b/g,'$1$2').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const positive=v=>v!==null&&v!==undefined&&v!==''&&Number.isFinite(Number(v))&&Number(v)>0;
const validUrl=v=>{try{return /^https?:$/.test(new URL(v).protocol)}catch{return false}};
const retailer=o=>String(o?.retailer?.name||o?.retailer||o?.store||o?.seller||'Retailer').trim();
const key=v=>norm(v).replace(/\bdis chem\b/g,'dischem').replace(/\btakealot com\b/g,'takealot').replace(/\bpnp\b/g,'pick n pay');
const knownStock=v=>/^(in_stock|out_of_stock|preorder|backorder)$/i.test(String(v||''));
const stockText=v=>({in_stock:'In stock online',out_of_stock:'Out of stock online',preorder:'Pre-order online',backorder:'Back-order online'}[String(v||'').toLowerCase()]||'Online stock not published');
const money=(n,c='ZAR')=>{if(!positive(n))return'Price not published';try{return new Intl.NumberFormat('en-ZA',{style:'currency',currency:c||'ZAR'}).format(Number(n))}catch{return`${c||'ZAR'} ${Number(n).toFixed(2)}`}};
function localOffer(o){if(String(o?.currency||'').toUpperCase()==='ZAR'||o?.localSouthAfrica===true)return true;try{const h=new URL(o?.product_url||o?.url||'').hostname.toLowerCase();return h.endsWith('.co.za')||h.endsWith('.za.com')||h==='takealot.com'||h.endsWith('.takealot.com')}catch{return false}}
function trusted(o){return !!(o&&o.exactProductMatch!==false&&(o.sourcePageVerified===true||o.priceComparisonVerified===true||(o.verified===true&&o.searchGroundedVerified!==true)));}
function evidence(o){return(o?.sourcePageVerified===true?1000:0)+(o?.priceComparisonVerified===true?800:0)+(o?.exactProductMatch===true?300:0)+(positive(o?.price)?160:0)+(knownStock(o?.availability)?70:0)+Math.min(100,Number(o?.matchScore||0));}
function combinedOffers(){
 const raw=[...(state()?.offers||[]),...(window.productIntelligence?.offers||[])].filter(trusted);
 const local=raw.filter(localOffer),use=local.length?local:raw,groups=new Map();
 for(const o of use){const k=key(retailer(o));if(!k)continue;const a=groups.get(k)||[];a.push(o);groups.set(k,a)}
 const out=[];
 for(const rows of groups.values()){
   const direct=[...rows].filter(o=>o.sourcePageVerified===true).sort((a,b)=>evidence(b)-evidence(a))[0]||null;
   const priced=[...rows].filter(o=>positive(o.price)).sort((a,b)=>Number(a.price)-Number(b.price)||evidence(b)-evidence(a));
   const priceRow=priced[0]||null,best=direct||priceRow||[...rows].sort((a,b)=>evidence(b)-evidence(a))[0];if(!best)continue;
   out.push({...best,retailer:best.retailer||priceRow?.retailer||direct?.retailer,product_name:direct?.product_name||priceRow?.product_name||best.product_name,product_url:(direct&&validUrl(direct.product_url||direct.url)?direct.product_url||direct.url:null)||(priceRow?.product_url||priceRow?.url||best.product_url||best.url),price:priceRow?.price??best.price,currency:priceRow?.currency||best.currency||'ZAR',availability:direct&&knownStock(direct.availability)?direct.availability:(knownStock(best.availability)?best.availability:null),priceComparisonVerified:rows.some(x=>x.priceComparisonVerified===true),sourcePageVerified:rows.some(x=>x.sourcePageVerified===true),priceSourceUrl:priceRow?.comparisonSourceUrl||priceRow?.product_url||priceRow?.url||null,branchStockVerified:false});
 }
 return out.sort((a,b)=>{const ap=positive(a.price),bp=positive(b.price);if(ap!==bp)return bp-ap;if(ap&&bp)return Number(a.price)-Number(b.price);return evidence(b)-evidence(a)});
}
function modal(){let m=$('#fxStableModal');if(!m){m=document.createElement('div');m.id='fxStableModal';m.className='fx-stable-modal hidden';m.innerHTML='<div class="fx-stable-card"><button type="button" class="fx-stable-close" aria-label="Close">×</button><div id="fxStableBody"></div></div>';document.body.appendChild(m)}if(!m.dataset.v4Close){m.dataset.v4Close='1';m.addEventListener('click',e=>{if(e.target===m||e.target.closest('.fx-stable-close')){m.classList.add('hidden');m.setAttribute('aria-hidden','true')}})}return m}
function open(html){const m=modal(),b=$('#fxStableBody');if(!b)return;b.innerHTML=html;m.classList.remove('hidden');m.setAttribute('aria-hidden','false');queuePolish()}
function body(){const i=ident(),s=state(),c=s.coords||{};return{identification:i,name:i.name||i.object||'',brand:i.brand||'',model:i.model||'',object:i.object||'',category:i.retailCategory||i.category||'',retailCategory:i.retailCategory||i.category||'',searchQuery:i.searchQuery||i.name||i.model||i.object||'',query:i.searchQuery||i.name||i.model||i.object||'',lat:c.lat??s.lat,lon:c.lon??c.lng??s.lon??s.lng,radius:Number(s.radius||localStorage.getItem('finditRadius')||10)}}
let refreshPromise=null;
async function doRefresh(){const b=body();if(!b.searchQuery)return false;const ctl=new AbortController(),timer=setTimeout(()=>ctl.abort(),15000);try{const r=await fetch('/api/product-intelligence-v2',{method:'POST',headers:{'content-type':'application/json','accept':'application/json'},body:JSON.stringify(b),cache:'no-store',signal:ctl.signal});const d=await r.json().catch(()=>({}));if(!r.ok||!Array.isArray(d.offers))return false;const old=[...(state()?.offers||[]),...(window.productIntelligence?.offers||[])],map=new Map();for(const o of[...old,...d.offers]){if(!trusted(o))continue;const k=`${key(retailer(o))}|${String(o.product_url||o.url||'').toLowerCase()}`;const prev=map.get(k);if(!prev||evidence(o)>=evidence(prev))map.set(k,o)}const offers=[...map.values()];try{state().offers=offers}catch{}window.productIntelligence={...(window.productIntelligence||{}),...d,offers};try{document.dispatchEvent(new CustomEvent('findit:dashboard-sync',{detail:{commerce:true}}))}catch{}return true}catch(e){console.warn('FindIt price refresh unavailable',e?.message||e);return false}finally{clearTimeout(timer)}}
function refresh(){if(refreshPromise)return refreshPromise;refreshPromise=doRefresh().finally(()=>{refreshPromise=null});return refreshPromise}
function near(){const seen=new Set(),rows=[];for(const s of(Array.isArray(state()?.stores)?state().stores:[])){const k=key(s?.name);if(!k||seen.has(k))continue;seen.add(k);rows.push(s)}return rows.sort((a,b)=>Number(a.distanceKm??1e9)-Number(b.distanceKm??1e9))}
function offerRow(o){const p=positive(o.price),url=o.product_url||o.url,source=o.priceSourceUrl;const sourceExtra=p&&source&&validUrl(source)&&source!==url?` <a href="${esc(source)}" target="_blank" rel="noopener noreferrer">Price source</a>`:'';const stock=o.availability&&knownStock(o.availability)?` · ${esc(stockText(o.availability))}`:'';return`<div class="fx-stable-row"><div><b>${esc(retailer(o))}</b><small>${esc(o.product_name||ident().name||'Exact product')}${stock}${o.priceComparisonVerified===true?' · Price verified from current comparison evidence':''}</small></div><div><b>${esc(money(o.price,o.currency||'ZAR'))}</b>${validUrl(url)?`<br><a href="${esc(url)}" target="_blank" rel="noopener noreferrer">View product</a>`:''}${sourceExtra}</div></div>`}
function nearbyHtml(offers){const by=new Map(offers.map(o=>[key(retailer(o)),o])),matched=near().filter(s=>by.has(key(s.name))),other=near().filter(s=>!by.has(key(s.name)));return`${matched.length?`<h3>Nearby branches of retailers with an exact online listing</h3><div class="fx-stable-list">${matched.slice(0,10).map(s=>{const o=by.get(key(s.name));return`<div class="fx-stable-row"><div><b>${esc(s.name)}</b><small>${Number.isFinite(Number(s.distanceKm))?`${Number(s.distanceKm).toFixed(1)} km · `:''}${esc(s.address||'')}${positive(o.price)?` · Online price ${esc(money(o.price,o.currency||'ZAR'))}`:''}${knownStock(o.availability)?` · ${esc(stockText(o.availability))}`:''} · Branch stock unknown unless this exact branch publishes inventory</small></div></div>`}).join('')}</div>`:''}${other.length?`<h3>Other nearby relevant retailers</h3><div class="fx-stable-list">${other.slice(0,8).map(s=>`<div class="fx-stable-row"><div><b>${esc(s.name||'Store')}</b><small>${Number.isFinite(Number(s.distanceKm))?`${Number(s.distanceKm).toFixed(1)} km · `:''}${esc(s.address||'')} · Exact item and price not confirmed</small></div></div>`).join('')}</div>`:''}`}
function render(checking=false){const all=combinedOffers(),priced=all.filter(o=>positive(o.price)),unpriced=all.filter(o=>!positive(o.price));open(`<h2 class="fx-stable-title">Compare Prices</h2><p class="fx-stable-sub">All verified exact-product South African prices found are shown. Retailers without a publishable price stay listed separately. Online stock and branch stock are verified separately.</p><div id="fxPriceStatus" class="fx-tool-status">${checking?'Showing saved results while checking for fresh prices…':priced.length?`${priced.length} retailer${priced.length===1?'':'s'} with current exact-product pricing found.`:'No trustworthy current price has been verified yet.'}</div><h3>Current online prices</h3><div id="fxOnlinePrices" class="fx-stable-list">${priced.length?priced.map(offerRow).join(''):'<div class="fx-stable-row"><div>No trustworthy current online price has been verified yet.</div></div>'}</div>${unpriced.length?`<h3>Exact listings without a published price</h3><div id="fxUnpricedListings" class="fx-stable-list">${unpriced.map(offerRow).join('')}</div>`:''}<h3>In-store branch prices</h3><div class="fx-stable-list"><div class="fx-stable-row"><div>No branch-specific price is shown unless that exact branch publishes it. Online prices above do not prove an in-store branch price.</div></div></div>${nearbyHtml(all)}<div class="fx-stable-actions"><button class="fx-primary" id="fxRefreshPrices">Refresh prices</button></div>`);const b=$('#fxRefreshPrices');if(b)b.onclick=()=>{if(b.disabled)return;b.disabled=true;render(true);refresh().finally(()=>render(false))}}
function openCompare(){render(true);refresh().finally(()=>{if(!$('#fxStableModal')?.classList.contains('hidden'))render(false)})}
let polishQueued=false;
function polish(){
 polishQueued=false;
 for(const b of $$('#fxTopStores > button')){const star=$('.fx-star',b);if(star&&/exact online|in stock/i.test(star.textContent||'')&&star.textContent!=='Exact online · branch stock unknown')star.textContent='Exact online · branch stock unknown'}
 for(const row of $$('#fxStoreList .fx-store')){const em=$('em',row);if(em&&/exact product online|in stock online|branch availability unknown|branch stock not published/i.test(em.textContent||'')){const hasPrice=!!$('strong',row)?.textContent?.match(/R\s*\d/i),next=`Exact product online${hasPrice?' · online price shown':''} · branch stock unknown`;if(em.textContent!==next)em.textContent=next;em.classList.remove('ok')}}
 const root=$('#fxStableBody');if(root){for(const n of [...root.querySelectorAll('*')]){if(n.childNodes.length!==1||n.firstChild?.nodeType!==Node.TEXT_NODE)continue;const old=n.textContent||'',next=old.replace(/Showing verified South African results while checking for updates…?/gi,'Verified South African exact-product results').replace(/Considered a good value by customers[^.]*\.?/gi,'Compare the verified retailer prices below to decide whether it is good value for your needs.');if(next!==old)n.textContent=next}}
}
function queuePolish(){if(polishQueued)return;polishQueued=true;requestAnimationFrame(polish)}
document.addEventListener('click',e=>{const t=e.target?.closest?.('[data-fx="compare"],[data-fxnav="compare"],#fxComparePrices');if(!t)return;e.preventDefault();e.stopImmediatePropagation();setTimeout(openCompare,0)},true);
document.addEventListener('findit:dashboard-sync',queuePolish);document.addEventListener('findit:results-rendered',queuePolish);setTimeout(queuePolish,300);setTimeout(queuePolish,1200);
window.finditOpenFullPriceComparison=openCompare;
})();
