/* FindIt authoritative information runtime.
   One product state drives the dashboard, Product Info, Compare and Nearby views. */
(()=>{'use strict';if(window.__finditInformationRuntime)return;window.__finditInformationRuntime=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=v=>String(v??'').replace(/\s+/g,' ').trim(),esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const st=()=>window.finditState||null, ident=()=>st()?.result?.identification||{};
let commerce=null,research=null,busy=false,owned=false,photoGeneration=0,researchPending=false;
const validUrl=v=>{try{return /^https?:$/.test(new URL(v).protocol)}catch{return false}};
const money=o=>{if(o?.price===null||o?.price===undefined||o?.price===''||!Number.isFinite(Number(o.price))||Number(o.price)<=0)return null;if(!/^[A-Z]{3}$/.test(String(o.currency||'').toUpperCase()))return 'Price '+Number(o.price).toFixed(2)+' (currency unverified)';try{return new Intl.NumberFormat('en-ZA',{style:'currency',currency:o.currency.toUpperCase()}).format(Number(o.price))}catch{return o.currency+' '+o.price}};
function productName(i=ident()){return clean(i.name||i.model||i.object||i.searchQuery)}
function exactOffers(){if(ident().requiresModelConfirmation)return [];return (Array.isArray(commerce?.offers)?commerce.offers:[]).filter(o=>o&&o.exactProductMatch===true&&(o.sourcePageVerified===true||o.priceComparisonVerified===true||o.verified===true))}
function verifiedPrices(){return exactOffers().filter(o=>o.price!==null&&o.price!==undefined&&o.price!==''&&Number.isFinite(Number(o.price))&&Number(o.price)>0&&(o.sourcePageVerified===true||o.priceComparisonVerified===true||o.verified===true))}
function retailerName(o){return clean(o?.retailer?.name||o?.retailer||o?.store||o?.seller||'Retailer')}
function closeInfoForDashboardTarget(target){const hit=target?.closest?.('#finditExactShell [data-fx],#finditExactShell [data-fxnav],#fxPremiumSideButton,#fxPremiumBottomButton');if(!hit)return;const m=$('#fxInformationModal');if(m?.classList.contains('open')){m.classList.remove('open');m.style.pointerEvents='none';m.setAttribute('aria-hidden','true')}}
document.addEventListener('pointerdown',e=>closeInfoForDashboardTarget(e.target),true);
document.addEventListener('click',e=>closeInfoForDashboardTarget(e.target),true);
function ensureModal(){let m=$('#fxInformationModal');if(!m){m=document.createElement('div');m.id='fxInformationModal';m.className='fx-info-modal';m.innerHTML='<div class="fx-info-card"><button class="fx-info-x" aria-label="Close">×</button><div id="fxInformationBody"></div></div>';document.body.appendChild(m);m.querySelector('.fx-info-x').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}return m}
function openModal(html){let m=ensureModal();$('#fxInformationBody',m).innerHTML=html;m.style.pointerEvents='auto';m.removeAttribute('aria-hidden');m.classList.add('open')}
function loading(title){openModal('<h2>'+esc(title)+'</h2><div class="fx-info-loading">Checking current product and retailer information…</div>')}
function searchModal(note='',initial=''){openModal('<h2>Search a product</h2>'+(note?'<p class="fx-info-note">'+esc(note)+'</p>':'')+'<form id="fxRealSearch"><label for="fxRealQuery">Product name, brand + model, or barcode</label><input id="fxRealQuery" required autofocus placeholder="e.g. Marc Anthony Strictly Curls 3X Moisture Conditioner 250ml"><button type="submit">Find product information</button></form><p class="fx-info-help">More detail gives FindIt a better exact-product match. Prices and stock are only shown when retailer evidence supports them.</p>');$('#fxRealQuery').value=clean(initial);$('#fxRealSearch').onsubmit=e=>{e.preventDefault();runSearch($('#fxRealQuery').value)}}
async function json(url,body,timeout=26000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:c.signal}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||d.error||'Request failed');return d}finally{clearTimeout(t)}}
async function getLocationIfAlreadyAllowed(){if(st()?.coords)return st().coords;if(!navigator.geolocation)return null;try{if(navigator.permissions){const permission=await navigator.permissions.query({name:'geolocation'});if(permission.state!=='granted')return null;}else return null;const p=await new Promise((ok,no)=>navigator.geolocation.getCurrentPosition(ok,no,{timeout:12000,maximumAge:300000}));const coords={lat:p.coords.latitude,lon:p.coords.longitude};if(st())st().coords=coords;return coords}catch(e){console.warn('Location not available',e);return null}}
function searchStatus(text){for(const selector of ['#status','#fxStatus']){const el=$(selector);if(el)el.textContent=text}}
async function runSearch(q){q=clean(q);if(!q||busy)return;const generation=++photoGeneration;busy=true;$('#fxPhotoRecovery')?.setAttribute('hidden','');searchStatus('Searching product name…');$('#warning')?.classList.add('hidden');loading('Finding '+q);try{
 const s=st(),base=await json('/api/search',{query:q});if(generation!==photoGeneration)return;owned=true;if(!base.identification)throw Error('FindIt could not create a product search from that name.');
 s.file=null;const oldPreview=$('#preview');if(oldPreview){oldPreview.removeAttribute('src');oldPreview.classList.add('hidden')}const photoBox=$('#fxProductImage');if(photoBox)photoBox.innerHTML='<span>▧</span>';s.photoSearchPending=null;s.photoSearchFile=null;s.result=base;s.offers=[];s.stores=[];commerce=null;research=null;
 const i=base.identification,coords=await getLocationIfAlreadyAllowed(),payload={identification:i,...(coords?{lat:coords.lat,lon:coords.lon}:{})};
 if(generation!==photoGeneration)return;syncIdentity(i);document.dispatchEvent(new CustomEvent('findit:results-rendered',{detail:{result:base}}));
 const tasks=[
  json('/api/product-intelligence-v2',payload,30000).catch(e=>{console.error('FindIt commerce request failed',e);return null}),
  coords?json('/api/nearby',{lat:coords.lat,lon:coords.lon,identification:i,radiusKm:s.radius||10},22000).catch(e=>{console.error('FindIt nearby request failed',e);return null}):Promise.resolve(null)
 ];
 const [c,n]=await Promise.all(tasks);if(generation!==photoGeneration)return;commerce=c;
 const r=await json('/api/product-insights',{identification:i,offers:Array.isArray(c?.offers)?c.offers:[]},24000).catch(e=>{console.error('FindIt product insights failed',e);return null});
 if(generation!==photoGeneration)return;research=r?.researched===false?null:r;
 if(Array.isArray(c?.offers)){s.offers=c.offers;window.productIntelligence=c}else console.warn('FindIt commerce response has no offer list');if(Array.isArray(n?.stores))s.stores=n.stores;else if(!coords)console.info('FindIt nearby search needs location permission');else console.warn('FindIt nearby response has no store list');
 syncAll();document.dispatchEvent(new CustomEvent('findit:dashboard-sync',{detail:{result:s.result}}));if(s.stores.length)document.dispatchEvent(new CustomEvent('findit:nearby-updated',{detail:{stores:s.stores}}));
 searchStatus('Product search complete. Prices and stock require verified retailer evidence.');saveRecent(i);showProductInfo();
 }catch(e){if(generation!==photoGeneration)return;searchStatus('Search failed. Check the message below.');openModal('<h2>Search problem</h2><p>'+esc(e.message||'FindIt could not complete this search.')+'</p><button id="fxTryAgain">Try another product</button>');$('#fxTryAgain').onclick=()=>searchModal()}finally{if(generation===photoGeneration){busy=false;syncAll()}}}
function saveRecent(i){try{let a=JSON.parse(localStorage.getItem('finditRecent')||'[]'),q=i.searchQuery||i.name||i.object;a=[{id:Date.now(),name:productName(i),brand:i.brand||'',query:q,date:new Date().toISOString()},...a.filter(x=>x.query!==q)].slice(0,30);localStorage.setItem('finditRecent',JSON.stringify(a))}catch{}}
function syncIdentity(i){let name=productName(i)||'Product selected',meta=[i.brand,i.model,i.category||i.retailCategory].filter(Boolean).join(' · ');
 const set=(sel,v)=>{let e=$(sel);if(e&&v!==undefined)e.textContent=v};
 set('#fxProductName',name);set('#fxProductMeta',meta);set('#fxProductDesc',i.summary||('Searching current retailer information for '+name+'.'));set('#fxExactBadge',i.userConfirmed?'Product confirmed by search':'Product identified');set('#fxConfidence',i.confidence!==null&&i.confidence!==undefined&&Number.isFinite(Number(i.confidence))?Math.round(Number(i.confidence)*100)+'% Match':'Search confirmed');
 set('#resultName',name);set('#resultDescription',i.summary||meta);
}
function syncAll(){if(!owned)return;syncIdentity(ident());let i=ident(),prices=verifiedPrices().sort((a,b)=>Number(a.price)-Number(b.price)),best=prices.length&&prices.every(o=>o.currency&&o.currency===prices[0].currency)?prices[0]:null,stores=st()?.stores||[],offers=exactOffers();
 let bp=$('#fxBestPrice');if(bp)bp.textContent=best?money(best):(prices.length?'Prices use different or unverified currencies — open Compare Prices':'No verified price yet');
 let top=$('#fxTopStores');if(top)top.innerHTML=stores.length?stores.slice(0,4).map(storeRow).join(''):'<div class="fx-empty">'+(!st()?.coords?'Allow location access in your browser, then search again to find nearby retailers.':'No matching nearby retailer was returned. Try a larger search radius; exact product stock is not verified.')+'</div>';
 window.finditRenderRetailerCards?.();
 let list=$('#fxStoreList');if(list)list.innerHTML=stores.length?stores.slice(0,6).map(storeRow).join(''):'<div class="fx-empty">'+(!st()?.coords?'Allow location access in your browser, then search again to find nearby retailers.':'No matching nearby retailer was returned. Try a larger search radius; exact product stock is not verified.')+'</div>';
 let desc=$('#fxProductDesc');if(desc)desc.textContent=(research?.researched===true?research.whatItDoes:null)||([offers.length?offers.length+' retailer listing'+(offers.length===1?'':'s')+' found':null,stores.length?stores.length+' nearby retailer'+(stores.length===1?'':'s')+' found':null].filter(Boolean).join(' · ')||(busy?'Checking retailer evidence…':'No exact retailer listing could be verified. Try adding the brand, model or size.'));
 syncSmart(best,stores,offers);
}
function storeRow(s){let dist=s.distanceKm!==null&&s.distanceKm!==undefined&&s.distanceKm!==''&&Number.isFinite(Number(s.distanceKm))&&Number(s.distanceKm)>=0?Number(s.distanceKm).toFixed(1)+' km':'',address=clean(s.address),site=validUrl(s.website)?s.website:'';return '<div class="fx-real-store"><div><b>'+esc(s.name||'Retailer')+'</b><small>'+esc([dist,address].filter(Boolean).join(' · '))+'</small><em>Branch stock '+(s.branchStockVerified===true?'verified':'not verified')+'</em></div>'+(site?'<a href="'+esc(site)+'" target="_blank" rel="noopener">Website</a>':'')+'</div>'}
function syncSmart(best,stores,offers){let root=$('#fxSmartChoice');if(!root)return;let cards=$$('.fx-smart-card',root);if(cards[0]){let x=cards[0].querySelector('strong'),p=cards[0].querySelector('p');if(x)x.textContent=offers.length?offers.length+' exact/relevant retailer listing'+(offers.length===1?'':'s'):'No exact retailer listing yet';if(p)p.textContent=offers.length?'Open Compare Prices to inspect the retailer evidence.':'FindIt has not found a retailer product page it can support yet.'}if(cards[1]){let x=cards[1].querySelector('strong'),p=cards[1].querySelector('small')||cards[1].querySelector('p');if(x)x.textContent=best?money(best):'No verified price yet';if(p)p.textContent=best?'Lowest verified current price found at '+retailerName(best)+'.':'No current price has passed verification yet.'}if(cards[2]){let x=cards[2].querySelector('strong'),p=cards[2].querySelector('p'),s=stores[0];if(x)x.textContent=s?(s.name||'Nearby retailer'):'No nearby retailer yet';if(p)p.textContent=s?([s.distanceKm!=null&&s.distanceKm!==''&&Number.isFinite(Number(s.distanceKm))&&Number(s.distanceKm)>=0?Number(s.distanceKm).toFixed(1)+' km away':'',s.address||''].filter(Boolean).join(' · ')||'Relevant nearby retailer'):'Use location after selecting a product to search nearby retailers.'}}
function identityBlock(){let i=ident(),bits=[i.brand&&'<span><b>Brand</b>'+esc(i.brand)+'</span>',i.model&&'<span><b>Model / variant</b>'+esc(i.model)+'</span>',(i.category||i.retailCategory)&&'<span><b>Category</b>'+esc(i.category||i.retailCategory)+'</span>',i.barcode&&'<span><b>Barcode</b>'+esc(i.barcode)+'</span>'].filter(Boolean).join('');return '<div class="fx-info-identity"><h3>'+esc(productName(i))+'</h3><div>'+bits+'</div></div>'}
function sourceLinks(){let src=Array.isArray(research?.sources)?research.sources:[];return src.filter(x=>validUrl(x.url||x.link)).slice(0,5).map(x=>'<a href="'+esc(x.url||x.link)+'" target="_blank" rel="noopener">'+esc(x.title||x.name||'Source')+'</a>').join('')}
function showProductInfo(){if(!productName())return searchModal('Select a product first so FindIt can show useful information.');if(ident().requiresModelConfirmation){openModal('<h2>Product Information</h2>'+identityBlock()+'<p>Recognised '+esc(productName())+'. The exact model or variant is not confirmed. Add the model or label to check its specifications, strengths, prices and stock.</p>'+(ident().suggestedLabel?'<p class="fx-info-note">Possible label reading: <b>'+esc(ident().suggestedLabel)+'</b>. Check it against your product before confirming.</p>':'')+'<button id="fxConfirmModel">Confirm model or label</button>');$('#fxConfirmModel').onclick=()=>searchModal(recoveryNote(),ident().suggestedLabel||productName());return}if(!research&&!busy&&!researchPending){const i=ident();researchPending=true;json('/api/product-insights',{identification:i,offers:Array.isArray(st()?.offers)?st().offers:[]},12000).then(r=>{if(r?.researched&&productName(i)===productName()){research=r;showProductInfo()}}).catch(e=>console.error('FindIt product details unavailable',e)).finally(()=>{researchPending=false});}let pros=research?.researched===true&&Array.isArray(research?.pros)?research.pros:[],cons=research?.researched===true&&Array.isArray(research?.cons)?research.cons:[],sources=sourceLinks(),offers=exactOffers();
 openModal('<h2>Product Information</h2>'+identityBlock()+'<section class="fx-info-section"><h3>What it does</h3><p>'+esc(research?.researched===true&&research?.whatItDoes?research.whatItDoes:('FindIt identified '+productName()+', but has not verified a product-specific description from reliable sources yet.'))+'</p></section>'+
 (Array.isArray(research?.specifications)&&research.specifications.length?'<section class="fx-info-section"><h3>Published specifications</h3><dl>'+research.specifications.map(p=>'<dt>'+esc(p.name)+'</dt><dd>'+esc(p.value)+(validUrl(p.sourceUrl)?' <a href="'+esc(p.sourceUrl)+'" target="_blank" rel="noopener">Source</a>':'')+'</dd>').join('')+'</dl></section>':'')+
 (research?.bestFor?'<section class="fx-info-section"><h3>Best for</h3><p>'+esc(research.bestFor)+'</p></section>':'')+
 '<div class="fx-info-cols"><section class="fx-info-section"><h3>Pros / supported strengths</h3>'+(pros.length?'<ul>'+pros.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p>No product-specific strengths have been verified yet.</p>')+'</section><section class="fx-info-section"><h3>Considerations</h3>'+(cons.length?'<ul>'+cons.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p>No product-specific drawbacks have been verified yet.</p>')+'</section></div>'+
 '<section class="fx-info-section"><h3>Shopping information</h3><p>'+esc(offers.length?offers.length+' relevant retailer listing'+(offers.length===1?' has':'s have')+' been found for comparison.':'No exact retailer listing has been verified yet.')+'</p><button id="fxInfoCompare">Compare retailer results</button></section>'+
 (sources?'<section class="fx-info-section"><h3>Sources checked</h3><div class="fx-info-sources">'+sources+'</div></section>':''));
 $('#fxInfoCompare').onclick=showCompare;
}
function showCompare(){if(!productName())return searchModal();let offers=exactOffers().filter(o=>validUrl(o.product_url||o.url));openModal('<h2>Compare Prices</h2>'+identityBlock()+(offers.length?'<div class="fx-offer-list">'+offers.map(o=>{let u=o.product_url||o.url,p=verifiedPrices().includes(o)?money(o):'',stock=o.branchStockVerified===true&&/^(in_stock|out_of_stock|preorder|backorder)$/i.test(clean(o.availability))?clean(o.availability).replaceAll('_',' '):'Branch stock not verified';return '<article><div><b>'+esc(retailerName(o))+'</b><span>'+esc(o.product_name||productName())+'</span><small>'+esc((/^(in_stock|out_of_stock|preorder|backorder)$/i.test(clean(o.availability))?'Online availability: '+clean(o.availability).replaceAll('_',' ')+' · ':'')+stock)+'</small></div><strong>'+(p?esc(p):'Price not verified')+'</strong>'+(validUrl(u)?'<a href="'+esc(u)+'" target="_blank" rel="noopener">View retailer page</a>':'')+'</article>'}).join('')+'</div>':'<div class="fx-info-empty"><b>No exact retailer price has been verified yet.</b><p>FindIt checked for retailer evidence but will not fill this page with made-up prices. Try adding the exact model, size or barcode to the product search.</p></div>')+nearbyHtml())}
function nearbyHtml(){let stores=st()?.stores||[];return '<section class="fx-info-section"><h3>Nearby retailers</h3>'+(stores.length?'<div class="fx-nearby-list">'+stores.slice(0,10).map(storeRow).join('')+'</div>':'<p>No relevant nearby retailers have been returned for the current product'+(st()?.coords?' in the selected radius.':'. Location has not been supplied for this search.')+'</p>')+'</section>'}
async function showNearby(){if(!productName())return searchModal();const state=st();if(!state?.stores?.length){openModal('<h2>Nearby Stores</h2>'+identityBlock()+'<p>Checking location and nearby retailers…</p>');const coords=await getLocationIfAlreadyAllowed();if(!coords){openModal('<h2>Nearby Stores</h2>'+identityBlock()+'<p>Location access is needed to find nearby retailers. Allow location in your browser settings and try again.</p>');return}try{const response=await json('/api/nearby',{lat:coords.lat,lon:coords.lon,identification:ident(),radiusKm:state.radius||10},22000);if(Array.isArray(response?.stores)){state.stores=response.stores;syncAll();document.dispatchEvent(new CustomEvent('findit:nearby-updated',{detail:{stores:state.stores}}))}}catch(e){console.error('FindIt nearby retry failed',e);openModal('<h2>Nearby Stores</h2>'+identityBlock()+'<p>The nearby retailer search failed. Please try again.</p>');return}}openModal('<h2>Nearby Stores</h2>'+identityBlock()+nearbyHtml())}
async function hydrateIdentifiedPhoto(){
 if(owned||busy||!productName())return;
 const s=st(),i=ident();if(!s||!i||!productName(i))return;
 owned=true;busy=true;commerce=null;research=null;
 const generation=++photoGeneration,photoFile=s.file;
 try{
  syncIdentity(i);
  const coords=await getLocationIfAlreadyAllowed(),payload={identification:i,...(coords?{lat:coords.lat,lon:coords.lon}:{})};
  const tasks=[
   json('/api/product-intelligence-v2',payload,30000).catch(e=>{console.error('FindIt photo commerce failed',e);return null}),
   coords?json('/api/nearby',{lat:coords.lat,lon:coords.lon,identification:i,radiusKm:s.radius||10},22000).catch(e=>{console.error('FindIt photo nearby failed',e);return null}):Promise.resolve(null)
  ];
  const [ci,ni]=await Promise.all(tasks);if(generation!==photoGeneration||st()!==s||s.file!==photoFile)return;commerce=ci;
  const ri=await json('/api/product-insights',{identification:i,offers:Array.isArray(ci?.offers)?ci.offers:[]},24000).catch(e=>{console.error('FindIt photo product insights failed',e);return null});
  if(generation!==photoGeneration||st()!==s||s.file!==photoFile)return;
  research=ri?.researched===false?null:ri;
  if(Array.isArray(ci?.offers)){s.offers=ci.offers;window.productIntelligence=ci}else console.warn('FindIt photo commerce response has no offer list');
  // Do not erase an already truthful nearby result when the optional refresh returns empty.
  if(Array.isArray(ni?.stores))s.stores=ni.stores;else if(coords)console.warn('FindIt photo nearby response has no store list');
  syncAll();saveRecent(i);
  document.dispatchEvent(new CustomEvent('findit:dashboard-sync',{detail:{result:s.result}}));
  if(s.stores?.length)document.dispatchEvent(new CustomEvent('findit:nearby-updated',{detail:{stores:s.stores}}));
 }finally{if(generation===photoGeneration)busy=false}
}
function recoveryNote(){return st()?.result?.requiresUserInput||st()?.result?.identification?.requiresModelConfirmation?clean(st().result.message||'FindIt could not identify this photo confidently. Enter the product name or barcode to continue.'):'Enter the product name, brand and model, or barcode first. This lets FindIt look for matching product information and retailers.'}
function handlePhotoResult(){
 const s=st(),partial=s?.result?.identification?.requiresModelConfirmation===true,failed=s?.result?.requiresUserInput===true||partial;let recovery=$('#fxPhotoRecovery');
 if(!s?.file||productName()&&!partial||!failed){if(recovery)recovery.hidden=true;return}
 if(!recovery){const card=$('#finditExactShell .fx-search-card');if(!card)return;recovery=document.createElement('section');recovery.id='fxPhotoRecovery';recovery.innerHTML='<p></p><button type="button">Search by name or barcode</button>';card.appendChild(recovery);recovery.querySelector('button').onclick=()=>searchModal(recoveryNote(),ident().suggestedLabel||productName())}
 recovery.querySelector('p').textContent=partial?'Recognised '+productName()+'. Add the exact model or label to get product-specific facts and matching offers.':'You can still search. Type the brand, product name and size printed on the label, or enter its barcode.';recovery.hidden=false;
 if(!partial&&$('#fxProductName'))$('#fxProductName').textContent='Product not identified';if($('#fxProductDesc'))$('#fxProductDesc').textContent=recoveryNote();
}
function closeInformation(){let m=$('#fxInformationModal');if(m)m.classList.remove('open')}
function capture(e){let t=e.target.closest?.('#finditExactShell [data-fx], #finditExactShell [data-power-search]');if(!t)return;let a=t.dataset.fx;if(a!=='product'&&a!=='compare'&&a!=='nearby'&&a!=='assistant')closeInformation();if(t.dataset.powerSearch!==undefined||t.matches?.('.fx-search-tabs [data-fx="assistant"]')){e.preventDefault();e.stopImmediatePropagation();searchModal();return}if(!productName()&&['product','compare','nearby'].includes(a)){if(a==='compare'&&!document.body.classList.contains('premium-active')&&localStorage.getItem('findit_premium_beta')!=='1')return;e.preventDefault();e.stopImmediatePropagation();searchModal(recoveryNote());return}if(a==='product'&&ident().requiresModelConfirmation){e.preventDefault();e.stopImmediatePropagation();showProductInfo();return}if(!owned)return;if(a==='product'){return}if(a==='compare'){e.preventDefault();e.stopImmediatePropagation();showCompare();return}if(a==='nearby'){e.preventDefault();e.stopImmediatePropagation();showNearby();return}}
window.addEventListener('click',capture,true);
let lastPhotoFile=null;
document.addEventListener('findit:results-rendered',()=>setTimeout(()=>{const s=st();if(s?.file&&s.file!==lastPhotoFile){lastPhotoFile=s.file;photoGeneration++;owned=false;busy=false;commerce=null;research=null;}if(owned&&productName())syncAll();else if(s?.file&&productName()){hydrateIdentifiedPhoto();handlePhotoResult();}else if(!productName())handlePhotoResult()},40));
document.addEventListener('findit:nearby-updated',()=>{if(owned)setTimeout(syncAll,40)});
document.addEventListener('findit:new-photo-selected',()=>{if($('#fxPhotoRecovery'))$('#fxPhotoRecovery').hidden=true});
window.finditRunProductSearch=runSearch;
const style=document.createElement('style');style.textContent=`.fx-info-modal{display:none;position:fixed;inset:0;z-index:200000;background:rgba(1,7,16,.78);padding:20px;overflow:auto}.fx-info-modal.open{display:grid;place-items:center}.fx-info-card{position:relative;width:min(820px,100%);max-height:90vh;overflow:auto;background:#071727;color:#eef6ff;border:1px solid #29455e;border-radius:22px;padding:26px;box-shadow:0 30px 100px #0009}.fx-info-x{position:absolute;right:16px;top:12px;border:0;background:transparent;color:#fff;font-size:30px}.fx-info-card h2{font-size:27px;margin:0 42px 18px 0}.fx-info-card input{width:100%;box-sizing:border-box;background:#0d2134;color:#fff;border:1px solid #31516b;border-radius:12px;padding:14px;margin:8px 0 12px}.fx-info-card button{background:#3858ff;color:#fff;border:0;border-radius:11px;padding:12px 16px;font-weight:700;cursor:pointer}.fx-info-note,.fx-info-help{color:#9db0c3}.fx-info-identity{padding:16px;border:1px solid #29455e;border-radius:14px;background:#0a1d2f;margin-bottom:14px}.fx-info-identity h3{margin:0 0 10px;font-size:21px}.fx-info-identity>div{display:flex;flex-wrap:wrap;gap:8px}.fx-info-identity span{background:#10283d;padding:8px 10px;border-radius:9px}.fx-info-identity span b{display:block;font-size:10px;text-transform:uppercase;color:#75dfff}.fx-info-section{border-top:1px solid #20384d;padding:16px 0}.fx-info-section h3{margin:0 0 8px}.fx-info-cols{display:grid;grid-template-columns:1fr 1fr;gap:20px}.fx-info-sources{display:flex;flex-wrap:wrap;gap:8px}.fx-info-sources a,.fx-offer-list a,.fx-real-store a{color:#7fdfff}.fx-offer-list{display:grid;gap:10px}.fx-offer-list article{display:grid;grid-template-columns:1fr auto auto;gap:16px;align-items:center;border:1px solid #29455e;border-radius:13px;padding:14px}.fx-offer-list article span,.fx-offer-list article small{display:block;color:#9db0c3;margin-top:4px}.fx-nearby-list{display:grid;gap:8px}.fx-real-store{display:flex;justify-content:space-between;gap:12px;border:1px solid #20384d;border-radius:11px;padding:11px}.fx-real-store small,.fx-real-store em{display:block;color:#9db0c3;font-style:normal;margin-top:3px}.fx-info-empty,.fx-info-loading{padding:18px;border:1px solid #29455e;border-radius:13px;background:#0a1d2f}.fx-value-strip{display:flex;justify-content:space-between;gap:10px;padding:9px 0;color:#9db0c3}@media(max-width:650px){.fx-info-modal{padding:8px}.fx-info-card{padding:20px 16px}.fx-info-cols{grid-template-columns:1fr}.fx-offer-list article{grid-template-columns:1fr}.fx-real-store{flex-direction:column}}`;document.head.appendChild(style);
})();