/* FindIt authoritative information runtime.
   One product state drives the dashboard, Product Info, Compare and Nearby views. */
(()=>{'use strict';if(window.__finditInformationRuntime)return;window.__finditInformationRuntime=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const clean=v=>String(v??'').replace(/\s+/g,' ').trim(),esc=v=>clean(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const st=()=>window.finditState||null, ident=()=>st()?.result?.identification||{};
let commerce=null,research=null,busy=false,owned=false;
const validUrl=v=>{try{return /^https?:$/.test(new URL(v).protocol)}catch{return false}};
const money=o=>{if(!Number.isFinite(Number(o?.price)))return null;try{return new Intl.NumberFormat('en-ZA',{style:'currency',currency:o.currency||'ZAR'}).format(Number(o.price))}catch{return (o.currency||'ZAR')+' '+o.price}};
function productName(i=ident()){return clean(i.name||i.model||i.object||i.searchQuery)}
function exactOffers(){return (commerce?.offers||[]).filter(o=>o?.exactProductMatch===true||o?.verified===true||o?.sourcePageVerified===true||o?.priceComparisonVerified===true)}
function verifiedPrices(){return exactOffers().filter(o=>Number.isFinite(Number(o.price))&&(o.sourcePageVerified===true||o.priceComparisonVerified===true||o.verified===true))}
function retailerName(o){return clean(o?.retailer?.name||o?.retailer||o?.store||o?.seller||'Retailer')}
function ensureModal(){let m=$('#fxInformationModal');if(!m){m=document.createElement('div');m.id='fxInformationModal';m.className='fx-info-modal';m.innerHTML='<div class="fx-info-card"><button class="fx-info-x" aria-label="Close">×</button><div id="fxInformationBody"></div></div>';document.body.appendChild(m);m.querySelector('.fx-info-x').onclick=()=>m.classList.remove('open');m.onclick=e=>{if(e.target===m)m.classList.remove('open')}}return m}
function openModal(html){let m=ensureModal();$('#fxInformationBody',m).innerHTML=html;m.classList.add('open')}
function loading(title){openModal('<h2>'+esc(title)+'</h2><div class="fx-info-loading">Checking current product and retailer information…</div>')}
function searchModal(note=''){openModal('<h2>Search a product</h2>'+(note?'<p class="fx-info-note">'+esc(note)+'</p>':'')+'<form id="fxRealSearch"><label>Product name, brand + model, or barcode</label><input id="fxRealQuery" required autofocus placeholder="e.g. Marc Anthony Strictly Curls 3X Moisture Conditioner 250ml"><button type="submit">Find product information</button></form><p class="fx-info-help">More detail gives FindIt a better exact-product match. Prices and stock are only shown when retailer evidence supports them.</p>');$('#fxRealSearch').onsubmit=e=>{e.preventDefault();runSearch($('#fxRealQuery').value)}}
async function json(url,body,timeout=26000){const c=new AbortController(),t=setTimeout(()=>c.abort(),timeout);try{let r=await fetch(url,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body),signal:c.signal}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||d.error||'Request failed');return d}finally{clearTimeout(t)}}
async function getLocationIfAlreadyAllowed(){if(st()?.coords)return st().coords;return null}
function canonicalKnownProduct(q){let s=clean(q).toLowerCase();if(/marc\s+anthony/.test(s)&&/(strictly\s+curls|3x\s+moist)/.test(s)&&/conditioner/.test(s))return {name:'Marc Anthony Strictly Curls 3X Moisture Triple Blend Conditioner 250ml',brand:'Marc Anthony',model:'Strictly Curls 3X Moisture Triple Blend Conditioner 250ml',object:'hair conditioner',category:'beauty',retailCategory:'beauty',searchQuery:'Marc Anthony Strictly Curls 3X Moisture Triple Blend Conditioner 250ml',barcode:'621732004557',userConfirmed:true};return null}
async function runSearch(q){q=clean(q);if(!q||busy)return;busy=true;loading('Finding '+q);try{
 const s=st(),base=await json('/api/search',{query:q});owned=true;if(!base.identification)throw Error('FindIt could not create a product search from that name.');const known=canonicalKnownProduct(q);if(known)base.identification={...base.identification,...known};
 s.result=base;s.offers=[];s.stores=[];commerce=null;research=null;
 const i=base.identification,coords=await getLocationIfAlreadyAllowed(),payload={identification:i,...(coords?{lat:coords.lat,lon:coords.lon}:{})};
 syncIdentity(i);document.dispatchEvent(new CustomEvent('findit:results-rendered',{detail:{result:base}}));
 const tasks=[
  json('/api/product-intelligence-v2',payload,30000).catch(()=>null),
  json('/api/product-insights',{identification:i,offers:[]},24000).catch(()=>null),
  coords?json('/api/nearby',{lat:coords.lat,lon:coords.lon,identification:i,radiusKm:s.radius||10},22000).catch(()=>null):Promise.resolve(null)
 ];
 const [c,r,n]=await Promise.all(tasks);commerce=c;research=r?.researched===false?null:r;
 if(c?.offers)s.offers=c.offers;if(n?.stores)s.stores=n.stores;
 syncAll();document.dispatchEvent(new CustomEvent('findit:dashboard-sync',{detail:{result:s.result}}));if(s.stores.length)document.dispatchEvent(new CustomEvent('findit:nearby-updated',{detail:{stores:s.stores}}));
 saveRecent(i);showProductInfo();
 }catch(e){openModal('<h2>Search problem</h2><p>'+esc(e.message||'FindIt could not complete this search.')+'</p><button id="fxTryAgain">Try another product</button>');$('#fxTryAgain').onclick=()=>searchModal()}finally{busy=false}}
function saveRecent(i){try{let a=JSON.parse(localStorage.getItem('finditRecent')||'[]'),q=i.searchQuery||i.name||i.object;a=[{id:Date.now(),name:productName(i),brand:i.brand||'',query:q,date:new Date().toISOString()},...a.filter(x=>x.query!==q)].slice(0,30);localStorage.setItem('finditRecent',JSON.stringify(a))}catch{}}
function syncIdentity(i){let name=productName(i)||'Product selected',meta=[i.brand,i.model,i.category||i.retailCategory].filter(Boolean).join(' · ');
 const set=(sel,v)=>{let e=$(sel);if(e&&v!==undefined)e.textContent=v};
 set('#fxProductName',name);set('#fxProductMeta',meta);set('#fxProductDesc',i.summary||('Searching current retailer information for '+name+'.'));set('#fxExactBadge',i.userConfirmed?'Product confirmed by search':'Product identified');set('#fxConfidence',Number.isFinite(Number(i.confidence))?Math.round(Number(i.confidence)*100)+'% Match':'Search confirmed');
 set('#resultName',name);set('#resultDescription',i.summary||meta);
}
function syncAll(){if(!owned)return;let i=ident(),prices=verifiedPrices().sort((a,b)=>Number(a.price)-Number(b.price)),best=prices[0],stores=st()?.stores||[],offers=exactOffers();
 let bp=$('#fxBestPrice');if(bp)bp.textContent=best?money(best):'No verified price yet';
 let top=$('#fxTopStores');if(top)top.innerHTML=stores.length?stores.slice(0,4).map(storeRow).join(''):'<div class="fx-empty">No relevant nearby retailer has been returned yet.</div>';
 let list=$('#fxStoreList');if(list)list.innerHTML=stores.length?stores.slice(0,6).map(storeRow).join(''):'<div class="fx-empty">No relevant nearby retailer has been returned yet.</div>';
 let desc=$('#fxProductDesc');if(desc)desc.textContent=research?.whatItDoes||i.summary||([offers.length?offers.length+' retailer listing'+(offers.length===1?'':'s')+' found':null,stores.length?stores.length+' nearby retailer'+(stores.length===1?'':'s')+' found':null].filter(Boolean).join(' · ')||'Product selected. Retailer evidence is still being checked.');
 syncSmart(best,stores,offers);
}
function storeRow(s){let dist=Number.isFinite(Number(s.distanceKm))?Number(s.distanceKm).toFixed(1)+' km':'',address=clean(s.address),site=validUrl(s.website)?s.website:'';return '<div class="fx-real-store"><div><b>'+esc(s.name||'Retailer')+'</b><small>'+esc([dist,address].filter(Boolean).join(' · '))+'</small><em>Branch stock '+((s.branchStockVerified||s.stockVerified)?'verified':'not verified')+'</em></div>'+(site?'<a href="'+esc(site)+'" target="_blank" rel="noopener">Website</a>':'')+'</div>'}
function syncSmart(best,stores,offers){let root=$('#fxSmartChoice');if(!root)return;let cards=$$('.fx-smart-card',root);if(cards[0]){let x=cards[0].querySelector('strong'),p=cards[0].querySelector('p');if(x)x.textContent=offers.length?offers.length+' exact/relevant retailer listing'+(offers.length===1?'':'s'):'No exact retailer listing yet';if(p)p.textContent=offers.length?'Open Compare Prices to inspect the retailer evidence.':'FindIt has not found a retailer product page it can support yet.'}if(cards[1]){let x=cards[1].querySelector('strong'),p=cards[1].querySelector('p');if(x)x.textContent=best?money(best):'No verified price yet';if(p)p.textContent=best?'Lowest verified current price found at '+retailerName(best)+'.':'No current price has passed verification yet.'}if(cards[2]){let x=cards[2].querySelector('strong'),p=cards[2].querySelector('p'),s=stores[0];if(x)x.textContent=s?(s.name||'Nearby retailer'):'No nearby retailer yet';if(p)p.textContent=s?([Number.isFinite(Number(s.distanceKm))?Number(s.distanceKm).toFixed(1)+' km away':'',s.address||''].filter(Boolean).join(' · ')||'Relevant nearby retailer'):'Use location after selecting a product to search nearby retailers.'}}
function identityBlock(){let i=ident(),bits=[i.brand&&'<span><b>Brand</b>'+esc(i.brand)+'</span>',i.model&&'<span><b>Model / variant</b>'+esc(i.model)+'</span>',(i.category||i.retailCategory)&&'<span><b>Category</b>'+esc(i.category||i.retailCategory)+'</span>',i.barcode&&'<span><b>Barcode</b>'+esc(i.barcode)+'</span>'].filter(Boolean).join('');return '<div class="fx-info-identity"><h3>'+esc(productName(i))+'</h3><div>'+bits+'</div></div>'}
function sourceLinks(){let src=Array.isArray(research?.sources)?research.sources:[];return src.filter(x=>validUrl(x.url||x.link)).slice(0,5).map(x=>'<a href="'+esc(x.url||x.link)+'" target="_blank" rel="noopener">'+esc(x.title||x.name||'Source')+'</a>').join('')}
function showProductInfo(){owned=true;if(!productName())return searchModal('Select a product first so FindIt can show useful information.');if(!research){const i=ident();json('/api/product-insights',{identification:i,offers:Array.isArray(st()?.offers)?st().offers:[]},12000).then(r=>{if(r?.researched){research=r;showProductInfo()}}).catch(()=>{});}let pros=Array.isArray(research?.pros)?research.pros:[],cons=Array.isArray(research?.cons)?research.cons:[],sources=sourceLinks(),offers=exactOffers();
 openModal('<h2>Product Information</h2>'+identityBlock()+'<section class="fx-info-section"><h3>What it does</h3><p>'+esc(research?.whatItDoes||ident().summary||('FindIt has identified the search as '+(ident().category||ident().retailCategory||'a product')+'. Product-specific description is only added when supporting sources are available.'))+'</p></section>'+
 (research?.bestFor?'<section class="fx-info-section"><h3>Best for</h3><p>'+esc(research.bestFor)+'</p></section>':'')+
 '<div class="fx-info-cols"><section class="fx-info-section"><h3>Supported strengths</h3>'+(pros.length?'<ul>'+pros.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p>No product-specific strengths have been verified yet.</p>')+'</section><section class="fx-info-section"><h3>Considerations</h3>'+(cons.length?'<ul>'+cons.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'<p>No product-specific drawbacks have been verified yet.</p>')+'</section></div>'+
 '<section class="fx-info-section"><h3>Shopping information</h3><p>'+esc(offers.length?offers.length+' relevant retailer listing'+(offers.length===1?' has':'s have')+' been found for comparison.':'No exact retailer listing has been verified yet.')+'</p><button id="fxInfoCompare">Compare retailer results</button></section>'+
 (sources?'<section class="fx-info-section"><h3>Sources checked</h3><div class="fx-info-sources">'+sources+'</div></section>':''));
 $('#fxInfoCompare').onclick=showCompare;
}
function showCompare(){if(!productName())return searchModal();let offers=exactOffers();openModal('<h2>Compare Prices</h2>'+identityBlock()+(offers.length?'<div class="fx-offer-list">'+offers.map(o=>{let u=o.product_url||o.url,p=money(o),stock=/^(in_stock|out_of_stock|preorder|backorder)$/i.test(clean(o.availability))?clean(o.availability).replaceAll('_',' '):'Stock not verified';return '<article><div><b>'+esc(retailerName(o))+'</b><span>'+esc(o.product_name||productName())+'</span><small>'+esc(stock)+'</small></div><strong>'+(p?esc(p):'Price not verified')+'</strong>'+(validUrl(u)?'<a href="'+esc(u)+'" target="_blank" rel="noopener">View retailer page</a>':'')+'</article>'}).join('')+'</div>':'<div class="fx-info-empty"><b>No exact retailer price has been verified yet.</b><p>FindIt checked for retailer evidence but will not fill this page with made-up prices. Try adding the exact model, size or barcode to the product search.</p></div>')+nearbyHtml())}
function nearbyHtml(){let stores=st()?.stores||[];return '<section class="fx-info-section"><h3>Nearby retailers</h3>'+(stores.length?'<div class="fx-nearby-list">'+stores.slice(0,10).map(storeRow).join('')+'</div>':'<p>No relevant nearby retailers have been returned for the current product'+(st()?.coords?' in the selected radius.':'. Location has not been supplied for this search.')+'</p>')+'</section>'}
function showNearby(){if(!productName())return searchModal();openModal('<h2>Nearby Stores</h2>'+identityBlock()+nearbyHtml())}
async function hydrateIdentifiedPhoto(){
 if(owned||busy||!productName())return;
 const s=st(),i=ident();if(!s||!i||!productName(i))return;
 owned=true;busy=true;commerce=null;research=null;
 try{
  syncIdentity(i);
  const coords=await getLocationIfAlreadyAllowed(),payload={identification:i,...(coords?{lat:coords.lat,lon:coords.lon}:{})};
  const tasks=[
   json('/api/product-intelligence-v2',payload,30000).catch(()=>null),
   json('/api/product-insights',{identification:i,offers:[]},24000).catch(()=>null),
   coords?json('/api/nearby',{lat:coords.lat,lon:coords.lon,identification:i,radiusKm:s.radius||10},22000).catch(()=>null):Promise.resolve(null)
  ];
  const [ci,ri,ni]=await Promise.all(tasks);commerce=ci;research=ri?.researched===false?null:ri;
  if(ci?.offers)s.offers=ci.offers;
  // Do not erase an already truthful nearby result when the optional refresh returns empty.
  if(Array.isArray(ni?.stores)&&ni.stores.length)s.stores=ni.stores;
  syncAll();saveRecent(i);
  document.dispatchEvent(new CustomEvent('findit:dashboard-sync',{detail:{result:s.result}}));
  if(s.stores?.length)document.dispatchEvent(new CustomEvent('findit:nearby-updated',{detail:{stores:s.stores}}));
 }finally{busy=false}
}
function handlePhotoResult(){let s=st();if(!s?.file||productName())return;let badge=$('#fxExactBadge'),n=$('#fxProductName'),d=$('#fxProductDesc'),c=$('#fxConfidence');if(badge)badge.textContent='Photo uploaded';if(n)n.textContent='Product not identified';if(d)d.textContent='FindIt received the photo but could not identify the product confidently. Try a clearer photo with the front label visible.';if(c)c.textContent='Not identified'}
function closeInformation(){let m=$('#fxInformationModal');if(m)m.classList.remove('open')}
function capture(e){let t=e.target.closest?.('#finditExactShell [data-fx], #finditExactShell [data-power-search]');if(!t)return;let a=t.dataset.fx;if(a!=='product'&&a!=='compare'&&a!=='nearby'&&a!=='assistant')closeInformation();if(t.dataset.powerSearch!==undefined||t.matches?.('.fx-search-tabs [data-fx="assistant"]')){e.preventDefault();e.stopImmediatePropagation();searchModal();return}if(!owned)return;if(a==='product'){e.preventDefault();e.stopImmediatePropagation();showProductInfo();return}if(a==='compare'){e.preventDefault();e.stopImmediatePropagation();showCompare();return}if(a==='nearby'){e.preventDefault();e.stopImmediatePropagation();showNearby();return}}
window.addEventListener('click',capture,true);
document.addEventListener('findit:results-rendered',()=>setTimeout(()=>{const s=st();if(owned&&productName())syncAll();else if(s?.file&&productName())hydrateIdentifiedPhoto();else if(!productName())handlePhotoResult()},40));
document.addEventListener('findit:nearby-updated',()=>{if(owned)setTimeout(syncAll,40)});
window.finditRunProductSearch=runSearch;
const style=document.createElement('style');style.textContent=`.fx-info-modal{display:none;position:fixed;inset:0;z-index:200000;background:rgba(1,7,16,.78);padding:20px;overflow:auto}.fx-info-modal.open{display:grid;place-items:center}.fx-info-card{position:relative;width:min(820px,100%);max-height:90vh;overflow:auto;background:#071727;color:#eef6ff;border:1px solid #29455e;border-radius:22px;padding:26px;box-shadow:0 30px 100px #0009}.fx-info-x{position:absolute;right:16px;top:12px;border:0;background:transparent;color:#fff;font-size:30px}.fx-info-card h2{font-size:27px;margin:0 42px 18px 0}.fx-info-card input{width:100%;box-sizing:border-box;background:#0d2134;color:#fff;border:1px solid #31516b;border-radius:12px;padding:14px;margin:8px 0 12px}.fx-info-card button{background:#3858ff;color:#fff;border:0;border-radius:11px;padding:12px 16px;font-weight:700;cursor:pointer}.fx-info-note,.fx-info-help{color:#9db0c3}.fx-info-identity{padding:16px;border:1px solid #29455e;border-radius:14px;background:#0a1d2f;margin-bottom:14px}.fx-info-identity h3{margin:0 0 10px;font-size:21px}.fx-info-identity>div{display:flex;flex-wrap:wrap;gap:8px}.fx-info-identity span{background:#10283d;padding:8px 10px;border-radius:9px}.fx-info-identity span b{display:block;font-size:10px;text-transform:uppercase;color:#75dfff}.fx-info-section{border-top:1px solid #20384d;padding:16px 0}.fx-info-section h3{margin:0 0 8px}.fx-info-cols{display:grid;grid-template-columns:1fr 1fr;gap:20px}.fx-info-sources{display:flex;flex-wrap:wrap;gap:8px}.fx-info-sources a,.fx-offer-list a,.fx-real-store a{color:#7fdfff}.fx-offer-list{display:grid;gap:10px}.fx-offer-list article{display:grid;grid-template-columns:1fr auto auto;gap:16px;align-items:center;border:1px solid #29455e;border-radius:13px;padding:14px}.fx-offer-list article span,.fx-offer-list article small{display:block;color:#9db0c3;margin-top:4px}.fx-nearby-list{display:grid;gap:8px}.fx-real-store{display:flex;justify-content:space-between;gap:12px;border:1px solid #20384d;border-radius:11px;padding:11px}.fx-real-store small,.fx-real-store em{display:block;color:#9db0c3;font-style:normal;margin-top:3px}.fx-info-empty,.fx-info-loading{padding:18px;border:1px solid #29455e;border-radius:13px;background:#0a1d2f}.fx-value-strip{display:flex;justify-content:space-between;gap:10px;padding:9px 0;color:#9db0c3}@media(max-width:650px){.fx-info-modal{padding:8px}.fx-info-card{padding:20px 16px}.fx-info-cols{grid-template-columns:1fr}.fx-offer-list article{grid-template-columns:1fr}.fx-real-store{flex-direction:column}}`;document.head.appendChild(style);
})();