(()=>{
  'use strict';
  if(window.__finditModalNavFixV5)return;window.__finditModalNavFixV5=true;
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  function premiumActive(){try{return localStorage.getItem('findit_premium_beta')==='1'||localStorage.getItem('finditPremium')==='1'||localStorage.getItem('finditPremium')==='true'||window.premiumState?.active===true||document.body.classList.contains('premium-active')}catch{return false}}
  function hidePanel(sel){const el=$(sel);if(!el)return;el.classList.add('hidden');el.removeAttribute('hidden');el.style.removeProperty('display');el.setAttribute('aria-hidden','true')}
  function closeDashboardModals(){hidePanel('#fxPanelModal');hidePanel('#fxSettingsModal')}
  function removeLegacyChrome(){const drawer=$('#drawer'),backdrop=$('#drawerBackdrop'),menu=$('#menuBtn');if(drawer){drawer.classList.add('hidden');drawer.setAttribute('aria-hidden','true')}if(backdrop)backdrop.classList.add('hidden');if(menu)menu.style.setProperty('display','none','important')}
  function syncPremiumUi(){const on=premiumActive();document.body.classList.toggle('fx-premium-already-active',on);const side=$('#fxPremiumSideButton'),bottom=$('#fxPremiumBottomButton');if(side)side.hidden=on;if(bottom)bottom.hidden=on;const card=$('.fx-premium');if(card&&on)card.setAttribute('aria-label','FindIt Premium is active')}
  const domains={'nike':'nike.com','totalsports':'totalsports.co.za','sportscene':'sportscene.co.za','makro':'makro.co.za','checkers':'checkers.co.za','pick n pay':'pnp.co.za','shoprite':'shoprite.co.za','woolworths':'woolworths.co.za','game':'game.co.za','clicks':'clicks.co.za','dis chem':'dischem.co.za','adidas':'adidas.co.za','jd sports':'jdsports.co.za','bash':'bash.com','takealot':'takealot.com','builders':'builders.co.za','incredible connection':'incredible.co.za','istore':'istore.co.za','computer mania':'computermania.co.za','sportsmans warehouse':'sportsmanswarehouse.co.za','cape union mart':'capeunionmart.co.za','outdoor warehouse':'outdoorwarehouse.co.za','mr price home':'mrphome.com','buco':'buco.co.za','mica':'mica.co.za'};
  const norm=v=>String(v||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
  const money=n=>Number.isFinite(Number(n))?`R ${Number(n).toLocaleString('en-ZA',{minimumFractionDigits:2,maximumFractionDigits:2})}`:'—';
  function state(){try{return window.finditState||window.state||null}catch{return null}}
  function retailerDomain(name){const n=norm(name);for(const [k,d] of Object.entries(domains)){if(n===k||n.includes(k)||k.includes(n))return d}return''}
  function logoMarkup(name,size=28){const d=retailerDomain(name);if(!d)return'';const safe=String(name||'Retailer').replace(/&/g,'&amp;').replace(/"/g,'&quot;').replace(/</g,'&lt;');return `<img src="https://www.google.com/s2/favicons?domain=${encodeURIComponent(d)}&sz=64" alt="${safe} logo" width="${size}" height="${size}" loading="lazy">`}
  function installStyle(){if($('#finditModalNavFixStyleV5'))return;const s=document.createElement('style');s.id='finditModalNavFixStyleV5';s.textContent=`
    #fxPanelModal,#fxSettingsModal{pointer-events:none!important}
    #fxPanelModal .fx-modal-card,#fxSettingsModal .fx-modal-card{pointer-events:auto!important;touch-action:auto!important;overscroll-behavior:contain;scrollbar-gutter:stable}
    body.findit-exact-dashboard #drawer,body.findit-exact-dashboard #drawerBackdrop,body.findit-exact-dashboard #menuBtn{display:none!important;visibility:hidden!important;pointer-events:none!important}
    body.fx-premium-already-active #fxPremiumSideButton,body.fx-premium-already-active #fxPremiumBottomButton{display:none!important}
    body.fx-premium-already-active .fx-premium{cursor:default!important}
    .fx-store-logo img,.fx-top-list .fx-store-logo img{width:100%;height:100%;object-fit:contain;border-radius:5px;background:#fff;padding:3px;box-sizing:border-box}
    #fxPanelBody .fx-offer-logo{width:36px;height:36px;display:grid;place-items:center;border:1px solid #213852;border-radius:9px;background:#fff;overflow:hidden;flex:0 0 auto;color:#07111e;font-size:10px;font-weight:900}
    #fxPanelBody .fx-offer-logo img{width:27px;height:27px;object-fit:contain}
    #fxPanelBody .fx-offer-main{display:flex;align-items:center;gap:11px;min-width:0}
    #fxPanelBody .fx-offer-main>span:last-child{min-width:0}
    #fxPanelBody .fx-offer{grid-template-columns:minmax(0,1fr) auto!important}
    #fxPanelBody .fx-compare-note{margin:7px 0 14px;color:#8193aa;font-size:11px;line-height:1.45}
    #fxPanelBody .fx-trip-controls{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px;margin:10px 0 16px;padding:12px;border:1px solid #1d3049;border-radius:12px;background:#091728}
    #fxPanelBody .fx-trip-controls label{display:grid;gap:5px;color:#90a1b7;font-size:10px}#fxPanelBody .fx-trip-controls input{width:100%;box-sizing:border-box;border:1px solid #27405e;border-radius:8px;background:#071321;color:#fff;padding:9px}
    #fxPanelBody .fx-ranked{border-color:#2c8b6b!important;box-shadow:0 0 0 1px rgba(61,220,160,.12) inset}#fxPanelBody .fx-cheapest{display:inline-block;margin-left:7px;padding:3px 6px;border-radius:999px;background:#0b5b43;color:#7ff0bd;font-size:9px;font-weight:900}
    #fxPanelBody .fx-cost-detail{margin-top:4px;color:#8294aa;font-size:10px;line-height:1.4}#fxPanelBody .fx-total{color:#7ff0bd;font-size:12px;font-weight:900}
    @media(max-width:620px){#fxPanelBody .fx-trip-controls{grid-template-columns:1fr}}
  `;document.head.appendChild(s)}
  async function enrichVerifiedOffers(){let st=state();const i=st?.result?.identification;if(!i||!String(i.name||i.model||i.object||'').trim())return;if(Array.isArray(st?.offers)&&st.offers.some(o=>(o?.verified===true||o?.sourcePageVerified===true)&&Number.isFinite(Number(o.price))))return;const q=i.searchQuery||i.query||i.name||i.model||i.object;try{const c=new AbortController(),t=setTimeout(()=>c.abort(),18000);const r=await fetch('/api/product-intelligence-v2',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({...i,query:q,searchQuery:q}),signal:c.signal});clearTimeout(t);if(!r.ok)return;const data=await r.json();if(Array.isArray(data?.offers)){st.offers=data.offers;window.productIntelligence=data;document.dispatchEvent(new CustomEvent('findit:nearby-updated'))}}catch{}}
  function decorateStoreLogos(){
    $$('.fx-store').forEach(card=>{const name=card.querySelector('b')?.textContent?.trim()||'';const box=card.querySelector('.fx-store-logo');if(box&&name&&retailerDomain(name)&&!box.querySelector('img'))box.innerHTML=logoMarkup(name,28)});
    $$('#fxTopStores button').forEach(card=>{const name=card.querySelector('b')?.textContent?.trim()||'';const box=card.querySelector('.fx-store-logo');if(box&&name&&retailerDomain(name)&&!box.querySelector('img'))box.innerHTML=logoMarkup(name,28)});
  }
  function fuelSettings(){let price=Number(localStorage.getItem('finditFuelPricePerLitre')),cons=Number(localStorage.getItem('finditFuelConsumptionL100'));if(!Number.isFinite(price)||price<=0)price=0;if(!Number.isFinite(cons)||cons<=0)cons=8;return{price,cons}}
  function saveFuel(price,cons){if(Number.isFinite(price)&&price>0)localStorage.setItem('finditFuelPricePerLitre',String(price));else localStorage.removeItem('finditFuelPricePerLitre');if(Number.isFinite(cons)&&cons>0)localStorage.setItem('finditFuelConsumptionL100',String(cons))}
  function nearestStoreFor(name){const n=norm(name),stores=Array.isArray(state()?.stores)?state().stores:[];return stores.filter(s=>{const x=norm(s?.name);return x&&(x===n||x.includes(n)||n.includes(x))&&Number.isFinite(Number(s.distanceKm))}).sort((a,b)=>Number(a.distanceKm)-Number(b.distanceKm))[0]||null}
  function verifiedOffersByRetailer(){const offers=Array.isArray(state()?.offers)?state().offers:[];const map=new Map();offers.filter(o=>(o?.verified===true||o?.sourcePageVerified===true)&&Number.isFinite(Number(o.price))).forEach(o=>{const name=String(o?.retailer?.name||o?.retailer||'Retailer').trim()||'Retailer',key=norm(name),price=Number(o.price);const old=map.get(key);if(!old||price<old.price)map.set(key,{name,price,url:o.product_url||o.url||'',availability:o.availability||'Verified current listing',count:(old?.count||0)+1});else old.count=(old.count||1)+1});return [...map.values()]}
  function rebuildCompare(){
    const body=$('#fxPanelBody');if(!body||!/^Compare Prices$/i.test(body.querySelector('.fx-panel-title')?.textContent?.trim()||''))return;
    const online=verifiedOffersByRetailer(),stores=Array.isArray(state()?.stores)?state().stores:[],{price:fuelPrice,cons}=fuelSettings();
    const allNames=new Set([...online.map(x=>norm(x.name)),...stores.map(x=>norm(x.name)).filter(Boolean)]);
    const rows=[];for(const key of allNames){const off=online.find(x=>norm(x.name)===key),store=nearestStoreFor(off?.name||stores.find(s=>norm(s.name)===key)?.name||key),name=off?.name||store?.name||key,productPrice=off?.price??((store?.branchPriceVerified&&Number.isFinite(Number(store.price)))?Number(store.price):null),distance=Number.isFinite(Number(store?.distanceKm))?Number(store.distanceKm):null,tripKm=distance!=null?distance*2:null,fuelCost=(tripKm!=null&&fuelPrice>0)?tripKm*(cons/100)*fuelPrice:null,total=(productPrice!=null)?productPrice+(fuelCost||0):null;rows.push({name,off,store,productPrice,distance,tripKm,fuelCost,total})}
    rows.sort((a,b)=>(a.total??1e12)-(b.total??1e12)||(a.productPrice??1e12)-(b.productPrice??1e12));const comparable=rows.filter(r=>r.total!=null),best=comparable[0];
    const controls=`<div class="fx-trip-controls"><label>Petrol price (R/litre)<input id="fxFuelPrice" type="number" min="0" step="0.01" placeholder="Enter current petrol price" value="${fuelPrice||''}"></label><label>Your car fuel use (L/100 km)<input id="fxFuelCons" type="number" min="1" step="0.1" value="${cons}"></label></div>`;
    let html=`<h2 class="fx-panel-title">Compare Prices</h2><p class="fx-panel-sub">FindIt compares one best verified price per retailer, then includes estimated return-trip petrol cost where a nearby branch distance is known.</p>${controls}`;
    if(best){html+=`<div class="fx-info-cell fx-ranked" style="margin-bottom:14px"><small>AI cheapest overall</small><strong>${best.name} — ${money(best.total)}</strong><div class="fx-cost-detail">${best.productPrice!=null?`Product ${money(best.productPrice)}`:''}${best.fuelCost!=null?` + estimated petrol ${money(best.fuelCost)}`:''}. ${fuelPrice>0?'Petrol is calculated from your current location to the nearest matching branch and back.':'Add the current petrol price above to include travel cost.'}</div></div>`}
    html+='<h3>Retailers</h3><div class="fx-compare-note">All retailers returned by the verified offer search or nearby-store search are listed. If the same retailer returned several verified prices, FindIt keeps its lowest verified price instead of treating it as a different retailer.</div>';
    if(!rows.length)html+='<div class="fx-info-cell">No retailer results are available yet.</div>';else html+=rows.map((r,i)=>{const d=retailerDomain(r.name),logo=logoMarkup(r.name,27)||r.name.slice(0,2).toUpperCase(),detail=[];if(r.productPrice!=null)detail.push(`Product ${money(r.productPrice)}`);else detail.push('Product price not verified');if(r.distance!=null)detail.push(`${r.distance.toFixed(1)} km away`);if(r.fuelCost!=null)detail.push(`return petrol ${money(r.fuelCost)}`);else if(r.distance!=null&&!fuelPrice)detail.push('add petrol price for travel cost');if(r.off?.count>1)detail.push(`${r.off.count} verified listings checked`);return `<div class="fx-offer ${best&&r===best?'fx-ranked':''}"><span class="fx-offer-main"><span class="fx-offer-logo">${logo}</span><span><b>${r.name}${best&&r===best?'<span class="fx-cheapest">CHEAPEST</span>':''}</b><small>${detail.join(' • ')}</small>${r.total!=null?`<div class="fx-total">Total ${money(r.total)}</div>`:''}</span></span><span>${r.productPrice!=null?`<b>${money(r.productPrice)}</b>`:'<b>Price not verified</b>'}${r.off?.url?`<a href="${r.off.url.replace(/"/g,'&quot;')}" target="_blank" rel="noopener">View deal</a>`:''}</span></div>`}).join('');
    body.innerHTML=html;
    const p=$('#fxFuelPrice'),c=$('#fxFuelCons');const recalc=()=>{saveFuel(Number(p?.value),Number(c?.value));rebuildCompare()};p?.addEventListener('change',recalc,{once:true});c?.addEventListener('change',recalc,{once:true});
  }
  function refreshUi(){removeLegacyChrome();syncPremiumUi();decorateStoreLogos();rebuildCompare()}
  window.addEventListener('pointerdown',e=>{const t=e.target?.closest?.('#finditExactShell [data-fx],#finditExactShell [data-fxnav]');if(!t)return;const action=t.dataset.fx||t.dataset.fxnav||'';if(!['product','compare','settings'].includes(action))closeDashboardModals();if(t.dataset.fx==='premium'&&premiumActive()){e.preventDefault();e.stopImmediatePropagation();syncPremiumUi()}},true);
  window.addEventListener('click',e=>{const t=e.target?.closest?.('#finditExactShell [data-fx],#finditExactShell [data-fxnav]');if(t&&t.dataset.fx==='premium'&&premiumActive()){e.preventDefault();e.stopImmediatePropagation();syncPremiumUi();return}if(t){setTimeout(refreshUi,0);setTimeout(refreshUi,100)}if(e.target=== $('#fxPanelModal')||e.target=== $('#fxSettingsModal'))closeDashboardModals()},true);
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeDashboardModals()});
  document.addEventListener('findit:results-rendered',()=>{refreshUi();setTimeout(enrichVerifiedOffers,120)});
  document.addEventListener('findit:nearby-updated',()=>setTimeout(refreshUi,0));document.addEventListener('findit:dashboard-sync',()=>setTimeout(refreshUi,0));window.addEventListener('storage',refreshUi);
  function init(){installStyle();refreshUi();setTimeout(enrichVerifiedOffers,500);setTimeout(refreshUi,700)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
