(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,c='ZAR')=>{try{return new Intl.NumberFormat('en-ZA',{style:'currency',currency:c||'ZAR'}).format(Number(n))}catch{return`${c||'ZAR'} ${Number(n).toFixed(2)}`}};
const stateSafe=()=>{try{return state}catch{return null}};
let busy=false,lastKey='';
function mount(){const root=$('#exactSellerResults');if(!root)return null;let box=$('#finditPriceCheckBox');if(box)return box;box=document.createElement('section');box.id='finditPriceCheckBox';box.style.marginTop='18px';const marker=[...root.querySelectorAll('.section-title-row')].find(x=>/search more retailers/i.test(x.textContent||''));if(marker?.parentNode)marker.parentNode.insertBefore(box,marker);else root.appendChild(box);return box}
async function sync(){const s=stateSafe(),i=s?.result?.identification||{};const q=[i.brand,i.model,i.searchQuery||i.name||i.object].filter(Boolean).join(' ').trim();if(!q||busy||lastKey===q)return;const box=mount();if(!box)return;busy=true;box.innerHTML='<div class="empty-state">Checking PriceCheck comparison data…</div>';
try{const r=await fetch('/api/pricecheck',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(i)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.error||'PriceCheck lookup failed');const x=d.result;if(!x){box.innerHTML=`<div class="section-title-row"><div><p class="section-kicker">PRICECHECK COMPARISON</p><h3>No exact PriceCheck match verified</h3><p>PriceCheck did not provide a strong enough exact-product match this time.</p></div></div><a class="btn secondary" href="${esc(d.searchUrl||'#')}" target="_blank" rel="noopener noreferrer">Search PriceCheck →</a>`;lastKey=q;return}
const stock=x.availability==='in_stock'?'Online listing appears available':x.availability==='out_of_stock'?'Online listing appears out of stock':'Online stock not verified';const price=x.price!=null?money(x.price,x.currency||'ZAR'):'Price not verified';box.innerHTML=`<div class="section-title-row"><div><p class="section-kicker">PRICECHECK COMPARISON</p><h3>Secondary price check</h3><p>PriceCheck is used as a comparison source only. Physical branch stock is never claimed from this result.</p></div></div><article class="offer-card"><div><span class="findit-exact-badge">✓ Strong PriceCheck match</span><h4>${esc(x.title||q)}</h4><p>PriceCheck</p><p>${esc(stock)} • Branch stock not verified</p><a href="${esc(x.url||d.searchUrl||'#')}" target="_blank" rel="noopener noreferrer">View PriceCheck →</a></div><div class="price">${esc(price)}</div><small class="findit-checked">Checked now • Comparison source, not branch inventory</small></article>`;lastKey=q}catch(e){box.innerHTML='<div class="empty-state"><strong>PriceCheck comparison unavailable.</strong><p>FindIt will continue using direct retailer results.</p></div>'}finally{busy=false}}
function init(){document.addEventListener('findit:results-rendered',()=>setTimeout(sync,250));new MutationObserver(()=>{if($('#exactSellerResults')&&!$('#finditPriceCheckBox'))setTimeout(sync,150)}).observe(document.body,{childList:true,subtree:true});setTimeout(sync,1200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();