(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=(n,c='ZAR')=>{try{return new Intl.NumberFormat('en-ZA',{style:'currency',currency:c||'ZAR'}).format(Number(n))}catch{return`${c||'ZAR'} ${Number(n).toFixed(2)}`}};
function mount(){const root=$('#exactSellerResults');if(!root)return null;let box=$('#finditPriceCheckBox');if(box)return box;box=document.createElement('section');box.id='finditPriceCheckBox';box.style.marginTop='18px';const marker=[...root.querySelectorAll('.section-title-row')].find(x=>/search more retailers/i.test(x.textContent||''));if(marker?.parentNode)marker.parentNode.insertBefore(box,marker);else root.appendChild(box);return box}
function pricecheckSearch(q){return`https://www.google.com/search?q=${encodeURIComponent(`site:pricecheck.co.za "${q}"`)}`}
function automotive(i={}){return /\b(car|cars|vehicle|vehicles|automotive|mustang|sedan|coupe|suv|bakkie|pickup|hatchback)\b/i.test([i.category,i.retailCategory,i.object,i.name,i.searchQuery,i.model].filter(Boolean).join(' '))}
function sync(){let i={};try{i=state?.result?.identification||{}}catch{}const existing=$('#finditPriceCheckBox');if(automotive(i)){existing?.remove();return}const box=mount();if(!box)return;const q=[i.brand,i.model,i.searchQuery||i.name||i.object].filter(Boolean).join(' ').trim();if(!q)return;const intel=window.productIntelligence||{};const offers=Array.isArray(intel.offers)?intel.offers:[];const x=offers.find(o=>String(o?.retailer?.name||'').toLowerCase()==='pricecheck'&&o?.verified===true&&Number(o?.matchScore||0)>=.68);const searchUrl=pricecheckSearch(q);
if(!x){box.innerHTML=`<div class="section-title-row"><div><p class="section-kicker">PRICECHECK COMPARISON</p><h3>No exact PriceCheck result verified yet</h3><p>FindIt did not get a strong enough exact PriceCheck match. You can still search PriceCheck for this exact product.</p></div></div><a class="btn secondary" href="${esc(searchUrl)}" target="_blank" rel="noopener noreferrer">Search PriceCheck →</a>`;return}
const price=Number.isFinite(Number(x.price))?money(Number(x.price),x.currency||'ZAR'):'Price not verified';const stock=x.availability==='in_stock'?'Online listing appears available':x.availability==='out_of_stock'?'Online listing appears out of stock':'Online stock not verified';const href=x.product_url||searchUrl;box.innerHTML=`<div class="section-title-row"><div><p class="section-kicker">PRICECHECK COMPARISON</p><h3>Secondary price check</h3><p>PriceCheck is used as a comparison source only. It can help with online price/availability, but it does not prove stock at a physical branch.</p></div></div><article class="offer-card"><div><span class="findit-exact-badge">✓ Strong PriceCheck match</span><h4>${esc(x.product_name||q)}</h4><p>PriceCheck</p><p>${esc(stock)} • Branch stock not verified</p><a href="${esc(href)}" target="_blank" rel="noopener noreferrer">View PriceCheck →</a></div><div class="price">${esc(price)}</div><small class="findit-checked">Comparison source • Physical branch stock not verified</small></article>`}
function init(){document.addEventListener('findit:results-rendered',()=>setTimeout(sync,300));new MutationObserver(()=>{if($('#exactSellerResults'))setTimeout(sync,120)}).observe(document.body,{childList:true,subtree:true});setTimeout(sync,1200);setTimeout(sync,2500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();