(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s);
const qa=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const clean=v=>String(v??'').trim();
const money=(n,c='ZAR')=>{if(n==null||!Number.isFinite(Number(n)))return'Price not verified';try{return new Intl.NumberFormat('en-ZA',{style:'currency',currency:c||'ZAR',maximumFractionDigits:2}).format(Number(n))}catch{return`${c||'ZAR'} ${Number(n).toFixed(2)}`}};
const checked=v=>{try{return new Intl.DateTimeFormat('en-ZA',{hour:'2-digit',minute:'2-digit'}).format(v?new Date(v):new Date())}catch{return'now'}};
const stockLabel=v=>v==='in_stock'?'In stock online':v==='out_of_stock'?'Out of stock online':v==='preorder'?'Pre-order':'Stock not verified';
const getState=()=>{try{return state}catch{return null}};
let lastKey='',busy=false;

function ensureStyle(){if($('#finditCommercePolishStyle'))return;const s=document.createElement('style');s.id='finditCommercePolishStyle';s.textContent=`
#finditLiveCommerce{margin:22px 0 26px;padding:0}
.findit-live-hero{border:1px solid #ffffff15;background:linear-gradient(145deg,#131d33,#0d1629);border-radius:24px;padding:20px;box-shadow:0 18px 55px #00000022}
.findit-live-kicker{font-size:11px;letter-spacing:.18em;font-weight:900;color:#8da2ff;margin:0 0 8px}
.findit-live-title{font-size:24px;line-height:1.15;margin:0;color:#f7f9ff}
.findit-live-sub{margin:8px 0 0;color:#95a5bd;line-height:1.5}
.findit-live-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:16px}
.findit-live-summary article{padding:12px;border:1px solid #ffffff10;background:#ffffff05;border-radius:15px}
.findit-live-summary b{display:block;font-size:18px;color:#fff}.findit-live-summary small{color:#8492a8}
.findit-live-list{display:grid;gap:12px;margin-top:14px}
.findit-live-card{display:grid;grid-template-columns:1fr auto;gap:14px;padding:16px;border:1px solid #ffffff12;background:#101a2e;border-radius:18px;align-items:start}
.findit-live-card h4{margin:0 0 4px;font-size:17px;color:#fff}.findit-live-card p{margin:4px 0;color:#98a8c0;line-height:1.35}
.findit-live-tags{display:flex;flex-wrap:wrap;gap:7px;margin-top:9px}.findit-live-tags span{font-size:11px;font-weight:800;border-radius:999px;padding:6px 9px;border:1px solid #ffffff12;background:#ffffff06;color:#bac7d9}
.findit-live-tags .ok{color:#8ff0ca;border-color:#45d6a54a;background:#45d6a512}.findit-live-tags .warn{color:#f0d48f;border-color:#f0c95a32;background:#f0c95a10}
.findit-live-price{text-align:right;font-size:20px;font-weight:900;color:#fff;white-space:nowrap}.findit-live-price small{display:block;margin-top:5px;color:#8190a8;font-size:10px;font-weight:600}
.findit-live-card a{display:inline-block;margin-top:11px;color:#dce5ff;font-weight:800;text-decoration:none}
.findit-live-empty{padding:18px;border:1px solid #ffffff12;border-radius:18px;background:#ffffff04;color:#97a6bd;line-height:1.5}
#finditPriceCheckBox{display:none!important}
#exactSellerResults>.section-title-row:last-of-type,#exactSellerResults>.free-action-grid{display:none!important}
#nearbyPanel.findit-polished-likely .findit-likely-store:nth-of-type(n+5){display:none!important}
.findit-nearby-note{margin:0 0 12px;padding:12px 14px;border-radius:14px;background:#ffffff05;border:1px solid #ffffff10;color:#94a4bb;font-size:12px;line-height:1.45}
@media(max-width:640px){.findit-live-summary{grid-template-columns:1fr 1fr}.findit-live-summary article:last-child{grid-column:1/-1}.findit-live-card{grid-template-columns:1fr}.findit-live-price{text-align:left}.findit-live-title{font-size:21px}}
`;document.head.appendChild(s)}

function exactQuery(i={}){return [i.brand,i.model,i.searchQuery||i.name||i.object].map(clean).filter(Boolean).join(' ').replace(/\s+/g,' ').trim()}
function mount(){const exact=$('#exactSellerResults'),near=$('#nearbyPanel');let box=$('#finditLiveCommerce');if(box)return box;box=document.createElement('section');box.id='finditLiveCommerce';if(exact?.parentNode)exact.parentNode.insertBefore(box,exact);else if(near?.parentNode)near.parentNode.insertBefore(box,near);return box}
function compactLegacy(){const exact=$('#exactSellerResults');if(!exact)return;qa('.premium-insights',exact).forEach(x=>x.remove());const heads=qa('.section-title-row',exact);heads.forEach(h=>{if(/search more retailers/i.test(h.textContent||''))h.style.display='none'});qa('.free-action-grid',exact).forEach(x=>x.style.display='none');const h=$('h3',exact);if(h&&/no exact seller verified yet/i.test(h.textContent||''))h.textContent='More exact-product checks';const p=qa('p',exact).find(x=>/not proved that a retailer|use the exact-product searches/i.test(x.textContent||''));if(p)p.textContent='FindIt is still checking retailer pages. Only verified product pages are shown as matches.'}
function cleanNearby(){const panel=$('#nearbyPanel'),el=$('#nearbyStores');if(!panel||!el)return;panel.classList.add('findit-polished-likely');qa('a,button',el).forEach(x=>{if(/direction|get directions/i.test(x.textContent||'')){const card=x.closest('article,.store-card');if(card&&/exact item not verified|relevant retailer|possible nearby/i.test(card.textContent||'')){x.removeAttribute('href');x.style.display='none'}}});let note=$('.findit-nearby-note',panel);if(!note){note=document.createElement('div');note.className='findit-nearby-note';const head=$('.nearby-head',panel)||panel.firstElementChild;head?.insertAdjacentElement('afterend',note)}note.textContent='Nearby results below are possible retailers only. FindIt will only show a Directions button when the exact item and that physical branch stock are both verified.';const summary=$('#nearbySummary');if(summary&&/closest relevant retailer/i.test(summary.textContent||''))summary.textContent='Possible nearby retailers — exact item not verified.'}
function renderLoading(q){const box=mount();if(!box)return;box.innerHTML=`<div class="findit-live-hero"><p class="findit-live-kicker">LIVE PRICE + STOCK</p><h3 class="findit-live-title">Checking the exact product now…</h3><p class="findit-live-sub">Searching current retailer product pages for <strong>${esc(q)}</strong>. FindIt will not invent prices or branch stock.</p></div>`}
function render(d,q){const box=mount();if(!box)return;const offers=Array.isArray(d?.offers)?d.offers.filter(x=>x?.verified&&x?.product_url):[];const priced=offers.filter(x=>x.price!=null),inStock=offers.filter(x=>x.availability==='in_stock');const best=priced.slice().sort((a,b)=>Number(a.price)-Number(b.price))[0];box.innerHTML=`<div class="findit-live-hero"><p class="findit-live-kicker">LIVE PRICE + STOCK</p><h3 class="findit-live-title">${offers.length?'Current exact-product results':'No live exact match verified yet'}</h3><p class="findit-live-sub">${offers.length?`Verified against current retailer product pages for <strong>${esc(q)}</strong>. Online availability is separate from physical branch stock.`:`FindIt checked current retailer pages for <strong>${esc(q)}</strong> but could not verify an exact live listing. It will not guess a price or stock level.`}</p><div class="findit-live-summary"><article><b>${offers.length}</b><small>Verified listings</small></article><article><b>${best?esc(money(best.price,best.currency||'ZAR')):'—'}</b><small>Best verified price</small></article><article><b>${inStock.length}</b><small>Online in stock</small></article></div>${offers.length?`<div class="findit-live-list">${offers.map(o=>`<article class="findit-live-card"><div><h4>${esc(o.product_name||q)}</h4><p>${esc(o.retailer||'Retailer')}</p><div class="findit-live-tags"><span class="ok">✓ Exact page verified</span><span class="${o.availability==='in_stock'?'ok':'warn'}">${esc(stockLabel(o.availability))}</span><span>Branch stock not verified</span></div><a href="${esc(o.product_url)}" target="_blank" rel="noopener noreferrer">View retailer →</a></div><div class="findit-live-price">${esc(money(o.price,o.currency||'ZAR'))}<small>Checked ${esc(checked(o.checkedAt||d.checkedAt))}</small></div></article>`).join('')}</div>`:`<div class="findit-live-empty" style="margin-top:14px">Try a photo where the brand and model number are readable. FindIt will keep nearby category stores separate from exact-product results.</div>`}</div>`}
async function sync(){ensureStyle();compactLegacy();cleanNearby();const s=getState(),i=s?.result?.identification||{};const q=exactQuery(i);if(!q||Number(i.confidence||0)<.55)return;const key=q.toLowerCase();if(busy||lastKey===key&&$('#finditLiveCommerce .findit-live-list,#finditLiveCommerce .findit-live-empty'))return;busy=true;lastKey=key;renderLoading(q);try{const r=await fetch('/api/live-commerce',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({searchQuery:i.searchQuery||'',name:i.name||i.object||'',object:i.object||'',brand:i.brand||'',model:i.model||'',category:i.category||'',retailCategory:i.retailCategory||''})});const d=await r.json().catch(()=>({offers:[]}));render(d,q)}catch{render({offers:[]},q)}finally{busy=false;compactLegacy();cleanNearby()}}
function init(){ensureStyle();document.addEventListener('findit:results-rendered',()=>setTimeout(sync,100));new MutationObserver(()=>{compactLegacy();cleanNearby()}).observe(document.body,{childList:true,subtree:true});setTimeout(sync,900);setTimeout(sync,2200)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
