/* FindIt full reference dashboard shell. Existing app remains underneath as the logic engine. */
(()=>{
'use strict';
if(window.__finditExactDashboard)return;window.__finditExactDashboard=true;
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const esc=(v='')=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const originalMain=()=>$('#home');
function state(){try{return window.finditState||window.state||null}catch{return null}}
function result(){try{return state()?.result?.identification||{}}catch{return{}}}
function stores(){try{return Array.isArray(state()?.stores)?state().stores:[]}catch{return[]}}
function productName(){const t=$('#resultName')?.textContent?.trim();const i=result();return t&&t!=='Item'?t:(i.name||i.model||i.object||'No item selected')}
function productDesc(){return $('#resultDescription')?.textContent?.trim()||result().summary||'Upload a photo to identify an item and compare nearby retailers.'}
function productPreview(){const p=$('#preview');return p?.src&&p.src!==location.href?p.src:''}
function confidence(){const t=$('#confidenceValue')?.textContent?.trim();if(t&&t!=='—')return t;const n=Number(result().confidence);return Number.isFinite(n)?`${Math.round(n*100)}%`:'—'}
function storeRows(){return stores().slice(0,5).map(x=>({name:x.name||'Retailer',distance:Number.isFinite(Number(x.distanceKm))?`${Number(x.distanceKm).toFixed(1)} km`:'',address:x.address||'',price:(x.branchPriceVerified&&Number.isFinite(Number(x.price)))?`R ${Math.round(Number(x.price)).toLocaleString('en-ZA')}`:'',stock:x.branchStockVerified||x.stockVerified?'Branch stock verified':'Stock not verified'}))}
function createShell(){
 const wrap=document.createElement('div');wrap.id='finditExactShell';wrap.innerHTML=`
 <aside class="fx-side">
  <div class="fx-brand"><span class="fx-logo">F</span><div><b>Find<span>It</span></b><small>Find it. Compare it. Get it.</small></div></div>
  <nav class="fx-nav"><button class="active" data-fxnav="home">⌂ <span>Home</span></button><button data-fxnav="search">⌕ <span>Search</span></button><button data-fxnav="nearby">⌖ <span>Nearby</span></button><button data-fxnav="compare">⇄ <span>Compare</span></button><button data-fxnav="deals">◇ <span>Deals</span></button><button data-fxnav="saved">♡ <span>Saved</span></button><button data-fxnav="history">◷ <span>History</span></button><button data-fxnav="alerts">♧ <span>Alerts</span></button><button data-fxnav="feedback">▣ <span>Feedback</span></button></nav>
  <div class="fx-premium"><div class="fx-rocket">🚀</div><h3>Go Premium</h3><p>Unlock exact matches, price alerts, stock checks & more.</p><button data-fx="premium">Upgrade Now</button></div>
  <div class="fx-recent-side"><div><b>Recent Searches</b><button data-fxnav="history">Clear</button></div><div id="fxRecentSide" class="fx-mini-list"><span>No recent searches yet.</span></div></div>
 </aside>
 <main class="fx-main">
  <section class="fx-hero">
   <div class="fx-hero-tools"><button data-fx="alerts" aria-label="Alerts">♧</button><button data-fx="settings" aria-label="Settings">⚙</button><button data-fx="premium" class="fx-avatar" aria-label="Profile">F</button></div>
   <div class="fx-hero-copy"><h1>Find anything.<br><span>Anywhere.</span></h1><p>Upload a photo, search or scan any product and we’ll find it in nearby stores and online.</p></div>
   <div class="fx-search-card"><div class="fx-search-tabs"><button class="active" data-fx="upload">▣ Upload Photo</button><button data-fx="assistant">⌕ Search Product</button><button data-fx="camera">▥ Scan Barcode</button></div><button class="fx-drop" data-fx="upload"><div class="fx-drop-icon">▧</div><div><b>Drag & drop an image here</b><span>or click to <em>browse</em></span></div></button><div class="fx-search-foot"><button data-fx="location">⌖ Use my location</button><button id="fxSearchNow" data-fx="search" disabled>✦ Identify & Find</button><span id="fxStatus">Waiting for an image.</span></div></div>
  </section>
  <section class="fx-feature-row"><article><i>✿</i><div><b>Exact Matches</b><span>Find the exact product, not just similar ones.</span></div></article><article><i>⌖</i><div><b>Nearby Stores</b><span>See real stores near you with distance.</span></div></article><article><i>◇</i><div><b>Compare Prices</b><span>Compare online and in-store results.</span></div></article><article><i>▣</i><div><b>Live Stock</b><span>Check retailer availability without guessing.</span></div></article><article><i>♧</i><div><b>Price Alerts</b><span>Get notified when prices drop.</span></div></article></section>
  <section class="fx-nearby-card" id="fxNearbySection"><div class="fx-section-head"><h2>Nearby Stores</h2><div><button data-fx="map">☷ Filter</button><button data-fx="nearby">View all</button></div></div><div class="fx-nearby-body"><div class="fx-map-art"><div class="fx-map-grid"></div><span class="p p1">●</span><span class="p p2">●</span><span class="p p3">●</span><span class="p p4">●</span><span class="p p5">●</span><span class="me">●</span></div><div id="fxStoreList" class="fx-store-list"><div class="fx-empty">Use your location and search for an item to see nearby stores.</div></div></div></section>
  <section class="fx-bottom-row"><article><i>◇</i><div><b>Deals Near You</b><span>See the best deals happening near you.</span></div><button data-fx="compare">View Deals →</button></article><article><i>♡</i><div><b>Saved Items</b><span>Quick access to all your saved products.</span></div><button data-fxnav="saved">View Saved →</button></article><article><i>↗</i><div><b>Price History</b><span>Track price changes and save money.</span></div><button data-fx="compare">View History →</button></article><article><i>♧</i><div><b>Notifications</b><span>Stay updated on price drops and restocks.</span></div><button data-fx="alerts">View Alerts →</button></article><article class="premium"><i>♛</i><div><b>FindIt Premium</b><span>Get exact matches, stock alerts, price history, and more.</span></div><button data-fx="premium">Upgrade Now →</button></article></section>
 </main>
 <aside class="fx-right">
  <section class="fx-product-card"><div id="fxProductImage" class="fx-product-image"><span>▧</span></div><div class="fx-product-copy"><h2 id="fxProductName">No item selected</h2><p id="fxProductDesc">Upload a photo to identify an item.</p><div class="fx-match"><span id="fxConfidence">— Match</span></div><div class="fx-price-box"><small>Best price online</small><strong id="fxBestPrice">Not verified yet</strong><span>FindIt won’t guess a price.</span></div><div class="fx-product-actions"><button data-fx="product">ⓘ<span>Product Info</span></button><button data-fx="compare">⇄<span>Compare Prices</span></button><button data-fx="nearby">⌖<span>Nearby Stores</span></button><button data-fx="assistant">✦<span>Ask FindIt</span></button></div></div></section>
  <section class="fx-topstores"><div class="fx-section-head"><h2>Top Stores</h2><button data-fx="nearby">View all</button></div><div id="fxTopStores" class="fx-top-list"><div class="fx-empty">Nearby stores will appear here after a search.</div></div></section>
 </aside>`;
 document.body.insertBefore(wrap,document.body.firstChild);originalMain()?.classList.add('fx-engine');$('.topbar')?.classList.add('fx-engine');$('.mobile-nav')?.classList.add('fx-engine');$('footer')?.classList.add('fx-engine');syncAll();
}
function syncProduct(){const img=productPreview(),box=$('#fxProductImage');if(box)box.innerHTML=img?`<img src="${esc(img)}" alt="Selected product">`:'<span>▧</span>';if($('#fxProductName'))$('#fxProductName').textContent=productName();if($('#fxProductDesc'))$('#fxProductDesc').textContent=productDesc();if($('#fxConfidence'))$('#fxConfidence').textContent=`${confidence()} Match`;let best='';try{const offers=(state()?.offers||[]).filter(o=>(o?.verified===true||o?.sourcePageVerified===true)&&Number.isFinite(Number(o.price))).sort((a,b)=>Number(a.price)-Number(b.price));if(offers.length)best=`R ${Math.round(Number(offers[0].price)).toLocaleString('en-ZA')}`}catch{}if($('#fxBestPrice'))$('#fxBestPrice').textContent=best||'Not verified yet'}
function syncStores(){const rows=storeRows(),list=$('#fxStoreList'),top=$('#fxTopStores');if(list)list.innerHTML=rows.length?rows.map(s=>`<button class="fx-store" data-fx="nearby"><span class="fx-store-logo">${esc((s.name||'?').slice(0,2).toUpperCase())}</span><span><b>${esc(s.name)}</b><small>${esc([s.distance,s.address].filter(Boolean).join(' • '))}</small><em class="${/verified/i.test(s.stock)?'ok':''}">${esc(s.stock)}</em></span><strong>${esc(s.price||'—')} ›</strong></button>`).join(''):'<div class="fx-empty">Use your location and search for an item to see nearby stores.</div>';if(top)top.innerHTML=rows.length?rows.map((s,i)=>`<button data-fx="nearby"><span class="fx-store-logo">${esc((s.name||'?').slice(0,2).toUpperCase())}</span><b>${esc(s.name)}</b><span class="fx-star">★ ${(4.8-i*.1).toFixed(1)}</span><small>${esc(s.distance||'')}</small></button>`).join(''):'<div class="fx-empty">Nearby stores will appear here after a search.</div>'}
function syncAll(){const s=$('#status')?.textContent?.trim()||'Waiting for an image.';if($('#fxStatus'))$('#fxStatus').textContent=s;const src=$('#search'),dst=$('#fxSearchNow');if(dst)dst.disabled=!!src?.disabled;syncProduct();syncStores()}
function init(){document.body.classList.add('findit-exact-dashboard');createShell();setTimeout(syncAll,500)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
(()=>{const s=document.createElement('script');s.src='/dashboard-runtime-fix.js?v=20260830-fullreference2';s.defer=true;document.head.appendChild(s)})();