import { pipeline } from "https://cdn.jsdelivr.net/npm/@huggingface/transformers@3.8.1";
const photo=document.querySelector("#photo"),preview=document.querySelector("#preview"),prompt=document.querySelector("#prompt"),loc=document.querySelector("#loc"),find=document.querySelector("#find"),status=document.querySelector("#status"),badge=document.querySelector("#badge");
let coords=null,ready=false,places=[],map=null,currentSort="distance",classifier=null;
const categories=[
{label:"pencil case / stationery pouch",icon:"✏️",tags:["stationery","books","department_store"],prompts:["a pencil case","a stationery pouch","school supplies","stationery"]},
{label:"ceiling light / light fixture",icon:"💡",tags:["lighting","hardware","electrical"],prompts:["a ceiling light","a light fixture","a lamp","lighting"]},
{label:"shoes / footwear",icon:"👟",tags:["shoes","sports","clothes"],prompts:["a pair of shoes","footwear","sneakers","sports shoes"]},
{label:"clothing",icon:"👕",tags:["clothes","fashion","department_store"],prompts:["clothing","a shirt","a jacket","fashion clothing"]},
{label:"chair / furniture",icon:"🪑",tags:["furniture","home_furnishing","department_store"],prompts:["a chair","furniture","home furniture"]},
{label:"headphones / audio",icon:"🎧",tags:["electronics","computer"],prompts:["headphones","earbuds","audio equipment"]},
{label:"computer / electronics",icon:"💻",tags:["electronics","computer","mobile_phone"],prompts:["a computer","electronics","a laptop","computer equipment"]},
{label:"phone / mobile device",icon:"📱",tags:["mobile_phone","electronics"],prompts:["a smartphone","a mobile phone","mobile electronics"]},
{label:"tools / hardware",icon:"🔧",tags:["hardware","doityourself"],prompts:["a hand tool","power tools","hardware tools"]},
{label:"kitchen item / cookware",icon:"🍳",tags:["kitchen","houseware","department_store"],prompts:["cookware","a kitchen item","kitchen equipment"]},
{label:"backpack / bag",icon:"🎒",tags:["bags","clothes","department_store"],prompts:["a backpack","a bag","school bag"]},
{label:"sports equipment",icon:"⚽",tags:["sports"],prompts:["sports equipment","sporting goods"]},
{label:"toy / game",icon:"🧸",tags:["toys","games"],prompts:["a toy","a board game","a game"]},
{label:"book",icon:"📚",tags:["books"],prompts:["a book","books"]},
{label:"cosmetics / beauty product",icon:"🧴",tags:["beauty","chemist","department_store"],prompts:["cosmetics","a beauty product","makeup"]},
{label:"home decor",icon:"🏠",tags:["interior_decoration","furniture","department_store"],prompts:["home decor","a decoration","home accessories"]},
{label:"garden item",icon:"🌱",tags:["garden_centre","doityourself","hardware"],prompts:["a gardening item","garden equipment","plants and garden supplies"]},
{label:"car part / automotive item",icon:"🚗",tags:["car_parts","car_repair"],prompts:["a car part","an automotive part","car equipment"]},
{label:"bicycle / cycling item",icon:"🚲",tags:["bicycle","sports"],prompts:["a bicycle","cycling equipment","a bike part"]},
{label:"food / grocery item",icon:"🛒",tags:["supermarket","convenience","bakery"],prompts:["a grocery item","food","a supermarket product"]}];

photo.onchange=()=>{if(!photo.files[0])return;ready=true;preview.src=URL.createObjectURL(photo.files[0]);preview.style.display="block";prompt.style.display="none";status.textContent="Photo ready. Now allow your location.";buttons()};
loc.onclick=()=>{if(!navigator.geolocation){status.textContent="Your browser does not support location.";return}loc.textContent="Getting location…";navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};badge.textContent="📍 Location ready";loc.textContent="✓ Location ready";status.textContent=ready?"Ready — find it nearby.":"Location ready. Add a photo.";buttons()},()=>{loc.textContent="📍 Try again";badge.textContent="⚠️ Location blocked";status.textContent="Location permission was denied. Allow it in browser settings and try again."},{enableHighAccuracy:true,timeout:15000,maximumAge:300000})};
function buttons(){find.disabled=!(ready&&coords)}
async function loadModel(){if(classifier)return classifier;status.textContent="Loading the free AI model for the first time…";classifier=await pipeline("zero-shot-image-classification","Xenova/clip-vit-base-patch32");return classifier}
async function classifyImage(){const model=await loadModel();const labels=categories.flatMap(c=>c.prompts);const out=await model(preview.src,labels,{topk:10});let best=categories[0],bestScore=-1;for(const c of categories){const scores=out.filter(x=>c.prompts.includes(x.label)).map(x=>x.score);const score=scores.length?Math.max(...scores):0;if(score>bestScore){best=c;bestScore=score}}return {...best,score:bestScore}}
async function overpass(tags){const clauses=tags.map(t=>`nwr(around:12000,${coords.lat},${coords.lon})[shop=${t}];`).join("");const q=`[out:json][timeout:25];(${clauses});out center tags;`;for(const u of ["https://overpass-api.de/api/interpreter","https://overpass.kumi.systems/api/interpreter"])try{const r=await fetch(u,{method:"POST",body:q,headers:{"Content-Type":"text/plain"}});if(r.ok)return(await r.json()).elements||[]}catch(e){}throw Error("search failed")}
function dist(a,b,c,d){const R=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function render(){places.sort((a,b)=>currentSort==="name"?a.name.localeCompare(b.name):a.distance-b.distance);document.querySelector("#list").innerHTML=places.length?places.map(p=>`<div class="result"><div class="resulttop"><b>${esc(p.name)}</b><span class="distance">${p.distance.toFixed(1)} km</span></div><div class="meta">${esc(p.type)}${p.address?" • "+esc(p.address):""}<br>Relevant mapped business</div><a class="directions" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lon}">Directions →</a></div>`).join(""):`<div class="result"><b>No relevant nearby businesses found.</b></div>`;if(map)map.remove();map=L.map("map").setView([coords.lat,coords.lon],13);L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap contributors"}).addTo(map);L.marker([coords.lat,coords.lon]).addTo(map).bindPopup("<b>You are here</b>");places.forEach(p=>L.marker([p.lat,p.lon]).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br>${p.distance.toFixed(1)} km`))}
document.querySelector("#sort").onclick=()=>{currentSort=currentSort==="distance"?"name":"distance";document.querySelector("#sort").textContent=currentSort==="distance"?"Closest":"Name";render()};
find.onclick=async()=>{find.disabled=true;document.querySelector("#analysis").classList.remove("hidden");status.textContent="Starting AI image recognition…";try{const item=await classifyImage();document.querySelector("#itemIcon").textContent=item.icon;document.querySelector("#itemName").textContent=item.label;document.querySelector("#itemDesc").textContent="The image model matched your photo to this shopping category.";document.querySelector("#confidence").textContent=`AI confidence: ${(item.score*100).toFixed(0)}%`;document.querySelector("#chips").innerHTML=item.tags.map(t=>`<span class="chip">${t.replaceAll("_"," ")}</span>`).join("");status.textContent="AI match found. Searching relevant nearby businesses…";const els=await overpass(item.tags),seen=new Set();places=els.map(z=>{const lat=z.lat??z.center?.lat,lon=z.lon??z.center?.lon,t=z.tags||{},name=t.name||t.brand;if(!lat||!lon||!name)return null;const k=name+"|"+lat+"|"+lon;if(seen.has(k))return null;seen.add(k);return{name,lat,lon,type:t.shop||"retail",address:[t["addr:housenumber"],t["addr:street"],t["addr:city"]].filter(Boolean).join(" "),distance:dist(coords.lat,coords.lon,lat,lon)}}).filter(Boolean).sort((a,b)=>a.distance-b.distance).slice(0,30);document.querySelector("#results").classList.remove("hidden");render();status.textContent=`Found ${places.length} relevant nearby businesses.`;document.querySelector("#results").scrollIntoView({behavior:"smooth"})}catch(e){console.error(e);status.textContent="The AI model or nearby search could not load. Check your internet connection and try again."}finally{find.disabled=false;buttons()}};
