const photo=document.querySelector('#photo'),preview=document.querySelector('#preview'),prompt=document.querySelector('#prompt'),loc=document.querySelector('#loc'),find=document.querySelector('#find'),status=document.querySelector('#status'),badge=document.querySelector('#badge');let coords=null,ready=false,places=[],map=null;
photo.onchange=()=>{if(!photo.files[0])return;ready=true;preview.src=URL.createObjectURL(photo.files[0]);preview.style.display='block';prompt.style.display='none';status.textContent='Photo ready. Now allow your location.';buttons()};
loc.onclick=()=>{if(!navigator.geolocation){status.textContent='Location is not supported by this browser.';return}loc.textContent='Getting location…';navigator.geolocation.getCurrentPosition(p=>{coords={lat:p.coords.latitude,lon:p.coords.longitude};badge.textContent='📍 Location ready';loc.textContent='✓ Location ready';status.textContent=ready?'Ready — find nearby places.':'Location ready. Add a photo.';buttons()},()=>{loc.textContent='📍 Try again';badge.textContent='⚠️ Location blocked';status.textContent='Please allow location access and try again.'},{enableHighAccuracy:true,timeout:15000,maximumAge:300000})};
function buttons(){find.disabled=!(ready&&coords)}
function classify(){let n=(photo.files[0]?.name||'').toLowerCase();let x={name:'Item from your photo',desc:'Broad retail search. Exact visual recognition is the next AI stage.',icon:'🔎',tags:['shop']};let r=[[/light|lamp|ceiling/,'Lighting','💡',['lighting','hardware','electrical']],[/shoe|sneaker|trainer/,'Shoes / footwear','👟',['shoes','sports']],[/shirt|hoodie|jacket|dress|clothing/,'Clothing','👕',['clothes','fashion']],[/chair|sofa|couch|table|desk|furniture/,'Furniture','🪑',['furniture','home_furnishing']],[/headphone|earbud|speaker|mouse|keyboard|laptop|phone|tablet|console/,'Electronics','🎧',['electronics','computer','mobile_phone']],[/drill|hammer|screwdriver|tool/,'Tools / hardware','🔧',['hardware','doityourself']]];for(const a of r)if(a[0].test(n))return{name:a[1],desc:'Category inferred from the uploaded file name when available.',icon:a[2],tags:a[3]};return x}
async function overpass(tags){let q=tags.map(t=>`nwr(around:12000,${coords.lat},${coords.lon})[shop=${t}];`).join('');q+=`nwr(around:12000,${coords.lat},${coords.lon})[shop];`;let body=`[out:json][timeout:25];(${q});out center tags;`;for(let u of ['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter'])try{let r=await fetch(u,{method:'POST',body});if(r.ok)return(await r.json()).elements||[]}catch(e){}throw Error('search failed')}
function dist(a,b,c,d){let R=6371,p=Math.PI/180,x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function render(){places.sort((a,b)=>a.distance-b.distance);document.querySelector('#list').innerHTML=places.length?places.map(p=>`<div class="result"><div class="resulttop"><b>${esc(p.name)}</b><span class="distance">${p.distance.toFixed(1)} km</span></div><div class="meta">${esc(p.type)}${p.address?' • '+esc(p.address):''}<br>Real mapped business</div><a class="directions" target="_blank" href="https://www.google.com/maps/dir/?api=1&destination=${p.lat},${p.lon}">Directions →</a></div>`).join(''):`<div class="result"><b>No nearby places found.</b><div class="meta">Try again or move to a different area.</div></div>`;if(map)map.remove();map=L.map('map').setView([coords.lat,coords.lon],13);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap contributors'}).addTo(map);L.marker([coords.lat,coords.lon]).addTo(map).bindPopup('<b>You are here</b>');places.forEach(p=>L.marker([p.lat,p.lon]).addTo(map).bindPopup(`<b>${esc(p.name)}</b><br>${p.distance.toFixed(1)} km`))}
find.onclick=async()=>{find.disabled=true;status.textContent='Searching real nearby businesses…';let x=classify();document.querySelector('#analysis').classList.remove('hidden');document.querySelector('#itemIcon').textContent=x.icon;document.querySelector('#itemName').textContent=x.name;document.querySelector('#itemDesc').textContent=x.desc;document.querySelector('#chips').innerHTML=x.tags.map(t=>`<span class="chip">${t}</span>`).join('');try{let e=await overpass(x.tags),seen=new Set();places=e.map(z=>{let lat=z.lat??z.center?.lat,lon=z.lon??z.center?.lon,t=z.tags||{},name=t.name||t.brand;if(!lat||!lon||!name)return null;let k=name+lat+lon;if(seen.has(k))return null;seen.add(k);return{name,lat,lon,type:t.shop||'retail',address:[t['addr:housenumber'],t['addr:street'],t['addr:city']].filter(Boolean).join(' '),distance:dist(coords.lat,coords.lon,lat,lon)}}).filter(Boolean).sort((a,b)=>a.distance-b.distance).slice(0,30);document.querySelector('#results').classList.remove('hidden');render();status.textContent=`Found ${places.length} real nearby mapped businesses.`;document.querySelector('#results').scrollIntoView({behavior:'smooth'})}catch(e){status.textContent='The nearby search service is busy. Please try again.'}finally{find.disabled=false;buttons()}}
