create table if not exists public.findit_premium_profiles (
 id bigint generated by default as identity primary key,
 external_user_id text unique,
 plan text not null default 'free' check (plan in ('free','premium_beta','premium')),
 premium_until timestamptz,
 created_at timestamptz not null default now(),
 updated_at timestamptz not null default now()
);
alter table public.findit_premium_profiles enable row level security;
grant select, insert, update on table public.findit_premium_profiles to service_role;
grant usage, select on sequence public.findit_premium_profiles_id_seq to service_role;
