create table if not exists public.findit_events (
 id bigint generated by default as identity primary key,
 event_type text not null,
 item text, retail_category text, confidence numeric,
 exact_offer_count integer, nearby_store_count integer,
 closest_store_distance_km numeric, radius_km numeric,
 success boolean, country text,
 created_at timestamptz not null default now()
);
alter table public.findit_events enable row level security;
grant select, insert on table public.findit_events to service_role;
grant usage, select on sequence public.findit_events_id_seq to service_role;
