-- FindIt Nearby feedback table
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  rating smallint not null check (rating between 1 and 5),
  topic text not null default 'general',
  message text not null check (char_length(message) between 3 and 1200),
  technical jsonb,
  source text not null default 'FindIt Nearby',
  created_at timestamptz not null default now()
);

-- Keep direct public browser access closed.
alter table public.feedback enable row level security;

-- No public SELECT/INSERT policies are created.
-- FindIt's Vercel server function writes using the server-side service-role key.
-- You view the rows privately inside the Supabase dashboard.
