import test from 'node:test';
import assert from 'node:assert/strict';
import handler, {ident, query, identityMatches, structuredProduct, structuralPrice, verify} from '../lib/product-intelligence-core.js';
import worker from '../cloudflare/worker.js';
const product=(name,extra={})=>ident({name,searchQuery:name,...extra});
const html=(name,price=120,currency='ZAR',extra={})=>`<title>${name}</title><script type="application/ld+json">${JSON.stringify({'@type':'Product',name,...extra,offers:{'@type':'Offer',price,priceCurrency:currency,availability:'https://schema.org/InStock'}})}</script>`;
const categories=[['electronics','Sony WH-1000XM5 black'],['groceries','Kelloggs Corn Flakes 500g'],['clothing','Levis 501 jeans blue'],['shoes','Nike Air Force 1 white'],['beauty','Nivea body lotion 250ml'],['tools','Bosch GSB 13 RE drill'],['toys','LEGO 75301 X Wing'],['furniture','IKEA Billy bookcase white'],['household','Twinsaver toilet paper 18 rolls']];
for(const [category,name] of categories)test(`${category}: exact retailer evidence retains price/currency/online stock`,async t=>{
 t.mock.method(globalThis,'fetch',async()=>new Response(html(name),{headers:{'content-type':'text/html'}}));
 const offer=await verify('https://retailer.example/product/exact-item',product(name));
 assert.ok(offer);assert.equal(offer.price,120);assert.equal(offer.currency,'ZAR');assert.equal(offer.availability,'in_stock');assert.equal(offer.branchStockVerified,false);assert.equal(offer.directionsAvailable,false);
});
test('search retains model, colour and capacity qualifiers',()=>assert.equal(query(product('Sony WH-1000XM5 black',{brand:'Sony',model:'WH-1000XM5'})),'Sony WH-1000XM5 black'));
for(const [wanted,wrong] of [['Sony WH-1000XM5','Sony WH-1000XM50'],['Bosch GSB 13 RE drill','Bosch GSB 130 RE drill'],['Nike Air Force 1 white','Nike Air Force 1 black white'],['Nivea lotion 250ml','Nivea lotion 500ml'],['Twinsaver 18 rolls','Twinsaver 9 rolls'],['Samsung phone 128GB','Samsung phone 256GB']])test(`reject adjacent variant: ${wrong}`,()=>assert.equal(identityMatches(wrong,product(wanted)),false));
test('Product type arrays and later valid offers are supported',()=>{const data={'@type':['Thing','Product'],name:'Sony WH-1000XM5',offers:[{price:null},{price:'199.99',priceCurrency:'USD'}]};const p=structuredProduct(`<script type="application/ld+json">${JSON.stringify(data)}</script>`,product(data.name));assert.equal(p.price,199.99);assert.equal(p.currency,'USD')});
test('barcode must match product-scoped GTIN',()=>{const i=product('Nivea lotion 250ml',{barcode:'1234567890123'});assert.equal(structuredProduct(html(i.name),i),null);assert.equal(structuredProduct(html(i.name,120,'ZAR',{gtin13:i.barcode}),i).price,120);assert.equal(structuredProduct(html(i.name,120,'ZAR',{gtin13:'9876543210987'}),i),null)});
test('no prices from recommendation JSON or catalogue text',()=>{const i=product('Sony WH-1000XM5');assert.equal(structuralPrice('<script>{"recommendations":[{"price":1}]}</script> R 1', '',i,i.name,'https://store.co.za/item'),null)});
test('currency is explicit evidence, never inferred from retailer country',()=>{const i=product('Sony WH-1000XM5');assert.equal(structuralPrice(html(i.name,100,''),'',i,i.name,'https://store.co.za/item').currency,null);assert.equal(structuralPrice(html(i.name,100,'USD'),' ',i,i.name,'https://store.co.za/item').currency,'USD')});
test('product price meta supports reversed attribute order',()=>{const i=product('Sony WH-1000XM5');assert.deepEqual(structuralPrice('<meta content="99.95" property="product:price:amount"><meta content="EUR" property="product:price:currency">','',i,i.name,'https://store.example/item'),{price:99.95,currency:'EUR'})});
test('end-to-end discovery rejects wrong variants and mixed-currency cheapest',async t=>{
 const wanted='Sony WH-1000XM5 black',urls=['https://store.example/product/right','https://other.example/product/right','https://store.example/product/wrong'];
 t.mock.method(globalThis,'fetch',async url=>{const u=String(url);if(u.includes('bing.com/search'))return new Response(`<rss>${urls.map(link=>`<item><title>${wanted}</title><description>${wanted} price</description><link>${link}</link></item>`).join('')}</rss>`);return new Response(html(u.endsWith('wrong')?'Sony WH-1000XM50 black':wanted, u.includes('other')?10:100,u.includes('other')?'USD':'ZAR'),{headers:{'content-type':'text/html'}})});
 let result;const res={setHeader(){},status(){return this},json(x){result=x;return this}};
 await handler({method:'POST',body:{identification:product(wanted)}},res);
 assert.equal(result.offers.length,2);assert.equal(result.bestPrice,null);assert.ok(result.offers.every(o=>!o.product_url.endsWith('wrong')));
});
test('worker validates missing and invalid input without remote calls',async()=>{
 for(const [route,body,status] of [['search',{},400],['nearby',{lat:91,lon:28},400],['nearby',{lat:null,lon:28},400],['assistant',{},400],['feedback',{rating:0,message:''},400]]){
 const r=await worker.fetch(new Request(`https://findit.test/api/${route}`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}),{});assert.equal(r.status,status,route);
 }
 const r=await worker.fetch(new Request('https://findit.test/api/no-such-route'),{});assert.equal(r.status,404);
});
test('typed search is user input, never a claimed visual identification',async()=>{const r=await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({query:'Sony WH-1000XM5 black'})}),{});const d=await r.json();assert.equal(d.identification.name,'Sony WH-1000XM5 black');assert.equal(d.visualVerification,false);assert.equal(d.verified,false);assert.equal(d.identification.confidence,null)});
test('barcode-only lookup resolves product name by matching GTIN',async t=>{const i=product('1234567890123',{barcode:'1234567890123'});t.mock.method(globalThis,'fetch',async()=>new Response(html('Nivea body lotion 250ml',100,'ZAR',{gtin13:i.barcode}),{headers:{'content-type':'text/html'}}));assert.equal((await verify('https://store.example/item',i)).price,100)});
test('explicit shoe size must be present in the product title',()=>{assert.equal(identityMatches('Nike Air Force 1 white size 9',product('Nike Air Force 1 white',{brand:'Nike',model:'Air Force 1',size:'8'})),false)});
test('feedback delivery failure is not a successful save',async()=>{const r=await worker.fetch(new Request('https://findit.test/api/feedback',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({rating:5,message:'test'})}),{});assert.equal(r.status,503);assert.equal((await r.json()).delivered,false)});
test('health reports configuration and version identifies the deployed commit',async()=>{const r=await worker.fetch(new Request('https://findit.test/api/health'),{}),d=await r.json();assert.equal(d.photoIdentification,false);assert.equal(d.feedbackEndpoint,false);assert.equal(d.checksAreConfigurationOnly,true);const v=await worker.fetch(new Request('https://findit.test/api/version'),{BUILD_COMMIT:'test-sha'});assert.equal((await v.json()).commit,'test-sha')});
test('nearby uses category-specific shops and never implies branch inventory',async t=>{
 const cases=[['LEGO toy','toys'],['IKEA Billy bookcase','furniture'],['Levis jeans','clothes'],['Bosch drill','hardware'],['Sony headphones','electronics'],['Kelloggs grocery cereal','supermarket']];
 let queries=[];t.mock.method(globalThis,'fetch',async(url,options)=>{queries.push(String(options.body));return new Response(JSON.stringify({elements:[{id:1,type:'node',lat:-25.748,lon:28.229,tags:{name:'Fixture Store',shop:'toys'}}]}))});
 for(const [name,tag] of cases){queries=[];const r=await worker.fetch(new Request('https://findit.test/api/nearby',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({lat:-25.7479,lon:28.2293,identification:{name}})}),{});const d=await r.json();assert.ok(d.searchedShopTags.includes(tag),name);assert.ok(d.stores[0].distanceKm<1);assert.equal(d.stores[0].branchStockVerified,false);assert.equal(d.stores[0].directionsAvailable,false);}
});
test('photo flow accepts corroborated visible identity and rejects conflicting models',async()=>{
 const post=()=>{const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');return new Request('https://findit.test/api/search',{method:'POST',body:f})};
 const good={name:'Sony WH-1000XM5 headphones',brand:'Sony',model:'WH-1000XM5',object:'headphones',category:'electronics',confidence:.9};
 let calls=0;const env={AI:{run:async()=>{calls++;return {answer:JSON.stringify(good)}}}};
 const d=await (await worker.fetch(post(),env)).json();assert.equal(d.visualVerification,true);assert.equal(d.identification.model,'WH-1000XM5');assert.ok(calls>=2);
 calls=0;env.AI.run=async()=>({answer:JSON.stringify(++calls===1?good:{...good,model:'WH-1000XM4'})});
 const conflict=await (await worker.fetch(post(),env)).json();assert.equal(conflict.identification.name,'Sony headphones');assert.equal(conflict.identification.model,'');assert.equal(conflict.identification.requiresModelConfirmation,true);
});
test('invalid image upload is rejected',async()=>{const f=new FormData();f.set('image',new Blob(['text'],{type:'text/plain'}),'file.txt');const r=await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),{});assert.equal(r.status,400)});
for(const wrong of ['Sony WH-1000XM5 replacement ear pads','Sony WH-1000XM5 protective case','Sony WH-1000XM5 bundle'])test(`reject accessories and bundles: ${wrong}`,()=>assert.equal(structuredProduct(html(wrong),product('Sony WH-1000XM5 headphones',{brand:'Sony',model:'WH-1000XM5',object:'headphones'})),null));
test('worker research fetches the exact page and rejects neighbouring model snippets',async t=>{
 const name='Sony WH-1000XM5',url='https://sony.example/product/xm5';
 t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss><item><title>Sony WH-1000XM50</title><description>Sony headphones with invented battery claims</description><link>https://wrong.example/product</link></item></rss>'):new Response(`<title>${name}</title><meta name="description" content="Sony WH-1000XM5 provides wireless audio and noise cancellation. Wireless playback supports compatible Bluetooth devices.">`));
 const r=await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name,searchQuery:name},offers:[{product_name:name,product_url:url,sourcePageVerified:true,exactProductMatch:true}]})}),{}),d=await r.json();
 assert.equal(d.researched,true);assert.match(d.whatItDoes,/noise cancellation/);assert.equal(d.sources.length,1);assert.equal(d.sources[0].url,url);assert.ok(d.pros.length);assert.doesNotMatch(JSON.stringify(d),/invented battery/);
});
test('worker research does not treat a search snippet as verified product evidence',async t=>{t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss><item><title>Sony WH-1000XM5</title><description>Best headphones with unverified claims.</description><link>https://store.example/product</link></item></rss>'):new Response('blocked',{status:403}));const r=await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name:'Sony WH-1000XM5'}})}),{});assert.equal((await r.json()).researched,false)});
test('verified manufacturer feature headings support headset strengths',async t=>{t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss/>'):new Response('<title>Logitech G PRO Gaming Headset</title><meta name="description" content="Logitech G Pro Gaming Headset provides audio, noise isolation and a condenser microphone."><div class="jumbotron-text"><h2>Passive Noise Isolation</h2></div><div class="jumbotron-text"><h2>Pro-Grade Condenser Microphone</h2></div>'));const r=await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name:'Logitech G Pro Gaming Headset',brand:'Logitech',model:'G Pro',object:'headset',searchQuery:'Logitech G Pro Gaming Headset'}})}),{}),d=await r.json();assert.equal(d.researched,true);assert.equal(d.pros.length,2);assert.equal(d.cons.length,0);assert.match(d.sources[0].url,/logitechg.com/)});
test('native retailer links are independently checked, never accepted as search-page offers',async t=>{
 const name='Korg Pitchclip 2 clip-on tuner';
 t.mock.method(globalThis,'fetch',async u=>{const url=String(u);if(url.includes('bing.com'))return new Response('<rss/>');if(url.includes('post_type=product'))return new Response(`<a href="https://www.marshallmusic.co.za/product/korg-pitchclip-2-clip-on-tuner/">${name}</a><span>R 1 in stock</span>`);return new Response(html(name,799,'ZAR'),{headers:{'content-type':'text/html'}})});
 let result;const res={setHeader(){},status(){return this},json(x){result=x;return this}};await handler({method:'POST',body:{identification:product(name,{brand:'Korg',model:'Pitchclip 2',object:'instrument tuner'})}},res);assert.ok(result.offers.length);assert.ok(result.offers.every(o=>o.price===799&&!o.product_url.includes('post_type=product')));
});

test('uncorroborated Scout identity asks for input without claiming visual verification',async()=>{const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');const good={name:'Nike Air Force 1',brand:'Nike',model:'Air Force 1',object:'shoe',category:'footwear',confidence:.9};const env={AI:{run:async model=>model.includes('scout')?{response:JSON.stringify(good)}:{answer:''}}};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();assert.equal(d.identification,null);assert.equal(d.visualVerification,false);assert.equal(d.requiresUserInput,true);assert.equal(d.code,'PHOTO_IDENTITY_UNCERTAIN');assert.ok(d.visionDiagnostics.some(x=>x.code==='CF_AI_NO_JSON'));assert.equal(d.visionDiagnostics.length,3)});

test('fallback retains corroborated object but clears unsupported brand and model',async()=>{const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');const env={AI:{run:async model=>model.includes('moondream')?{answer:''}:model.includes('llava')?{description:JSON.stringify({name:'Voice Over Microphone',brand:'Voice-Over',model:'Voice-Over Microphone',object:'Microphone',category:'electronics',confidence:.8})}:{response:JSON.stringify({name:'USB microphone',object:'Microphone',category:'electronics',confidence:.8})}}};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();assert.equal(d.identification.brand,'');assert.equal(d.identification.model,'');assert.equal(d.identification.name,'microphone')});
test('photo eyewear category is normalized across provider capitalization',async()=>{const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');const eye={name:'Eye Glasses',object:'Eyewear',category:'Eyewear',retailCategory:'Eyewear',confidence:.8};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),{AI:{run:async()=>({answer:JSON.stringify(eye)})}})).json();assert.equal(d.identification.category,'eyewear');assert.equal(d.identification.retailCategory,'eyewear')});

test('corroborated eyewear synonyms retain generic identification',async()=>{const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');const env={AI:{run:async model=>model.includes('moondream')?{answer:''}:model.includes('llava')?{description:JSON.stringify({name:'Eye Glasses',object:'Eyewear',category:'Eyewear',confidence:.8})}:{response:JSON.stringify({name:'Eyeglasses',object:'Glasses',category:'eyewear',confidence:.8})}}};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();assert.equal(d.identification.retailCategory,'eyewear');assert.equal(d.identification.brand,'');assert.equal(d.identification.model,'')});

test('nested provider response objects preserve structured visual identity',async()=>{const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');const identity={name:'Nike Air Force 1 shoe',brand:'Nike',model:'Air Force 1',object:'shoe',category:'footwear',confidence:.9};const env={AI:{run:async model=>model.includes('moondream')?{result:{answer:{text:JSON.stringify(identity)}}}:{answer:JSON.stringify(identity)}}};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();assert.equal(d.identification.model,'Air Force 1');assert.equal(d.identification.retailCategory,'footwear');assert.equal(d.visualVerification,true)});

test('primary brand and model need a witness when the second vision provider fails',async()=>{
 const primary={name:'Marc Anthony',brand:'Strictly Curls',model:'Triple Bend Conditioner',object:'conditioner',category:'beauty',confidence:.99};
 const witness={name:'Marc Anthony conditioner',brand:'Marc Anthony',model:'Strictly Curls',object:'conditioner',category:'beauty',confidence:.9};
 const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');
 const env={AI:{run:async model=>model.includes('moondream')?{answer:JSON.stringify(primary)}:model.includes('llava')?{answer:''}:{response:JSON.stringify(witness)}}};
 const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();
 assert.equal(d.identification.name,'conditioner');assert.equal(d.identification.brand,'');assert.equal(d.identification.model,'');assert.equal(d.identification.requiresModelConfirmation,true);
});

test('daily AI allowance exhaustion stops further inference and explains the actual limit',async()=>{
 let calls=0;const env={AI:{run:async()=>{calls++;throw Error('4006: you have used up your daily free allocation of 10,000 neurons')}}};
 const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');
 const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();
 assert.equal(calls,1);assert.equal(d.code,'PHOTO_DAILY_LIMIT_REACHED');assert.equal(d.retryable,false);
 assert.equal(d.identification,null);assert.equal(d.visualVerification,false);assert.match(d.message,/daily service limit.*product name or barcode/);
});

test('discovery accepts reordered exact product titles without requiring quoted search phrases',async t=>{
 const wanted='Nivea body lotion 250ml',requests=[];
 t.mock.method(globalThis,'fetch',async url=>{const u=String(url);if(u.includes('bing.com/search')){const q=new URL(u).searchParams.get('q');requests.push(q);return new Response(q.includes('"')?'<rss/>':'<rss><item><title>Nivea 250ml body lotion</title><description>Nivea body lotion 250ml</description><link>https://store.example/product/nivea-250ml</link></item></rss>')}return new Response(html('Nivea 250ml body lotion',49.99,'ZAR'),{headers:{'content-type':'text/html'}})});
 let result;const res={setHeader(){},status(){return this},json(x){result=x;return this}};await handler({method:'POST',body:{identification:product(wanted)}},res);
 assert.ok(requests.some(q=>q.startsWith('site:clicks.co.za')));assert.ok(requests.includes(wanted+' product price'));assert.ok(result.offers.some(o=>o.product_url==='https://store.example/product/nivea-250ml'&&o.price===49.99));
});

test('research does not present a truncated meta description tail as a product strength',async t=>{
 const name='Nivea Rich Nourishing Body Lotion 250ml',url='https://store.example/nivea-rich-nourishing-body-lotion-250ml';
 t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss/>'):new Response('<title>'+name+'</title><meta name="description" content="Nivea Rich Nourishing Body Lotion 250ml moisturises very dry skin. It provides hydration for up to 72 hours, helping t">'));
 const r=await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name},offers:[{product_name:name,product_url:url,sourcePageVerified:true,exactProductMatch:true}]})}),{}),d=await r.json();
 assert.equal(d.researched,true);assert.match(d.whatItDoes,/moisturises/);assert.deepEqual(d.pros,[]);assert.doesNotMatch(JSON.stringify(d),/helping t/);
});

test('corroborated photo variant is preserved rather than replaced by a product-specific heuristic',async()=>{
 const identity={name:'Marc Anthony Strictly Curls 3X Moisture Conditioner',brand:'Marc Anthony',model:'Strictly Curls 3X Moisture',object:'conditioner',category:'beauty',confidence:.9};
 const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');
 const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),{AI:{run:async()=>({answer:JSON.stringify(identity)})}})).json();
 assert.equal(d.identification.model,identity.model);assert.equal(d.identification.name,identity.name);assert.equal(d.visualVerification,true);
});
test('conflicting photo brand/model claims stay unverified and provide diagnostic evidence',async()=>{
 let calls=0;const identity={name:'Visible Conditioner',brand:'Brand One',model:'Variant One',object:'conditioner',category:'beauty',confidence:.9};
 const f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');
 const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),{AI:{run:async()=>({answer:JSON.stringify(++calls===1?identity:{...identity,brand:'Brand Two'})})}})).json();
 assert.equal(d.identification.name,'conditioner');assert.equal(d.identification.brand,'');assert.equal(d.identification.model,'');assert.equal(d.identification.requiresModelConfirmation,true);
 assert.equal(d.visionDiagnostics[0].identityClaim.brand,'Brand One');assert.equal(d.visionDiagnostics[1].identityClaim.brand,'Brand Two');
});
test('verified toy retailer retains its actual name and unknown sellers retain their hostname',async t=>{
 const name='LEGO Classic Creative Dinosaurs 11041';
 t.mock.method(globalThis,'fetch',async()=>new Response('<title>'+name+'</title><script type="application/ld+json">'+JSON.stringify({'@type':'Product',name,offers:{price:649.9,priceCurrency:'ZAR',availability:'https://schema.org/InStock'}})+'</script>',{headers:{'content-type':'text/html'}}));
 const {verify,ident}=await import('../lib/product-intelligence-core.js');
 assert.equal((await verify('https://www.toysrus.co.za/lego-classic-creative-dinosaurs-11041',ident({name}))).retailer.name,'Toys R Us');
 assert.equal((await verify('https://independent-shop.co.za/lego-classic-creative-dinosaurs-11041',ident({name}))).retailer.name,'independent-shop.co.za');
});

test('research reads complete product-scoped descriptions and excludes recommendations',async t=>{
 const name='LEGO Classic Creative Dinosaurs 11041',url='https://store.example/lego-classic-creative-dinosaurs-11041';
 const raw='<title>'+name+'</title><meta name="description" content="LEGO CLASSICS 11041 CREATIVE DINOSAURS"><div class="product attribute description"><div><h3>Short Description:</h3><p>Get ready for exciting dinosaur adventures! Build your own dinosaur models including a T. rex with this LEGO brick set.</p></div><div><h3>Features and Benefits:</h3><ul><li>A step-by-step guide is included for creative construction</li><li>Other LEGO sets are sold separately</li></ul></div></div><div class="recommendations">Invented flying dinosaurs and unlimited battery life.</div>';
 t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss/>'):new Response(raw));
 const d=await(await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name},offers:[{product_name:name,product_url:url,sourcePageVerified:true,exactProductMatch:true}]})}),{})).json();
 assert.match(d.whatItDoes,/Build your own dinosaur models including a T\. rex with this LEGO brick set/);assert.match(d.pros.join(' '),/step-by-step guide/);assert.match(d.cons.join(' '),/sold separately/);assert.doesNotMatch(d.pros.join(' '),/sold separately/);assert.doesNotMatch(JSON.stringify(d),/Invented flying|unlimited battery|Short Description/);
});

 test('research rejects conflicting colour in scoped retailer copy and uses matching structured facts',async t=>{
 const name='Sony WH-1000XM5 Wireless Headphones Black',url='https://store.example/sony-wh-1000xm5-black';
 const page='<title>'+name+'</title><script type="application/ld+json">'+JSON.stringify({'@type':'Product',name,description:'Sony WH-1000XM5 provides wireless listening with active noise cancellation.'})+'</script><div class="product attribute description">Sony WH-1000XM5 Wireless Headphones Silver provide wireless audio, active noise cancellation and a comfortable listening experience for everyday use.</div>';
 t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss/>'):new Response(page));
 const r=await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name,searchQuery:name},offers:[{product_name:name,product_url:url,sourcePageVerified:true,exactProductMatch:true}]})}),{}),d=await r.json();
 assert.equal(d.researched,true);assert.match(d.whatItDoes,/noise cancellation/);assert.doesNotMatch(JSON.stringify(d),/Silver/);
 });
test('uncertain model cannot publish a different models price or researched specifications',async t=>{let calls=0;t.mock.method(globalThis,'fetch',async()=>{calls++;throw Error('must not discover a guessed model')});const identification={name:'Beats headphones',requiresModelConfirmation:true};let result;await handler({method:'POST',body:{identification}},{setHeader(){},status(){return this},json(v){result=v}});assert.deepEqual(result.offers,[]);assert.equal(result.exactMatchVerified,false);const r=await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification})}),{});assert.equal((await r.json()).researched,false);assert.equal(calls,0)});
test('product information exposes source-scoped structured specifications',async t=>{const name='Sony WH-1000XM5',url='https://sony.example/product/xm5';t.mock.method(globalThis,'fetch',async u=>String(u).includes('bing.com')?new Response('<rss/>'):new Response('<title>'+name+'</title><script type="application/ld+json">'+JSON.stringify([{'@type':'Product',name,description:'Sony WH-1000XM5 provides wireless listening and noise cancellation.',additionalProperty:[{'@type':'PropertyValue',name:'Battery life',value:30,unitText:'hours'}]},{'@type':'Product',name:'Sony WH-1000XM4',additionalProperty:[{name:'Wrong specification',value:'must not show'}]}])+'</script>'));const d=await(await worker.fetch(new Request('https://findit.test/api/product-insights',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({identification:{name,searchQuery:name},offers:[{product_name:name,product_url:url,sourcePageVerified:true,exactProductMatch:true}]})}),{})).json();assert.deepEqual(d.specifications,[{name:'Battery life',value:'30 hours',sourceUrl:url}]);assert.doesNotMatch(JSON.stringify(d),/Wrong specification/)});
test('Cloudflare text-completion envelope is parsed as transport metadata, not a product',async()=>{const i={name:'Beats headphones',brand:'Beats',object:'headphones',category:'electronics',model:''},f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');const env={AI:{run:async model=>model.includes('scout')?{object:'text_completion',model:'@cf/meta/llama-4-scout-17b-16e-instruct',choices:[{text:JSON.stringify(i)}]}:{answer:JSON.stringify(i)}}};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();assert.equal(d.identification.name,'Beats headphones');assert.equal(d.visionDiagnostics[2].identityClaim.object,'headphones');assert.doesNotMatch(JSON.stringify(d.identification),/text_completion|@cf\//)});
test('flat legacy commerce input also preserves model uncertainty',async t=>{t.mock.method(globalThis,'fetch',()=>{throw Error('must not fetch')});let result;await handler({method:'POST',body:{name:'Beats headphones',requiresModelConfirmation:true}},{setHeader(){},status(){return this},json(v){result=v}});assert.deepEqual(result.offers,[]);const {verify,ident}=await import('../lib/product-intelligence-core.js');assert.equal(await verify('https://store.example/beats-solo3',ident({name:'Beats headphones',requiresModelConfirmation:true})),null)});
test('Scout receives the image in a multimodal message instead of a text-only prompt',async()=>{const identity={name:'Beats headphones',brand:'Beats',model:'',object:'headphones'},f=new FormData();f.set('image',new Blob(['fixture'],{type:'image/jpeg'}),'fixture.jpg');let seen=false;const env={AI:{run:async(model,input)=>{if(model.includes('scout')){seen=true;assert.equal(input.messages[0].content[1].type,'image_url');assert.match(input.messages[0].content[1].image_url.url,/^data:image\/jpeg;base64,/);return {choices:[{message:{content:JSON.stringify(identity)}}],object:'chat.completion'};}return{answer:JSON.stringify(identity)}}};const d=await(await worker.fetch(new Request('https://findit.test/api/search',{method:'POST',body:f}),env)).json();assert.equal(seen,true);assert.equal(d.identification.brand,'Beats')});
