import { chromium } from 'playwright';
const URL=process.env.FINDIT_URL||'https://findit-nearby.vercel.app/';
const browser=await chromium.launch({headless:true});let failures=[];const check=async(name,fn)=>{try{await fn();console.log('[PASS]',name)}catch(e){failures.push(`${name}: ${e.message}`);console.error('[FAIL]',name,e.message)}};
const ctx=await browser.newContext({viewport:{width:1440,height:900},geolocation:{latitude:-25.7479,longitude:28.2293},permissions:['geolocation','clipboard-read','clipboard-write']});const p=await ctx.newPage();await p.addInitScript(()=>{Object.defineProperty(navigator,'share',{configurable:true,value:async d=>{window.__finditShared=d}})});await p.goto(URL,{waitUntil:'domcontentloaded',timeout:35000});await p.waitForTimeout(1800);
await check('production loads',async()=>{if(!await p.locator('#finder').count())throw Error('finder missing')});
await check('feedback copy',async()=>{await p.locator('#feedbackMessage').fill('release smoke');await p.locator('#copyFeedback').click();await p.waitForTimeout(150);const t=await p.locator('#feedbackStatus').innerText();if(!/copied/i.test(t))throw Error(t||'not copied')});
await check('share deep-link',async()=>{await p.evaluate(()=>{state.result={identification:{name:'Nike Air Force 1 Test',object:'shoe',brand:'Nike',model:'Air Force 1',category:'footwear',retailCategory:'footwear',searchQuery:'Nike Air Force 1',summary:'QA shared result',confidence:.95,likelyStoreTypes:['shoe store']}};renderFreeActions(state.result.identification)});await p.locator('#shareFind').click();await p.waitForTimeout(150);const d=await p.evaluate(()=>window.__finditShared);if(!d?.url||!d.url.includes('?find='))throw Error(JSON.stringify(d));const q=await ctx.newPage();await q.goto(d.url,{waitUntil:'domcontentloaded',timeout:35000});await q.waitForTimeout(1800);if(!await q.locator('.findit-shared-banner').count())throw Error('shared banner missing');const title=await q.locator('#resultTitle').innerText();if(!/Nike Air Force 1 Test/i.test(title))throw Error(`wrong restored title: ${title}`);await q.close()});await ctx.close();
const mob=await browser.newContext({viewport:{width:390,height:844}});const m=await mob.newPage();await m.goto(URL,{waitUntil:'domcontentloaded',timeout:35000});await m.waitForTimeout(1800);await m.evaluate(()=>{localStorage.setItem('findit_premium_beta','1');localStorage.setItem('findit_v10_watchlist',JSON.stringify([{name:'Marc Anthony Strictly Curls Triple Blend Conditioner',query:'Marc Anthony Strictly Curls Triple Blend Conditioner',brand:'Marc Anthony',model:'Strictly Curls Triple Blend Conditioner',currency:'ZAR',lastPrice:null,lastStock:null,targetPrice:250,retailer:'',nearestStore:null}]))});await m.reload({waitUntil:'domcontentloaded'});await m.waitForTimeout(1800);
await check('mobile Watchlist layout',async()=>{const b=m.locator('[data-v10="watchlist"]').first();await b.click();await m.waitForTimeout(250);const row=m.locator('.findit-watch-modal .v10-list>.v10-row').first();if(!await row.isVisible())throw Error('watch row missing');const info=await row.evaluate(e=>{const r=e.getBoundingClientRect(),title=e.querySelector('b')?.getBoundingClientRect(),acts=e.querySelector('.findit-row-actions')?.getBoundingClientRect();return{rowW:r.width,titleW:title?.width||0,actionsW:acts?.width||0}});if(info.titleW<info.rowW*.65||info.actionsW<info.rowW*.65)throw Error(JSON.stringify(info))});await mob.close();await browser.close();if(failures.length){console.error('\nFAILURES\n'+failures.join('\n'));process.exit(1)}console.log('RELEASE_SMOKE_PASS');
// Triggered after the final production fixes so the PR workflow audits the live site again.
