const text = v => String(v ?? '').replace(/\s+/g,' ').trim();
export function answerFromEvidence(question, context={}, research={}) {
 const q=text(question).toLowerCase(),i=context.identification||{},name=text(i.name||i.object)||'this product',parts=[];
 const offers=(Array.isArray(context.offers)?context.offers:[]).filter(o=>o?.sourcePageVerified===true&&o?.exactProductMatch===true);
 const sourceLines=[];
 const addSource=url=>{try{const u=new URL(url);if(u.protocol==='https:'&&!sourceLines.includes(u.href))sourceLines.push(u.href);}catch{}};
 const uncertain=i.requiresModelConfirmation===true;
 if(/price|cheapest|cost|compare|buy|where/.test(q)) {
  const priced=uncertain?[]:offers.filter(o=>o.price!=null&&Number.isFinite(Number(o.price))&&Number(o.price)>0&&/^[A-Z]{3}$/.test(o.currency||''));
  const currencies=[...new Set(priced.map(o=>o.currency))];
  if(priced.length){parts.push('Verified online prices in the current result:');for(const currency of currencies){const group=priced.filter(o=>o.currency===currency).sort((a,b)=>Number(a.price)-Number(b.price));for(const o of group.slice(0,5)){parts.push(`${text(o.retailer?.name||o.retailer)||'Retailer'}: ${new Intl.NumberFormat('en-ZA',{style:'currency',currency}).format(Number(o.price))}${o.availability==='in_stock'?' — in stock online':o.availability==='out_of_stock'?' — out of stock online':''}.`);addSource(o.product_url||o.url);}if(group.length>1)parts.push(`Lowest listed ${currency} price: ${text(group[0].retailer?.name||group[0].retailer)}. Delivery charges may differ.`);}if(currencies.length>1)parts.push('Different currencies are listed separately; they have not been compared as equal amounts.');}
  else parts.push(`No exact, verified price is available in the current result for ${name}.`);
 }
 if(/stock|available|availability/.test(q)){const known=uncertain?[]:offers.filter(o=>['in_stock','out_of_stock','preorder','backorder'].includes(o.availability));for(const o of known){parts.push(`${text(o.retailer?.name||o.retailer)}: ${{in_stock:'in stock online',out_of_stock:'out of stock online',preorder:'available for preorder online',backorder:'backorder online'}[o.availability]}.`);addSource(o.product_url||o.url);}if(!known.length)parts.push('No exact online availability has been verified in the current result.');parts.push('Online availability does not confirm stock at a nearby branch.');}
 if(/nearby|nearest|closest|store|where|distance|hours|phone|address|directions/.test(q)){const stores=(Array.isArray(context.stores)?context.stores:[]).slice().sort((a,b)=>(Number(a.distanceKm)||Infinity)-(Number(b.distanceKm)||Infinity));if(stores.length){parts.push('Nearby retailer results (exact item and branch stock may be unconfirmed):');for(const s of stores.slice(0,5)){const detail=[text(s.name)];if(s.distanceKm!=null&&Number.isFinite(Number(s.distanceKm)))detail.push(Number(s.distanceKm).toFixed(1)+' km');if(s.address)detail.push(text(s.address));if(/hours|open|close/.test(q)&&s.openingHours)detail.push('Published hours: '+text(s.openingHours));if(/phone|call/.test(q)&&s.phone)detail.push('Phone: '+text(s.phone));parts.push(detail.join(' — '));}parts.push('Open Check Store for the branch details and their verification status.');}else parts.push('No nearby branches are loaded. Allow location and run a search to calculate nearby distances.');}
 if(/what|does|how|product|information|detail|feature|spec|good|better|benefit|pros|cons|drawback|use|purpose|worth|recommend/.test(q)||!parts.length){
  if(uncertain)parts.push(`${name} is recognised, but its exact model needs confirmation before I can give model-specific facts.`);
  else if(research.researched){parts.push(name+':',text(research.whatItDoes));if(research.pros?.length)parts.push('Published strengths:',...research.pros.slice(0,4).map(x=>'• '+text(x)));if(research.cons?.length)parts.push('Published considerations:',...research.cons.slice(0,3).map(x=>'• '+text(x)));else parts.push('No product-specific downsides were verified; that does not mean there are none.');if(research.specifications?.length)parts.push('Published specifications:',...research.specifications.slice(0,8).map(x=>text(x.name)+': '+text(x.value)));for(const s of research.sources||[])addSource(s.url);}
  else parts.push(`I could not verify published product-specific information for ${name}. Add the exact model, size or barcode if the current identity is incomplete.`);
 }
 if(sourceLines.length)parts.push('Sources:',...sourceLines.slice(0,6));
 return {answer:parts.filter(Boolean).join('\n\n'),sources:sourceLines.map(url=>({url})),modelUsed:'findit-sourced-evidence'};
}
