const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const safeSearch=(domain,q)=>`https://www.google.com/search?q=${encodeURIComponent(`site:${domain} "${clean(q)}"`)}`;

export const RETAILERS=[
 {name:'Takealot',domain:'takealot.com',cats:['all'],priority:1,search:q=>safeSearch('takealot.com',q),branchMode:'online_only',priceMode:'online',branchNote:'Online marketplace listing; no physical retail branch should be claimed.',priceNote:'Use the current published Takealot listing price.'},
 {name:'Makro',domain:'makro.co.za',cats:['all'],priority:1,search:q=>safeSearch('makro.co.za',q),branchMode:'pickup_location',priceMode:'online_location',branchNote:'A Makro branch is verified only when pickup/collection data confirms the exact item at that selected store.',priceNote:'Makro website price is online pricing and can differ from a physical-store price; only store-specific data may be labelled branch price.'},
 {name:'PriceCheck',domain:'pricecheck.co.za',cats:['all'],priority:4,search:q=>safeSearch('pricecheck.co.za',q),branchMode:'online_only',priceMode:'online',branchNote:'Comparison listing only; never use it as physical branch-stock proof.',priceNote:'Price is a comparison-source price and should link to the underlying retailer where possible.'},
 {name:'AutoTrader',domain:'autotrader.co.za',cats:['automotive'],priority:1,search:q=>safeSearch('autotrader.co.za',q),branchMode:'listing_location',priceMode:'listing',branchNote:'Vehicle listing location is not the same as verified dealer stock unless the listing identifies the dealer and vehicle.',priceNote:'Use the current vehicle listing price only.'},
 {name:'Cars.co.za',domain:'cars.co.za',cats:['automotive'],priority:1,search:q=>safeSearch('cars.co.za',q),branchMode:'listing_location',priceMode:'listing',branchNote:'Vehicle listing location is not treated as verified dealer inventory unless the specific listing proves it.',priceNote:'Use the current listing price only.'},
 {name:'WeBuyCars',domain:'webuycars.co.za',cats:['automotive'],priority:1,search:q=>safeSearch('webuycars.co.za',q),branchMode:'vehicle_location',priceMode:'listing',branchNote:'Directions may be shown only when a specific listed vehicle is tied to a physical branch.',priceNote:'Use the current listed vehicle price.'},
 {name:'Ford South Africa',domain:'ford.co.za',cats:['automotive'],brand:'ford',priority:1,search:q=>safeSearch('ford.co.za',q),branchMode:'dealer_network',priceMode:'model_or_quote',branchNote:'Dealer directions are not exact vehicle stock proof unless dealer inventory confirms the specific vehicle.',priceNote:'Model pricing or quotations are not automatically exact dealer-stock prices.'},
 {name:'Mercedes-Benz South Africa',domain:'mercedes-benz.co.za',cats:['automotive'],brand:'mercedes benz',priority:1,search:q=>safeSearch('mercedes-benz.co.za',q),branchMode:'dealer_network',priceMode:'model_or_quote',branchNote:'Dealer directions are not exact vehicle stock proof unless dealer inventory confirms the specific vehicle.',priceNote:'Model pricing or quotations are not automatically exact dealer-stock prices.'},
 {name:'Checkers',domain:'checkers.co.za',cats:['grocery','home','kitchenware'],priority:1,search:q=>safeSearch('checkers.co.za',q),branchMode:'location_required',priceMode:'local',branchNote:'Grocery and home stock must be tied to a selected delivery/store area before a branch is treated as verified.',priceNote:'Promotions and availability can be regional/store dependent; do not assume a national branch price.'},
 {name:'Pick n Pay',domain:'pnp.co.za',cats:['grocery','home','kitchenware'],priority:1,search:q=>safeSearch('pnp.co.za',q),branchMode:'location_required',priceMode:'local',branchNote:'Pick n Pay requires location/delivery details to expose local availability.',priceNote:'Only location-specific pricing may be treated as local price.'},
 {name:'Shoprite',domain:'shoprite.co.za',cats:['grocery','home'],priority:2,search:q=>safeSearch('shoprite.co.za',q),branchMode:'location_required',priceMode:'local',branchNote:'Branch availability must come from location/store-specific Shoprite data.',priceNote:'Regional/store offers must not be treated as one national price.'},
 {name:'Woolworths',domain:'woolworths.co.za',cats:['grocery','home','kitchenware','clothing','beauty'],priority:2,search:q=>safeSearch('woolworths.co.za',q),branchMode:'in_store_check',priceMode:'local_or_online',branchNote:'Use Woolworths in-store availability or selected-store Click & Collect data before verifying a physical branch.',priceNote:'Keep online price separate from any store-specific deal or price.'},
 {name:'Nike',domain:'nike.com',cats:['footwear','clothing','sports'],brand:'nike',priority:1,search:q=>safeSearch('nike.com/za',q),branchMode:'online_only',priceMode:'online',branchNote:'Official Nike South Africa online listing; branch inventory is not assumed.',priceNote:'Use the current official online price only unless store-specific data is supplied.'},
 {name:'adidas',domain:'adidas.co.za',cats:['footwear','clothing','sports'],brand:'adidas',priority:1,search:q=>safeSearch('adidas.co.za',q),branchMode:'online_only',priceMode:'online',branchNote:'Official adidas South Africa online listing; branch inventory is not assumed.',priceNote:'Use the current official online price only unless store-specific data is supplied.'},
 {name:'Sportscene',domain:'sportscene.co.za',cats:['footwear','clothing','sports'],priority:1,search:q=>safeSearch('sportscene.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'A Sportscene branch is shown only when store-specific inventory is returned by a connected source.',priceNote:'Online price is not automatically a verified branch price.'},
 {name:'Totalsports',domain:'totalsports.co.za',cats:['footwear','clothing','sports'],priority:1,search:q=>safeSearch('totalsports.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'A Totalsports branch is shown only when store-specific inventory is returned by a connected source.',priceNote:'Online price is not automatically a verified branch price.'},
 {name:'Bash',domain:'bash.com',cats:['footwear','clothing','sports'],priority:2,search:q=>safeSearch('bash.com',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Collection/location data must confirm the exact item before a physical destination is shown.',priceNote:'Keep online price separate from branch-specific pricing.'},
 {name:'Superbalist',domain:'superbalist.com',cats:['footwear','clothing'],priority:3,search:q=>safeSearch('superbalist.com',q),branchMode:'online_only',priceMode:'online',branchNote:'Online retailer; no physical retail branch should be claimed.',priceNote:'Use current online listing price.'},
 {name:'Sportsmans Warehouse',domain:'sportsmanswarehouse.co.za',cats:['sports','outdoor','footwear'],priority:3,search:q=>safeSearch('sportsmanswarehouse.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Physical store stock requires store-specific inventory evidence.',priceNote:'Online price is separate until a branch-specific price is supplied.'},
 {name:'Incredible Connection',domain:'incredible.co.za',cats:['electronics'],priority:1,search:q=>safeSearch('incredible.co.za',q),branchMode:'store_stock_lookup',priceMode:'local_or_online',branchNote:'Incredible Connection exposes store stock/collection selection; a store is verified only when that lookup says the exact item is available there.',priceNote:'Use the published product price; label a branch price only when the store-specific source supplies it.'},
 {name:'Game',domain:'game.co.za',cats:['electronics','appliances','home','kitchenware','electrical','toys','sports','hardware'],priority:1,search:q=>safeSearch('game.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Do not convert Game online stock into branch stock without store-specific inventory evidence.',priceNote:'Online price/stock stays separate from branch price/stock.'},
 {name:'HiFi Corp',domain:'hificorp.co.za',cats:['electronics','appliances'],priority:2,search:q=>safeSearch('hificorp.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Physical store availability requires store-specific inventory evidence.',priceNote:'Online price is not automatically a branch price.'},
 {name:'Builders',domain:'builders.co.za',cats:['hardware','home','garden','electrical'],priority:1,search:q=>safeSearch('builders.co.za',q),branchMode:'click_collect_location',priceMode:'local_or_online',branchNote:'Builders supports Click & Collect; a branch should be verified only when the exact item is available for collection at that selected store.',priceNote:'Keep online price separate unless a store-specific price is supplied.'},
 {name:'Leroy Merlin',domain:'leroymerlin.co.za',cats:['hardware','home','garden','electrical'],priority:2,search:q=>safeSearch('leroymerlin.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Physical store stock requires store/location-specific confirmation.',priceNote:'Online price is not automatically a branch price.'},
 {name:'Clicks',domain:'clicks.co.za',cats:['beauty','health'],priority:2,search:q=>safeSearch('clicks.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Physical store availability requires store-specific confirmation.',priceNote:'Online price is not automatically a branch price.'},
 {name:'Dis-Chem',domain:'dischem.co.za',cats:['beauty','health'],priority:2,search:q=>safeSearch('dischem.co.za',q),branchMode:'location_required',priceMode:'local_or_online',branchNote:'Physical store availability requires store-specific confirmation.',priceNote:'Online price is not automatically a branch price.'}
];

export function hostMatches(url,domain){try{const h=new URL(url).hostname.replace(/^www\./,'');return h===domain||h.endsWith('.'+domain)}catch{return false}}
export function familyOf(v){const x=norm(v);if(/\b(car|cars|vehicle|vehicles|automotive|mustang|sedan|coupe|suv|bakkie|pickup|hatchback|motor vehicle|mercedes|benz|glc|gle|gla)\b/.test(x))return'automotive';if(/plug adapter|plug adaptor|multi plug|multiplug|power strip|extension lead|extension cord|electrical accessory|electrical adaptor|socket adaptor/.test(x))return'electrical';if(/appliance|fridge|washing machine|microwave|air fryer|dishwasher|toaster|kettle|vacuum/.test(x))return'appliances';if(/grocery|household|toilet paper|food|drink|supermarket|cleaning|detergent|snack|bread|milk|cereal/.test(x))return'grocery';if(/shoe|sneaker|footwear|boot|trainer|samba/.test(x))return'footwear';if(/clothing|clothes|fashion|shirt|dress|jacket|jeans|pants/.test(x))return'clothing';if(/sport|fitness|gym|soccer|rugby|cricket|tennis/.test(x))return'sports';if(/hardware|tool|drill|hammer|wrench|spanner|adjustable wrench|screwdriver|pliers|saw|paint|plumbing|diy/.test(x))return'hardware';if(/electronic|microphone|audio|computer|phone|camera|speaker|headphone|headset|gaming|laptop|monitor|keyboard|mouse|router|charger|bluetooth/.test(x))return'electronics';if(/salt shaker|pepper shaker|salt and pepper|pepper mill|salt mill|kitchenware|cookware|utensil|tableware|cutlery/.test(x))return'kitchenware';if(/garden|plant|flower/.test(x))return'garden';if(/beauty|perfume|cosmetic|skincare|makeup|shampoo|conditioner|hair care/.test(x))return'beauty';if(/health|vitamin|pharmacy|medicine|personal care/.test(x))return'health';if(/sofa|chair|table|bed|home decor|furniture|homeware/.test(x))return'home';return'general';}
export function selectedRetailers(q,b={}){const fam=familyOf([b.object,b.name,b.model,b.category,b.retailCategory,b.query,q].join(' '));const explicitBrand=norm(b.brand);const brand=norm(b.brand||q);let arr=RETAILERS.filter(r=>(fam==='automotive'?r.cats.includes('automotive'):(r.cats.includes('all')||r.cats.includes(fam)))&&(!r.brand||!explicitBrand||explicitBrand.includes(r.brand)||r.brand.includes(explicitBrand)));for(const r of RETAILERS){if(r.brand&&brand.includes(r.brand)&&!arr.includes(r)&&r.cats.includes(fam))arr.unshift(r)}return [...new Map(arr.map(r=>[r.name,r])).values()].sort((a,z)=>(a.priority||9)-(z.priority||9));}
export function capabilitySummary(profile,connected=false){if(!profile)return null;return{retailer:profile.name,domain:profile.domain,exactProductSearch:true,onlinePrice:true,onlineAvailability:true,branchStock:connected?'connected_feed':profile.branchMode,branchPrice:connected?'connected_feed':profile.priceMode,branchVerificationNote:connected?'Connected retailer data can verify exact branch stock.':profile.branchNote,priceVerificationNote:connected?'Connected retailer data determines whether the price is branch-specific.':profile.priceNote,directionsAllowedOnlyWhenBranchVerified:true};}
export function retailerByName(name){return RETAILERS.find(r=>norm(r.name)===norm(name))||null}
export function retailerByUrl(url){return RETAILERS.find(r=>hostMatches(url,r.domain))||null}