import {selectedRetailers,hostMatches,familyOf} from './retailers.js';

const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/&amp;/g,' and ').replace(/\b(\d+)\s*(ml|mg|g|kg|l|gb|tb)\b/g,'$1$2').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const words=v=>[...new Set(norm(v).split(' ').filter(x=>x.length>2&&!['the','and','for','with','from','this','that','product','item'].includes(x)))];
const price=v=>{if(v==null)return null;let s=String(v).replace(/\s/g,'').replace(/[^0-9.,]/g,'');if(!s)return null;if(s.includes(',')&&s.includes('.'))s=s.replace(/,/g,'');else if(s.includes(',')&&!s.includes('.')){const p=s.split(',');s=p.at(-1).length===2?p.slice(0,-1).join('')+'.'+p.at(-1):p.join('')}const n=Number(s);return Number.isFinite(n)&&n>0&&n<10000000?n:null};
const stock=v=>{const x=norm(v);if(/out of stock|sold out|currently unavailable/.test(x))return'out_of_stock';if(/preorder|pre order/.test(x))return'preorder';if(/in stock|add to basket|add to cart|available online|available now|delivered in|delivery|click collect|store pick up|store pickup/.test(x))return'in_stock';return null};
function productUrl(url,domain){try{const u=new URL(url),p=u.pathname.toLowerCase();if(!hostMatches(url,domain))return false;if(/\/(search|catalogsearch|browse|category|categories|brands?|collections?|all)(\/|$)/.test(p))return false;if(/[?&](q|text|search|qsearch)=/i.test(u.search))return false;if(domain==='clicks.co.za')return /\/p\/\d+\/?$/.test(p);if(domain==='nike.com')return /\/t\//.test(p);return p.split('/').filter(Boolean).length>=2}catch{return false}}
async function reader(url,timeout=11000){try{const r=await fetch(`https://r.jina.ai/${url}`,{headers:{Accept:'text/plain','User-Agent':'FindItNearby/1.0'},signal:AbortSignal.timeout(timeout)});if(!r.ok)return null;return(await r.text()).slice(0,700000)}catch{return null}}
function directSearch(profile,q){const x=encodeURIComponent(q),d=profile.domain.replace(/^www\./,'');const m={'clicks.co.za':`https://clicks.co.za/search?text=${x}`,'dischem.co.za':`https://www.dischem.co.za/catalogsearch/result/?q=${x}`,'takealot.com':`https://www.takealot.com/all?qsearch=${x}`,'makro.co.za':`https://www.makro.co.za/search/?text=${x}`,'woolworths.co.za':`https://www.woolworths.co.za/cat?Ntt=${x}`,'nike.com':`https://www.nike.com/za/w?q=${x}&vst=${x}`,'adidas.co.za':`https://www.adidas.co.za/search?q=${x}`,'sportscene.co.za':`https://www.sportscene.co.za/search?q=${x}`,'totalsports.co.za':`https://www.totalsports.co.za/search?q=${x}`,'incredible.co.za':`https://www.incredible.co.za/search?q=${x}`,'game.co.za':`https://www.game.co.za/search?q=${x}`,'builders.co.za':`https://www.builders.co.za/search?text=${x}`};return m[d]||`https://www.google.com/search?q=${encodeURIComponent(`site:${profile.domain} ${q}`)}`}
function links(text,profile){const out=[],seen=new Set(),re=/https?:\/\/[^\s)\]>"']+/g;let m;while((m=re.exec(text||''))){let u=m[0].replace(/[.,;:]+$/,'');try{u=decodeURIComponent(u)}catch{}if(seen.has(u)||!productUrl(u,profile.domain))continue;seen.add(u);out.push(u);if(out.length>=12)break}return out}
function queryFor(body){const obj=clean(body.object),features=Array.isArray(body.features)?body.features.map(clean).filter(Boolean):[],source=[obj,...features].join(' '),w=words(source);return w.slice(0,6).join(' ')||clean(body.retailCategory||body.category||obj)}
function scoreCandidate(text,title,body){const object=norm(body.object),nTitle=norm(title),n=norm(text),f=words((Array.isArray(body.features)?body.features:[]).join(' '));if(object&&['conditioner','shampoo','serum','mascara','foundation','lipstick','router','microphone','headphones','monitor','keyboard','mouse','camera','drill'].some(x=>object.includes(x))&&!nTitle.includes(object))return 0;let s=.52;if(object&&nTitle.includes(object))s+=.13;if(f.length){const hits=f.filter(x=>n.includes(x)).length;s+=Math.min(.28,(hits/f.length)*.28)}const original=norm(body.name||body.query||body.searchQuery);if(original&&(nTitle===original||nTitle.includes(original)))return 0;return Math.min(.95,s)}
function parsePage(text,url,profile,body){if(!text)return null;const title=clean(text.match(/^Title:\s*(.+)$/mi)?.[1]||'');if(!title)return null;const similarity=scoreCandidate(text,title,body);if(similarity<.62)return null;const pm=text.match(/(?:R|ZAR)\s*([0-9][0-9\s,.]{1,12})/i)?.[1],pv=price(pm),av=stock(text);if(pv==null&&av==null)return null;const features=Array.isArray(body.features)?body.features.map(clean).filter(Boolean):[],nt=norm(text),matching=features.filter(f=>words(f).some(w=>nt.includes(w))).slice(0,5);return{product_name:title,retailer:{name:profile.name,country:'ZA'},product_url:url,price:pv,currency:'ZAR',availability:av,similarity:Math.round(similarity*100),matchingFeatures:matching,difference:'Alternative product — exact formula, ingredients or specifications may differ.',source:'Rendered retailer product page',branchStockVerified:false,stockScope:'online',checkedAt:new Date().toISOString()}}
function dedupe(rows){const seen=new Set(),out=[];for(const x of rows.sort((a,b)=>(b.similarity-a.similarity)||((a.price??1e12)-(b.price??1e12)))){const k=norm(x.product_url);if(!k||seen.has(k))continue;seen.add(k);out.push(x)}return out.slice(0,4)}

export async function searchSimilar(body={}){
  const original=clean(body.name||body.query||body.searchQuery||body.model||body.object);if(!original)return{ok:false,error:'Original product details required',alternatives:[]};
  const fam=familyOf([body.category,body.retailCategory,body.object,original].join(' ')),q=queryFor(body);
  let profiles=selectedRetailers(original,body).filter(p=>p.cats?.includes(fam)||p.cats?.includes('all'));
  profiles=profiles.sort((a,b)=>((a.cats?.includes('all')?10:0)+(a.priority||9))-((b.cats?.includes('all')?10:0)+(b.priority||9))).slice(0,6);
  const all=[];
  for(const profile of profiles){
    const sources=[directSearch(profile,q),`https://www.google.com/search?q=${encodeURIComponent(`site:${profile.domain} ${q}`)}`];
    const urls=[];
    for(const source of sources){const text=await reader(source,10000);for(const u of links(text,profile))if(!urls.includes(u))urls.push(u);if(urls.length>=5)break}
    for(const url of urls.slice(0,5)){const text=await reader(url,11000),item=parsePage(text,url,profile,body);if(item)all.push(item);if(all.length>=8)break}
    if(all.length>=8)break;
  }
  return{ok:true,original,alternatives:dedupe(all),checkedAt:new Date().toISOString()};
}
