from pathlib import Path
p=Path('api/product-intelligence-v2.js')
s=p.read_text()
old="async function verifySourceOffer(o,body){const url=o?.product_url;if(!url)return null;const p=profileFor(url,o?.retailer?.name,body);if(!p||!directProductUrl(url,p.domain))return null;try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'en-ZA,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(9000)});if(!r.ok)return null;const ct=r.headers.get('content-type')||'';if(!/html|xhtml|json/.test(ct))return null;const html=(await r.text()).slice(0,1400000),title=pageTitle(html),products=jsonLdProducts(html),ld=productOfferFromLd(products),ldName=products.map(x=>x?.name).filter(Boolean)[0]||'';const text=stripHtml(html).slice(0,300000);if(!sourcePageMatches(title,text,r.url||url,body,p,ldName))return null;const metaPrice=parsePrice(metaValue(html,'product:price:amount')||metaValue(html,'og:price:amount')||metaValue(html,'price')),metaCurrency=metaValue(html,'product:price:currency')||metaValue(html,'og:price:currency');const pagePrice=ld.price??metaPrice,pageStock=ld.availability??parseStock(metaValue(html,'availability')||text.slice(0,120000));return{...o,product_name:ldName||title||o.product_name,product_url:r.url||url,price:pagePrice,currency:ld.currency||metaCurrency||o.currency||'ZAR',availability:pageStock,verified:true,source:'Verified directly on retailer product page',sourcePageVerified:true,checkedAt:new Date().toISOString()}}catch{return null}}"
new="async function verifySourceOffer(o,body){const url=o?.product_url;if(!url)return null;const p=profileFor(url,o?.retailer?.name,body);if(!p||!directProductUrl(url,p.domain))return null;const finish=(title,text,finalUrl,priceValue,currencyValue,stockValue,source)=>{if(!sourcePageMatches(title,text,finalUrl||url,body,p,title))return null;return{...o,product_name:title||o.product_name,product_url:finalUrl||url,price:priceValue,currency:currencyValue||o.currency||'ZAR',availability:stockValue,verified:true,source,sourcePageVerified:true,checkedAt:new Date().toISOString()}};try{const r=await fetch(url,{headers:{'user-agent':'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/131 Safari/537.36','accept':'text/html,application/xhtml+xml','accept-language':'en-ZA,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(7500)});if(r.ok){const ct=r.headers.get('content-type')||'';if(/html|xhtml|json/.test(ct)){const html=(await r.text()).slice(0,1400000),title=pageTitle(html),products=jsonLdProducts(html),ld=productOfferFromLd(products),ldName=products.map(x=>x?.name).filter(Boolean)[0]||'',text=stripHtml(html).slice(0,300000);const metaPrice=parsePrice(metaValue(html,'product:price:amount')||metaValue(html,'og:price:amount')||metaValue(html,'price')),metaCurrency=metaValue(html,'product:price:currency')||metaValue(html,'og:price:currency');const v=finish(ldName||title,text,r.url||url,ld.price??metaPrice,ld.currency||metaCurrency||o.currency||'ZAR',ld.availability??parseStock(metaValue(html,'availability')||text.slice(0,120000)),'Verified directly on retailer product page');if(v)return v}}}catch{}try{const rr=await fetch(`https://r.jina.ai/${url}`,{headers:{Accept:'text/plain','User-Agent':'FindItNearby/2.0'},signal:AbortSignal.timeout(8500)});if(!rr.ok)return null;const text=(await rr.text()).slice(0,500000),title=String(text.match(/^Title:\\s*(.+)$/mi)?.[1]||o.product_name||'').trim(),pm=text.match(/(?:^|\\s)(?:R|ZAR)\\s*([0-9][0-9\\s,.]{1,12})(?=\\s|$)/i),pv=parsePrice(pm?.[1]),stock=parseStock(text.slice(0,180000));if(pv==null&&stock==null)return null;return finish(title,text,url,pv,o.currency||'ZAR',stock,'Verified on retailer product page via reader fallback')}catch{return null}}"
if old not in s:
    raise SystemExit('target verifySourceOffer block not found')
s=s.replace(old,new)
p.write_text(s)
print('patched api/product-intelligence-v2.js')
