from pathlib import Path

p=Path('dashboard-runtime-v8.js')
s=p.read_text()
old="""function route(a){if(a==='product')product();else if(a==='compare')compare();else if(a==='stock')stock();else if(a==='deals')compare('Verified Deals');else if(a==='pricehistory')compare('Price History');else if(a==='nearby')nearby();else if(a==='map'||a==='settings')settings();else if(a==='location')nearby();else if(a==='assistant')ask();else if(a==='alerts')simple('Price & Stock Alerts','Alerts only use verified price or stock updates. FindIt will not invent changes.');else if(a==='premium')premium();else if(a==='search')search();else if(a==='saved')simple('Saved Items','Your saved Finds are available here.');else if(a==='history')simple('History','Your recent FindIt searches are available here.');else if(a==='feedback')simple('Feedback','Send feedback from the FindIt feedback section.')}\n"""
new="""const identityActions=new Set(['product','compare','stock','deals','pricehistory','nearby','assistant']);\nlet pendingIdentityAction='';\nfunction hasCurrentIdentity(){const i=id();return !!(i?.name||i?.object||i?.searchQuery||i?.model)}\nfunction identifyThen(action){\n if(hasCurrentIdentity()||!st()?.file)return false;\n pendingIdentityAction=action;\n closeModal();\n const b=$('#search');\n if(b&&!b.disabled)b.click();\n let tries=0;\n const timer=setInterval(()=>{\n  if(hasCurrentIdentity()){\n   clearInterval(timer);\n   const next=pendingIdentityAction;pendingIdentityAction='';\n   if(next)route(next);\n   return;\n  }\n  if(++tries>=80){clearInterval(timer);pendingIdentityAction=''}\n },250);\n return true;\n}\nfunction route(a){if(identityActions.has(a)&&identifyThen(a))return;if(a==='product')product();else if(a==='compare')compare();else if(a==='stock')stock();else if(a==='deals')compare('Verified Deals');else if(a==='pricehistory')compare('Price History');else if(a==='nearby')nearby();else if(a==='map'||a==='settings')settings();else if(a==='location')nearby();else if(a==='assistant')ask();else if(a==='alerts')simple('Price & Stock Alerts','Alerts only use verified price or stock updates. FindIt will not invent changes.');else if(a==='premium')premium();else if(a==='search')search();else if(a==='saved')simple('Saved Items','Your saved Finds are available here.');else if(a==='history')simple('History','Your recent FindIt searches are available here.');else if(a==='feedback')simple('Feedback','Send feedback from the FindIt feedback section.')}\n"""
if old not in s:
    raise SystemExit('route block not found')
s=s.replace(old,new,1)
p.write_text(s)
