from pathlib import Path
import re

p=Path('dashboard-runtime-v8.js')
s=p.read_text()
new=r'''const PRODUCT_RESEARCH_CACHE='finditProductResearchCacheV1';
function researchIdentity(i={}){const clean=v=>String(v||'').replace(/\s+/g,' ').trim();const brand=clean(i.brand),model=clean(i.model),name=clean(i.name),object=clean(i.object),category=clean(i.retailCategory||i.category);const primary=clean(i.searchQuery||i.query||[brand,model||name||object].filter(Boolean).join(' '));const canonical=clean([brand,model||name||object,(!model&&object)||''].filter(Boolean).join(' '));const key=[brand,model,name,object,category,primary].map(x=>x.toLowerCase()).join('|');return{brand,model,name,object,category,primary,canonical,key}}
function researchCacheGet(key){try{const all=JSON.parse(localStorage.getItem(PRODUCT_RESEARCH_CACHE)||'{}'),hit=all[key];if(!hit||!hit.data?.researched||Date.now()-Number(hit.savedAt||0)>86400000)return null;return hit.data}catch{return null}}
function researchCachePut(key,data){if(!key||!data?.researched)return;try{const all=JSON.parse(localStorage.getItem(PRODUCT_RESEARCH_CACHE)||'{}');all[key]={savedAt:Date.now(),data};const entries=Object.entries(all).sort((a,b)=>Number(b[1]?.savedAt||0)-Number(a[1]?.savedAt||0)).slice(0,20);localStorage.setItem(PRODUCT_RESEARCH_CACHE,JSON.stringify(Object.fromEntries(entries)))}catch{}}
async function requestResearch(payload){const r=await fetch('/api/product-insights',{method:'POST',cache:'no-store',headers:{'content-type':'application/json','cache-control':'no-cache'},body:JSON.stringify(payload)});const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d?.error||`Research request failed (${r.status})`);return d}
async function reliableProductResearch(i){const x=researchIdentity(i),cached=researchCacheGet(x.key);if(cached)return cached;const queries=[x.primary,x.canonical,[x.brand,x.model||x.name||x.object,x.object,x.category].filter(Boolean).join(' ')].map(v=>String(v||'').replace(/\s+/g,' ').trim()).filter(Boolean);const unique=[...new Set(queries.map(q=>q.toLowerCase()))].map(q=>queries.find(x=>x.toLowerCase()===q)).slice(0,3);let last=null;for(let n=0;n<unique.length;n++){const q=unique[n];try{const d=await requestResearch({identification:{...i,brand:x.brand||i.brand||'',model:x.model||i.model||'',name:x.name||i.name||'',object:x.object||i.object||'',category:x.category||i.category||'',searchQuery:q},offers:verifiedOffers().slice(0,5),name:x.name||x.object,brand:x.brand,model:x.model,category:x.category,searchQuery:q,researchAttempt:n+1});last=d;if(d?.researched){researchCachePut(x.key,d);return d}}catch(e){last={researched:false,error:e?.message||'Research request failed'}}if(n<unique.length-1)await new Promise(r=>setTimeout(r,250*(n+1)))}return last||{researched:false}}
async function product(){const i=id();openModal(`<h2 class="fx-stable-title">Product Information</h2><p class="fx-stable-sub">Verified identity plus product information grounded in retailer evidence.</p><div class="fx-stable-list">${[['Brand',i.brand],['Model',i.model],['Category',i.retailCategory||i.category],['Search identity',i.searchQuery||i.name||i.object]].filter(([,v])=>v).map(([k,v])=>`<div class="fx-stable-row"><div><small>${esc(k)}</small><b>${esc(v)}</b></div></div>`).join('')||'<div class="fx-stable-row"><div>No product selected yet.</div></div>'}</div><div id="fxStableResearch" class="fx-stable-row" style="margin-top:12px"><div>Researching the exact product across verified web sources…</div></div>`);const box=$('#fxStableResearch');if(!i.name&&!i.object){box.innerHTML='<div>Search for a product first.</div>';return}try{const d=await reliableProductResearch(i);if(!box||!box.isConnected)return;if(!d?.researched){box.innerHTML='<div><b>Research not available yet</b><small>FindIt checked multiple exact-product searches but could not verify enough trustworthy information. It will not invent product facts.</small></div>';return}box.innerHTML=`<div><b>What it does</b><small>${esc(d.whatItDoes||'')}</small>${(d.pros||[]).length?`<h4>Pros</h4><ul>${d.pros.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}${(d.cons||[]).length?`<h4>Cons / considerations</h4><ul>${d.cons.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:''}</div>`}catch{if(box&&box.isConnected)box.innerHTML='<div><b>Research service is temporarily unavailable.</b><small>FindIt tried multiple times and did not invent missing facts.</small></div>'}}
'''
pat=re.compile(r'function product\(\)\{.*?\}\nfunction priceRow',re.S)
if not pat.search(s):
    raise SystemExit('product() block not found')
s=pat.sub(new+'function priceRow',s,count=1)
p.write_text(s)
