from pathlib import Path
p=Path('api/search.js')
s=p.read_text()
s=s.replace("const PRIMARY_MODEL='gemini-3.6-flash';\nconst FAST_MODEL='gemini-3.5-flash-lite';\nconst FALLBACK_MODEL='gemini-2.5-flash-lite';", "const PRIMARY_MODEL='gemini-3.1-flash-lite';\nconst FAST_MODEL='gemini-3.5-flash-lite';\nconst FALLBACK_MODEL='gemini-2.5-flash-lite';")
old="""  const primaryPromise=identifyDraft(key,base64,mime);\n  const checkerPromise=independentCheck(key,base64,mime);\n  const [primaryResult,checkerResult]=await Promise.allSettled([primaryPromise,checkerPromise]);\n  let draft=primaryResult.status==='fulfilled'?primaryResult.value:null;\n  let checker=checkerResult.status==='fulfilled'?checkerResult.value:null;\n  if(!draft&&checker){draft={...checker,modelUsed:checker.verifierModel||FAST_MODEL,verificationNote:'Primary identification timed out; independent vision result used safely.',draftChanged:false};checker=null}\n  if(!draft)throw (primaryResult.reason||checkerResult.reason||Error('Gemini request failed'));\n  let verified=mergeIndependent(draft,checker),verificationMode=checker?'parallel-two-pass':'single-pass-degraded';\n  if(checker&&needsTieBreak(draft,checker)){\n   const adjudicated=await tieBreak(key,base64,mime,draft,checker).catch(()=>null);\n   if(adjudicated){verified=adjudicated;verificationMode='parallel-plus-tiebreak'}\n  }\n"""
new="""  // Quota-safe path: one current stable multimodal pass first. A second pass is only used\n  // when the first result is genuinely uncertain, instead of spending 2-3 requests per photo.\n  let draft=await identifyDraft(key,base64,mime);\n  let checker=null,verificationMode='single-pass-quota-safe';\n  const draftConfidence=Number(draft?.confidence||0);\n  const needsChecker=draftConfidence<.72||(!draft?.object&&!draft?.name)||(draft?.modelEvidence===true&&draft?.brandEvidence!==true);\n  if(needsChecker){\n   checker=await independentCheck(key,base64,mime).catch(()=>null);\n   if(checker)verificationMode='selective-two-pass';\n  }\n  let verified=mergeIndependent(draft,checker);\n  if(checker&&needsTieBreak(draft,checker)){\n   const adjudicated=await tieBreak(key,base64,mime,draft,checker).catch(()=>null);\n   if(adjudicated){verified=adjudicated;verificationMode='selective-plus-tiebreak'}\n  }\n"""
if old not in s: raise SystemExit('parallel search block not found')
s=s.replace(old,new,1)
s=s.replace("let last;for(const model of [FAST_MODEL,FALLBACK_MODEL,PRIMARY_MODEL]){try{", "let last;for(const model of [PRIMARY_MODEL,FALLBACK_MODEL,FAST_MODEL]){try{",1)
p.write_text(s)
