import {retailerByName,capabilitySummary} from '../lib/retailers.js';

const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const toks=v=>[...new Set(norm(v).split(/\s+/).filter(x=>x.length>1))];
const number=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function overlap(a,b){const A=new Set(toks(a)),B=new Set(toks(b));if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.size,B.size)}
function haversine(a,b,c,d){const R=6371,p=Math.PI/180;const x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function stockState(v){const s=norm(v);if(/out of stock|sold out|unavailable|not available/.test(s))return'out_of_stock';if(/in stock|instock|available|low stock|limited stock/.test(s))return'in_stock';return null}
function branchState(s){if(!s)return null;if(s.in_stock===true||s.available===true||Number(s.stock_quantity)>0||Number(s.quantity)>0)return'in_stock';if(s.in_stock===false||s.available===false||Number(s.stock_quantity)===0||Number(s.quantity)===0){const raw=s.stock||s.availability||s.status||'';if(raw||s.stock_quantity===0||s.quantity===0)return'out_of_stock'}return stockState(s.stock||s.stock_status||s.availability||s.status)}
function productScore(i,p){const left=norm([i.name,i.object,i.searchQuery,i.query,i.brand,i.model].join(' ')),right=norm([p.name,p.title,p.brand,p.model,p.sku,p.category,(p.keywords||[]).join(' ')].join(' '));let s=.55*overlap(left,right);if(i.brand&&p.brand){if(norm(i.brand)===norm(p.brand))s+=.28;else s-=.22}if(i.model){const im=norm(i.model),pm=norm(p.model||p.sku);if(pm&&im===pm)s+=.42;else if(right.includes(im))s+=.32;else s-=.25}return clamp(s,0,1)}
function exactEnough(i,p,s){const text=norm([p.name,p.title,p.brand,p.model,p.sku,p.category,(p.keywords||[]).join(' ')].join(' '));const ib=norm(i.brand),im=norm(i.model);if(ib&&!text.includes(ib))return false;if(im&&!text.includes(im))return false;const q=toks(i.searchQuery||i.query||i.name||i.object);const hits=q.filter(t=>text.includes(t)).length;return s>=.68&&hits>=Math.min(3,Math.max(2,Math.ceil(q.length*.45)))}
function feedConfig(){try{const x=JSON.parse(process.env.RETAILER_FEEDS_JSON||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
async function fetchFeed(c){try{const headers={Accept:'application/json'};if(c.tokenEnv&&process.env[c.tokenEnv])headers.Authorization=`Bearer ${process.env[c.tokenEnv]}`;const r=await fetch(c.url,{headers,signal:AbortSignal.timeout(7000)});if(!r.ok)throw new Error(`${c.name} feed ${r.status}`);const d=await r.json();const products=Array.isArray(d)?d:Array.isArray(d.products)?d.products:[];return{config:c,products}}catch(e){return{config:c,products:[],error:e.message}}}
async function loadFeeds(){const cfg=feedConfig().filter(x=>x?.url&&x?.name);return Promise.all(cfg.map(fetchFeed))}
function likelyTags(i={}){const s=norm([i.category,i.retailCategory,i.object,i.name,i.searchQuery,i.brand,i.model].join(' '));if(/\b(car|cars|vehicle|vehicles|automotive|mustang|sedan|coupe|suv|bakkie|pickup|hatchback)\b/.test(s))return['car','car_parts','car_repair'];if(/grocery|household|toilet paper|food|supermarket|cleaning|beverage|snack/.test(s))return['supermarket','convenience','department_store'];if(/electronic|audio|microphone|computer|phone|camera|gaming/.test(s))return['electronics','computer','mobile_phone'];if(/shoe|footwear/.test(s))return['shoes','sports'];if(/clothing|fashion|shirt|dress|jacket/.test(s))return['clothes','department_store'];if(/hardware|tool|diy|paint|building/.test(s))return['hardware','doityourself'];if(/sport|fitness|gym|outdoor/.test(s))return['sports','outdoor'];return['department_store','variety_store']}
async function likelyNearby(a,b,radiusKm,identification){const r=Math.max(3,Math.min(25,radiusKm))*1000,tags=likelyTags(identification),ors=tags.map(t=>`nwr(around:${Math.round(r)},${a},${b})[shop=${JSON.stringify(t)}];`).join(''),q=`[out:json][timeout:10];(${ors});out center tags;`,endpoints=['https://overpass-api.de/api/interpreter','https://overpass.kumi.systems/api/interpreter','https://overpass.private.coffee/api/interpreter'];for(const endpoint of endpoints){try{const rr=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'FindIt-Nearby/3.1'},body:new URLSearchParams({data:q}),signal:AbortSignal.timeout(8000)});if(!rr.ok)continue;const d=await rr.json(),seen=new Set(),stores=[];for(const e of d.elements||[]){const t=e.tags||{},name=clean(t.name||t.brand||t.operator),lat=number(e.lat??e.center?.lat),lon=number(e.lon??e.center?.lon);if(!name||lat==null||lon==null)continue;const key=norm(name)+'|'+lat.toFixed(4)+'|'+lon.toFixed(4);if(seen.has(key))continue;seen.add(key);stores.push({id:`osm-${e.type}-${e.id}`,name,address:clean([t['addr:housenumber'],t['addr:street'],t['addr:suburb'],t['addr:city']].filter(Boolean).join(' ')),lat,lon,distanceKm:haversine(a,b,lat,lon),phone:clean(t.phone||t['contact:phone']),website:clean(t.website||t['contact:website']),exactProductMatch:false,stockVerified:false,directionsAvailable:false,source:'OpenStreetMap',type:/\b(car|cars|vehicle|automotive|mustang)\b/.test(norm([identification.object,identification.name,identification.searchQuery].join(' ')))?'Nearby automotive business — exact vehicle not verified':'Nearby category retailer only — exact item not verified'})}return{stores:stores.sort((x,y)=>x.distanceKm-y.distanceKm).slice(0,12),reliable:true}}catch{}}return{stores:[],reliable:false}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{const {lat,lon,identification={},radiusKm:requested,mode}=req.body||{},a=number(lat),b=number(lon);if(a==null||b==null)return res.status(400).json({error:'Valid location required'});const radiusKm=Math.min(25,Math.max(3,number(requested)||10));if(mode==='likely'){const d=await likelyNearby(a,b,radiusKm,identification);return res.status(200).json({ok:true,stores:d.stores,reliable:d.reliable,exactProductOnly:false,branchStockVerified:false,directionsAvailable:false,disclaimer:'These are nearby category retailers only. They are never treated as places to drive for the exact item.'})}
 const feeds=await loadFeeds(),rows=[],feedStatus=[];for(const f of feeds){const profile=retailerByName(f.config.name);feedStatus.push({retailer:f.config.name,connected:!f.error,error:f.error||null,capability:profile?capabilitySummary(profile,true):null});for(const p of f.products){const s=productScore(identification,p);if(!exactEnough(identification,p,s))continue;for(const st of Array.isArray(p.stores)?p.stores:[]){const state=branchState(st);if(state!=='in_stock')continue;const slat=number(st.lat??st.latitude),slon=number(st.lon??st.lng??st.longitude);if(slat==null||slon==null)continue;const distanceKm=haversine(a,b,slat,slon);if(distanceKm>radiusKm)continue;const branchPrice=number(st.price);rows.push({id:String(st.id||st.store_id||`${f.config.name}:${st.name||slat+','+slon}`),name:clean(st.name||st.store_name)||f.config.name,address:clean(st.address||st.formatted_address),lat:slat,lon:slon,distanceKm,phone:clean(st.phone),website:clean(st.website||p.url),retailer:f.config.name,productName:clean(p.name||p.title),productUrl:clean(p.url),exactProductMatch:true,matchTier:'exact',match:s,stockVerified:true,stockStatus:'In stock',stockQuantity:number(st.stock_quantity??st.quantity),branchStockVerified:true,price:branchPrice,branchPriceVerified:branchPrice!=null,currency:clean(st.currency||p.currency||'ZAR')||'ZAR',priceScope:branchPrice!=null?'branch':'not_verified_for_branch',directionsAvailable:true,checkedAt:clean(st.checked_at||st.checkedAt)||new Date().toISOString(),source:'Connected retailer feed'})}}}
 const seen=new Set(),stores=[];for(const x of rows.sort((m,n)=>n.match-m.match||m.distanceKm-n.distanceKm)){const k=norm(`${x.retailer}|${x.name}|${x.address}|${x.productName}`);if(seen.has(k))continue;seen.add(k);stores.push(x);if(stores.length>=20)break}
 if(stores.length)return res.status(200).json({ok:true,radiusKm,stores,reliable:true,exactProductOnly:true,exactVerifiedCount:stores.length,branchStockVerified:true,directionsAvailable:true,feedStatus,message:`Found ${stores.length} nearby branch${stores.length===1?'':'es'} where connected retailer data confirms the exact item is in stock.`,disclaimer:'Directions are shown only because exact product and branch stock are both verified. Branch price is shown only when the branch feed supplies a branch-specific price.'});
 return res.status(200).json({ok:true,radiusKm,stores:[],nearbyCandidates:[],reliable:true,exactProductOnly:true,exactVerifiedCount:0,branchStockVerified:false,directionsAvailable:false,feedStatus,message:'No nearby physical branch is verified for the exact item yet.',disclaimer:'FindIt will not suggest a trip to an unverified store. Exact online retailer listings can still be shown separately.'})
 }catch(e){console.error('nearby',e);return res.status(200).json({ok:true,reliable:false,stores:[],exactVerifiedCount:0,branchStockVerified:false,directionsAvailable:false,message:'Nearby branch verification is temporarily limited.',disclaimer:'FindIt will not invent branch stock, branch price, or directions.'})}}