import {RETAILERS,retailerByName,capabilitySummary,selectedRetailers} from '../lib/retailers.js';

const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const toks=v=>[...new Set(norm(v).split(/\s+/).filter(x=>x.length>1))];
const number=v=>{const n=Number(v);return Number.isFinite(n)?n:null};
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
function overlap(a,b){const A=new Set(toks(a)),B=new Set(toks(b));if(!A.size||!B.size)return 0;let hit=0;for(const x of A)if(B.has(x))hit++;return hit/Math.max(A.size,B.size)}
function haversine(a,b,c,d){const R=6371,p=Math.PI/180;const x=Math.sin((c-a)*p/2)**2+Math.cos(a*p)*Math.cos(c*p)*Math.sin((d-b)*p/2)**2;return R*2*Math.atan2(Math.sqrt(x),Math.sqrt(1-x))}
function stockState(v){const s=norm(v);if(/out of stock|sold out|unavailable|not available/.test(s))return'out_of_stock';if(/in stock|instock|available|low stock|limited stock/.test(s))return'in_stock';return null}
function branchState(s){if(!s)return null;if(s.in_stock===true||s.available===true||Number(s.stock_quantity)>0||Number(s.quantity)>0)return'in_stock';if(s.in_stock===false||s.available===false||Number(s.stock_quantity)===0||Number(s.quantity)===0)return'out_of_stock';return stockState(s.stock||s.stock_status||s.availability||s.status)}
function productScore(i,p){const left=norm([i.name,i.object,i.searchQuery,i.query,i.brand,i.model].join(' ')),right=norm([p.name,p.title,p.brand,p.model,p.sku,p.category,(p.keywords||[]).join(' ')].join(' '));let s=.55*overlap(left,right);if(i.brand&&p.brand){if(norm(i.brand)===norm(p.brand))s+=.28;else s-=.22}if(i.model){const im=norm(i.model),pm=norm(p.model||p.sku);if(pm&&im===pm)s+=.42;else if(right.includes(im))s+=.32;else s-=.25}return clamp(s,0,1)}
function exactEnough(i,p,s){const text=norm([p.name,p.title,p.brand,p.model,p.sku,p.category,(p.keywords||[]).join(' ')].join(' '));const ib=norm(i.brand),im=norm(i.model);if(ib&&!text.includes(ib))return false;if(im&&!text.includes(im))return false;const q=toks(i.searchQuery||i.query||i.name||i.object),hits=q.filter(t=>text.includes(t)).length;return s>=.68&&hits>=Math.min(3,Math.max(2,Math.ceil(q.length*.45)))}
function feedConfig(){try{const x=JSON.parse(process.env.RETAILER_FEEDS_JSON||'[]');return Array.isArray(x)?x:[]}catch{return[]}}
async function fetchFeed(c){try{const headers={Accept:'application/json'};if(c.tokenEnv&&process.env[c.tokenEnv])headers.Authorization=`Bearer ${process.env[c.tokenEnv]}`;const r=await fetch(c.url,{headers,signal:AbortSignal.timeout(5500)});if(!r.ok)throw new Error(`${c.name} feed ${r.status}`);const d=await r.json();return{config:c,products:Array.isArray(d)?d:Array.isArray(d.products)?d.products:[]}}catch(e){return{config:c,products:[],error:e.message}}}
async function loadFeeds(){return Promise.all(feedConfig().filter(x=>x?.url&&x?.name).map(fetchFeed))}
function likelyTags(i={}){const s=norm([i.category,i.retailCategory,i.object,i.name,i.searchQuery,i.brand,i.model].join(' '));if(/\b(car|cars|vehicle|vehicles|automotive|mustang|sedan|coupe|suv|bakkie|pickup|hatchback|mercedes|benz)\b/.test(s))return['car','car_parts','car_repair'];if(/grocery|household|toilet paper|food|supermarket|cleaning|beverage|snack|bread|milk|cereal/.test(s))return['supermarket','convenience','department_store'];if(/beauty|conditioner|shampoo|cosmetic|skincare|hair care|pharmacy/.test(s))return['chemist','beauty','department_store'];if(/plug adapter|multi plug|power strip|extension lead|electrical|socket adaptor/.test(s))return['electrical','hardware','doityourself'];if(/appliance|toaster|kettle|microwave|vacuum|air fryer|fridge|washing machine/.test(s))return['appliance','electronics','department_store'];if(/shoe|footwear|samba|sneaker|trainer|nike|adidas/.test(s))return['shoes','sports','clothes'];if(/clothing|fashion|shirt|dress|jacket/.test(s))return['clothes','department_store'];if(/electronic|audio|microphone|computer|phone|camera|gaming|speaker|bluetooth|headphone|headset|router|wifi|range extender/.test(s))return['electronics','computer','mobile_phone'];if(/hardware|tool|diy|paint|building|wrench|spanner|screwdriver|pliers|drill|hammer|saw/.test(s))return['hardware','doityourself'];if(/kitchenware|cookware|tableware|utensil|cutlery/.test(s))return['houseware','department_store','supermarket'];if(/sport|fitness|gym|outdoor/.test(s))return['sports','outdoor'];return['department_store','variety_store']}
function relevantNames(i={}){const q=[i.searchQuery,i.name,i.object,i.brand,i.model].filter(Boolean).join(' '),rows=selectedRetailers(q,i).filter(r=>r.branchMode!=='online_only').slice(0,8).map(r=>r.name);if(i.brand)rows.unshift(clean(i.brand));return [...new Set(rows.filter(Boolean))].slice(0,9)}
function rx(v){return String(v).replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}
function overpassQuery(a,b,radiusKm,tags,names){const r=Math.round(Math.max(3,Math.min(25,radiusKm))*1000),selectors=[...tags.map(t=>`nwr(around:${r},${a},${b})[shop="${t}"];`)];if(names.length){const nameRx=names.map(rx).join('|');selectors.push(`nwr(around:${r},${a},${b})[name~"${nameRx}",i];`);selectors.push(`nwr(around:${r},${a},${b})[brand~"${nameRx}",i];`)}return `[out:json][timeout:8];(${selectors.join('')});out center tags;`}
async function fetchOverpass(endpoint,q){try{const rr=await fetch(endpoint,{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded','user-agent':'FindIt-Nearby/5.2'},body:new URLSearchParams({data:q}),signal:AbortSignal.timeout(6500)});if(!rr.ok)throw new Error(String(rr.status));return await rr.json()}catch{return null}}
function parseOsm(d,a,b){const stores=[];for(const e of d?.elements||[]){const t=e.tags||{},name=clean(t.name||t.brand||t.operator),lat=number(e.lat??e.center?.lat),lon=number(e.lon??e.center?.lon);if(!name||lat==null||lon==null)continue;stores.push({id:`osm-${e.type}-${e.id}`,name,address:clean([t['addr:housenumber'],t['addr:street'],t['addr:suburb'],t['addr:city']].filter(Boolean).join(' ')),lat,lon,distanceKm:haversine(a,b,lat,lon),phone:clean(t.phone||t['contact:phone']),website:clean(t.website||t['contact:website']),exactProductMatch:false,stockVerified:false,branchStockVerified:false,directionsAvailable:true,source:'OpenStreetMap',type:'Nearby relevant retailer — exact item stock not verified'})}return stores}
function box(a,b,r){const lat=r/111.32,lon=r/(111.32*Math.max(.25,Math.cos(a*Math.PI/180)));return{left:b-lon,right:b+lon,top:a+lat,bottom:a-lat}}
async function nominatimName(name,a,b,radiusKm){try{const v=box(a,b,radiusKm),u=new URL('https://nominatim.openstreetmap.org/search');u.search=new URLSearchParams({q:name,format:'jsonv2',limit:'5',countrycodes:'za',bounded:'1',viewbox:`${v.left},${v.top},${v.right},${v.bottom}`});const rr=await fetch(u,{headers:{'user-agent':'FindIt-Nearby/5.2','accept-language':'en-ZA,en;q=0.9'},signal:AbortSignal.timeout(5000)});if(!rr.ok)return[];const d=await rr.json();return(d||[]).map((x,j)=>{const lat=number(x.lat),lon=number(x.lon);if(lat==null||lon==null)return null;return{id:`nom-${norm(name)}-${j}`,name:clean((x.display_name||'').split(',')[0])||name,address:clean(x.display_name),lat,lon,distanceKm:haversine(a,b,lat,lon),phone:'',website:'',exactProductMatch:false,stockVerified:false,branchStockVerified:false,directionsAvailable:true,source:'OpenStreetMap Nominatim',type:'Nearby named retailer — exact item stock not verified'}}).filter(Boolean)}catch{return[]}}
function sameBranch(a,b){if(!a||!b)return false;const d=haversine(a.lat,a.lon,b.lat,b.lon),an=norm(a.name),bn=norm(b.name);if(d<=.08)return true;if(d<=.35&&(an.includes(bn)||bn.includes(an)||overlap(an,bn)>=.6))return true;return false}
function mergeBranch(a,b){const first=a.source==='OpenStreetMap'?a:b,other=first===a?b:a;return{...other,...first,address:first.address||other.address,phone:first.phone||other.phone,website:first.website||other.website,distanceKm:Math.min(a.distanceKm,b.distanceKm)}}
function dedupeBranches(rows,limit=50){const stores=[];for(const s of rows.sort((x,y)=>x.distanceKm-y.distanceKm)){const idx=stores.findIndex(x=>sameBranch(x,s));if(idx>=0)stores[idx]=mergeBranch(stores[idx],s);else stores.push(s);if(stores.length>=limit)break}return stores}
function retailerChainKey(name){const n=norm(name);if(!n)return'';const matches=RETAILERS.map(r=>({key:norm(r.name),name:r.name})).filter(r=>n===r.key||n.startsWith(r.key+' ')).sort((a,b)=>b.key.length-a.key.length);return matches[0]?.key||n}
function nearestPerRetailer(rows,limit=12){const branches=dedupeBranches(rows,50).sort((a,b)=>a.distanceKm-b.distanceKm),seen=new Set(),out=[];for(const s of branches){const key=retailerChainKey(s.name);if(seen.has(key))continue;seen.add(key);out.push(s);if(out.length>=limit)break}return out}
async function likelyNearby(a,b,radiusKm,identification){const tags=likelyTags(identification),names=relevantNames(identification),q=overpassQuery(a,b,radiusKm,tags,names),endpoints=['https://overpass.kumi.systems/api/interpreter','https://overpass-api.de/api/interpreter','https://overpass.private.coffee/api/interpreter'];const [over,named]=await Promise.all([Promise.allSettled(endpoints.map(e=>fetchOverpass(e,q))),Promise.allSettled(names.slice(0,5).map(n=>nominatimName(n,a,b,radiusKm)))]);const rows=[];for(const x of over)if(x.status==='fulfilled'&&x.value)rows.push(...parseOsm(x.value,a,b));for(const x of named)if(x.status==='fulfilled')rows.push(...x.value);const inside=rows.filter(s=>s.distanceKm<=radiusKm);return{stores:nearestPerRetailer(inside),reliable:inside.length>0,names,tags}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});try{const {lat,lon,identification={},radiusKm:requested,mode}=req.body||{},a=number(lat),b=number(lon);if(a==null||b==null)return res.status(400).json({error:'Valid location required'});const radiusKm=Math.min(25,Math.max(3,number(requested)||10));if(mode==='likely'){const d=await likelyNearby(a,b,radiusKm,identification);return res.status(200).json({ok:true,stores:d.stores,reliable:d.reliable,exactProductOnly:false,branchStockVerified:false,directionsAvailable:d.stores.length>0,message:d.stores.length?`Found ${d.stores.length} relevant nearby retailer${d.stores.length===1?'':'s'} (nearest branch per retailer).`:'No relevant nearby retailers were found in this radius.',searchedRetailers:d.names,disclaimer:'These are real nearby retailers for the product type. FindIt shows only the nearest branch of each retailer until exact branch stock is verified.'})}
 const feeds=await loadFeeds(),rows=[],feedStatus=[];for(const f of feeds){const profile=retailerByName(f.config.name);feedStatus.push({retailer:f.config.name,connected:!f.error,error:f.error||null,capability:profile?capabilitySummary(profile,true):null});for(const p of f.products){const s=productScore(identification,p);if(!exactEnough(identification,p,s))continue;for(const st of Array.isArray(p.stores)?p.stores:[]){if(branchState(st)!=='in_stock')continue;const slat=number(st.lat??st.latitude),slon=number(st.lon??st.lng??st.longitude);if(slat==null||slon==null)continue;const distanceKm=haversine(a,b,slat,slon);if(distanceKm>radiusKm)continue;const branchPrice=number(st.price);rows.push({id:String(st.id||st.store_id||`${f.config.name}:${st.name||slat+','+slon}`),name:clean(st.name||st.store_name)||f.config.name,address:clean(st.address||st.formatted_address),lat:slat,lon:slon,distanceKm,phone:clean(st.phone),website:clean(st.website||p.url),retailer:f.config.name,productName:clean(p.name||p.title),productUrl:clean(p.url),exactProductMatch:true,matchTier:'exact',match:s,stockVerified:true,stockStatus:'In stock',stockQuantity:number(st.stock_quantity??st.quantity),branchStockVerified:true,price:branchPrice,branchPriceVerified:branchPrice!=null,currency:clean(st.currency||p.currency||'ZAR')||'ZAR',priceScope:branchPrice!=null?'branch':'not_verified_for_branch',directionsAvailable:true,checkedAt:clean(st.checked_at||st.checkedAt)||new Date().toISOString(),source:'Connected retailer feed'})}}}
 const stores=dedupeBranches(rows.sort((m,n)=>n.match-m.match||m.distanceKm-n.distanceKm),20);return res.status(200).json({ok:true,radiusKm,stores,reliable:true,exactProductOnly:true,exactVerifiedCount:stores.length,branchStockVerified:stores.length>0,directionsAvailable:stores.length>0,feedStatus,message:stores.length?`Found ${stores.length} nearby branch${stores.length===1?'':'es'} with verified exact-item stock.`:'No nearby physical branch is verified for the exact item yet.',disclaimer:stores.length?'Directions are shown because exact product and branch stock are both verified.':'FindIt will fall back to nearby relevant retailers separately instead of pretending they have the item.'})}catch(e){console.error('nearby',e);return res.status(200).json({ok:true,reliable:false,stores:[],exactVerifiedCount:0,branchStockVerified:false,directionsAvailable:false,message:'Nearby branch verification is temporarily limited.'})}}
