const BLOCKED=/\b(firearm|gun|rifle|pistol|ammunition|ammo|weapon|knife|knives|machete|sword|switchblade|taser|stun gun|pepper spray|mace|brass knuckles|fireworks|explosive|vape|nicotine|cigarette|cigar|alcohol|beer|wine|liquor|cannabis|marijuana|thc|cbd|psilocybin|magic mushroom|gambling|sports betting|casino|pornography|adult sex toy)\b/i;
const clean=(v,n=500)=>String(v??'').replace(/\s+/g,' ').trim().slice(0,n);
const norm=v=>clean(v,20000).toLowerCase().replace(/\b(\d+)\s*(ml|mg|g|kg|l|oz|gb|tb|pack|ply)\b/g,'$1$2').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const STOP=new Set(['the','and','for','with','from','this','that','product','item','online','shop','buy','price','store','retailer','south','africa','hair']);
const toks=v=>[...new Set(norm(v).split(' ').filter(x=>x.length>2&&!STOP.has(x)))];
function ident(body={}){const i=body.identification||body;return{brand:clean(i.brand,100),model:clean(i.model,220),name:clean(i.name||i.object,300),object:clean(i.object,140),query:clean(i.searchQuery||i.query||i.name||i.model||i.object,380)}}
function query(i){return clean(i.brand&&i.model?`${i.brand} ${i.model}`:i.query||`${i.brand} ${i.name}`,380)}
function exact(text,i){const n=norm(text),brand=toks(i.brand),generic=new Set(toks(i.object)),specific=toks(`${i.model} ${i.name} ${i.query}`).filter(x=>!brand.includes(x)&&!generic.has(x));if(brand.length&&!brand.every(x=>n.includes(x)))return false;const hits=specific.filter(x=>n.includes(x)).length;return specific.length>=5?hits>=3:specific.length>=2?hits>=2:specific.length?hits>=1:true}
function conflict(text,i){const c=String(text||'').toLowerCase(),w=`${i.model} ${i.name} ${i.query}`.toLowerCase();if(/\bconditioner\b/.test(w)&&/\bshampoo\b/.test(c)&&!/\bconditioner\b/.test(c))return true;if(/\bshampoo\b/.test(w)&&/\bconditioner\b/.test(c)&&!/\bshampoo\b/.test(c))return true;return[/(?:\+|\bplus\b)/i,/\bpro\b/i,/\bmax\b/i,/\bmini\b/i,/\bultra\b/i,/\bxl\b/i].some(re=>re.test(c)!==re.test(w))}
function amount(v){let s=String(v||'').replace(/[^0-9.,]/g,'');if(!s)return null;if(s.includes(',')&&s.includes('.'))s=s.lastIndexOf('.')>s.lastIndexOf(',')?s.replace(/,/g,''):s.replace(/\./g,'').replace(',','.');else if(s.includes(','))s=s.split(',').at(-1).length===2?s.replace(',','.'):s.replace(/,/g,'');const n=Number(s);return Number.isFinite(n)&&n>0&&n<1e8?n:null}
async function get(url){for(const target of [`https://r.jina.ai/${url}`,url]){try{const r=await fetch(target,{headers:{'user-agent':'Mozilla/5.0 FindItNearby/57.0','accept-language':'en-ZA,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(12000)});if(r.ok)return(await r.text()).slice(0,900000)}catch{}}return''}
function parse(raw,i,sourceUrl){const text=String(raw||'').replace(/\r/g,''),lines=text.split('\n').map(x=>x.trim()).filter(Boolean),out=[];for(let x=0;x<lines.length;x++){const line=lines[x];if(!exact(line,i)||conflict(line,i))continue;const block=lines.slice(Math.max(0,x-2),Math.min(lines.length,x+35));if(!exact(block.join(' '),i)||conflict(block.slice(0,8).join(' '),i))continue;for(let y=0;y<block.length;y++){const pm=block[y].match(/(?:^|\s)R\s*([0-9][0-9 .,'’]*(?:[.,][0-9]{2})?)/i);if(!pm)continue;const price=amount(pm[1].replace(/[ ’']/g,''));if(!price)continue;let retailer='';for(let z=Math.max(0,y-4);z<y;z++){const candidate=clean(block[z],100).replace(/^Image\s*!?$/i,'').trim();if(candidate&&!/^R\s*\d/i.test(candidate)&&!/recommended offers|loading|save|off$/i.test(candidate)&&candidate.length<70)retailer=candidate}
retailer=retailer.replace(/^Image\s*/i,'').trim();if(!retailer||exact(retailer,i))continue;out.push({retailer,price,currency:'ZAR',product_name:clean(line,260),source_url:sourceUrl,comparisonSource:'PriceCheck',exactProductMatch:true,comparisonVerified:true,checkedAt:new Date().toISOString()});}
if(out.length>=16)break}
const seen=new Set();return out.filter(o=>{const k=`${norm(o.retailer)}|${o.price}`;if(seen.has(k))return false;seen.add(k);return true})}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');const body=req.method==='POST'?(req.body||{}):(req.query||{}),i=ident(body),q=query(i);if(!q)return res.status(400).json({ok:false,error:'Missing product identity',offers:[]});if(BLOCKED.test(q))return res.status(403).json({ok:false,error:'This product category is not supported.',offers:[]});const url=`https://www.pricecheck.co.za/search?search=${encodeURIComponent(q)}`,raw=await get(url),offers=parse(raw,i,url);return res.status(200).json({ok:true,query:q,offers,source:'PriceCheck South Africa comparison data',checkedAt:new Date().toISOString()})}
