const RESTRICTED = ['firearm','gun','rifle','pistol','ammunition','ammo','weapon','switchblade','taser','pepper spray','vape','nicotine','cigarette','cigar','alcohol','beer','wine','liquor','cannabis','marijuana','thc','gambling','casino','betting','pornography','adult sex toy'];
const STOP = new Set(['the','and','for','with','from','this','that','pair','clear','black','white','small','large','new','men','women','unisex']);
const norm = v => String(v || '').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const toks = v => [...new Set(norm(v).split(/\s+/).filter(x => x.length > 1 && !STOP.has(x)))];
const clean = v => String(v || '').trim();
const clamp = (v,a,b) => Math.max(a,Math.min(b,v));
const RETAILERS = [
  {name:'Takealot',categories:['electronics','home','grocery','beauty','toys','stationery','sports','pet','automotive','clothing'],search:q=>`https://www.takealot.com/all?q=${encodeURIComponent(q)}`},
  {name:'Makro',categories:['electronics','home','grocery','beauty','toys','stationery','sports','pet','automotive','hardware'],search:q=>`https://www.makro.co.za/search?text=${encodeURIComponent(q)}`},
  {name:'Pick n Pay',categories:['grocery','home','electronics','stationery','toys','beauty','pet'],search:q=>`https://www.pnp.co.za/search?q=${encodeURIComponent(q)}`},
  {name:'Checkers',categories:['grocery','home','electronics','beauty','pet','stationery'],search:q=>`https://www.checkers.co.za/search?q=${encodeURIComponent(q)}`},
  {name:'Woolworths',categories:['grocery','clothing','beauty','home'],search:q=>`https://www.woolworths.co.za/cat?Ntt=${encodeURIComponent(q)}`},
  {name:'Clicks',categories:['beauty','personal care','health','baby','electronics'],search:q=>`https://clicks.co.za/search?q=${encodeURIComponent(q)}`},
  {name:'Dis-Chem',categories:['beauty','personal care','health','baby','electronics'],search:q=>`https://www.dischem.co.za/search?q=${encodeURIComponent(q)}`},
  {name:'Incredible Connection',categories:['electronics','computers','phones','audio'],search:q=>`https://www.incredible.co.za/catalogsearch/result/?q=${encodeURIComponent(q)}`},
  {name:'Game',categories:['electronics','home','grocery','toys','sports','hardware'],search:q=>`https://www.game.co.za/search?q=${encodeURIComponent(q)}`},
  {name:'Builders',categories:['hardware','home','garden','automotive'],search:q=>`https://www.builders.co.za/search?q=${encodeURIComponent(q)}`}
];
function family(v){const x=norm(v);if(/router|wifi|wi fi|modem|network|laptop|computer|phone|smartphone|headphone|earbud|speaker|microphone|camera|charger|electronics/.test(x))return'electronics';if(/toilet paper|tissue|food|drink|grocery|coffee|tea|snack|cleaning|detergent/.test(x))return'grocery';if(/shoe|sneaker|footwear|boot/.test(x))return'clothing';if(/makeup|cosmetic|skincare|shampoo|personal care/.test(x))return'beauty';if(/tool|drill|hardware|paint|plumbing/.test(x))return'hardware';if(/plant|garden|flower/.test(x))return'garden';if(/toy|lego|puzzle/.test(x))return'toys';if(/pencil|notebook|stationery|pen/.test(x))return'stationery';if(/pet|dog|cat/.test(x))return'pet';if(/car|automotive|tyre|battery/.test(x))return'automotive';return'general'}
function restricted(q){const x=norm(q);return RESTRICTED.some(t=>x.includes(t))}
function scoreProduct(p,q,brand,model){const text=norm([p.name,p.brand,p.model].join(' ')),qt=toks(q);let hit=0;for(const t of qt)if(text.includes(t))hit++;let s=qt.length?hit/qt.length*.58:0;if(brand&&text.includes(norm(brand)))s+=.24;if(model&&text.includes(norm(model)))s+=.34;return clamp(s,0,1)}
function parsePrice(v){if(v==null)return null;const n=Number(String(v).replace(/[^0-9.,]/g,'').replace(/,/g,''));return Number.isFinite(n)?n:null}
function availability(v){const x=norm(v);if(!x)return null;if(x.includes('instock')||x.includes('in stock'))return'in_stock';if(x.includes('outofstock')||x.includes('out of stock'))return'out_of_stock';if(x.includes('preorder')||x.includes('pre order'))return'preorder';return clean(v)}
function walkJsonLd(node,out=[]){if(!node)return out;if(Array.isArray(node)){for(const x of node)walkJsonLd(x,out);return out}if(typeof node!=='object')return out;const type=Array.isArray(node['@type'])?node['@type'].join(' '):node['@type'];if(/product/i.test(String(type||'')))out.push(node);if(node['@graph'])walkJsonLd(node['@graph'],out);return out}
function extractProducts(html,retailer,q,brand,model){const found=[],re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(html))&&found.length<30){try{const data=JSON.parse(m[1].trim());for(const p of walkJsonLd(data)){const offers=Array.isArray(p.offers)?p.offers[0]:p.offers||{},url=clean(p.url||offers.url||''),name=clean(p.name||'');if(!name)continue;const match=scoreProduct({name,brand:p.brand?.name||p.brand||'',model:p.model||p.sku||''},q,brand,model);if(match<.42)continue;found.push({retailer:retailer.name,productName:name,brand:clean(p.brand?.name||p.brand||''),model:clean(p.model||p.sku||''),price:parsePrice(offers.price||offers.lowPrice),currency:clean(offers.priceCurrency||'ZAR')||'ZAR',availability:availability(offers.availability),productUrl:url&&/^https?:/i.test(url)?url:null,image:Array.isArray(p.image)?p.image[0]:clean(p.image||''),match,source:'official retailer website',onlineListing:true,branchStockVerified:false})}}catch{}}return found.sort((a,b)=>b.match-a.match).slice(0,6)}
async function inspectRetailer(retailer,q,brand,model){const searchUrl=retailer.search(q);try{const r=await fetch(searchUrl,{headers:{'User-Agent':'FindItNearby/1.0 (+https://findit-nearby.vercel.app/)','Accept':'text/html,application/xhtml+xml'},redirect:'follow',signal:AbortSignal.timeout(5500)});if(!r.ok)return{name:retailer.name,searchUrl,status:'search_link_only',products:[]};const type=r.headers.get('content-type')||'';if(!type.includes('text/html'))return{name:retailer.name,searchUrl,status:'search_link_only',products:[]};const html=(await r.text()).slice(0,1800000),products=extractProducts(html,retailer,q,brand,model);return{name:retailer.name,searchUrl,status:products.length?'structured_products_found':'search_link_only',products}}catch{return{name:retailer.name,searchUrl,status:'search_link_only',products:[]}}}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{},q=clean(b.query||b.name||b.object),brand=clean(b.brand),model=clean(b.model);if(!q)return res.status(400).json({error:'Product query required'});if(restricted([q,brand,model,b.category].join(' ')))return res.status(403).json({error:'FindIt cannot search retailer websites for restricted or age-limited products.'});const fam=family([q,b.category,b.retailCategory].join(' ')),candidates=RETAILERS.filter(r=>fam==='general'||r.categories.includes(fam)).slice(0,6),settled=await Promise.all(candidates.map(r=>inspectRetailer(r,q,brand,model))),products=settled.flatMap(x=>x.products).sort((a,b)=>b.match-a.match).slice(0,20);return res.status(200).json({ok:true,query:q,family:fam,products,retailers:settled.map(({name,searchUrl,status})=>({name,searchUrl,status})),message:products.length?'Official retailer pages returned matching structured product data. Prices and stock labels are online listing data unless explicitly branch-verified.':'No structured product data was readable automatically, but official retailer search links are available.',disclaimer:'Online availability is not physical branch stock. FindIt only claims branch stock when a retailer supplies branch-level availability.'})}
