const BLOCKED=/\b(firearm|gun|rifle|pistol|ammunition|ammo|weapon|knife|knives|machete|sword|switchblade|taser|stun gun|pepper spray|mace|brass knuckles|fireworks|explosive|vape|nicotine|cigarette|cigar|alcohol|beer|wine|liquor|cannabis|marijuana|thc|cbd|psilocybin|magic mushroom|gambling|sports betting|casino|betting|pornography|adult sex toy)\b/i;
const clean=v=>String(v??'').trim();
const norm=v=>clean(v).toLowerCase().replace(/&amp;/g,' and ').replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
const STOP=new Set(['the','and','for','with','from','this','that','pair','new','white','black','small','large']);
const toks=v=>[...new Set(norm(v).split(' ').filter(x=>x.length>1&&!STOP.has(x)))];
const price=v=>{if(v==null)return null;let s=String(v).replace(/\s/g,'').replace(/[^0-9.,]/g,'');if(!s)return null;if(s.includes(',')&&s.includes('.'))s=s.replace(/,/g,'');else if(s.includes(','))s=s.replace(/,/g,'');const n=Number(s);return Number.isFinite(n)&&n>0&&n<10000000?n:null};
const availability=v=>{const x=norm(v);if(/out of stock|unavailable|sold out/.test(x))return'out_of_stock';if(/in stock|add to cart|get it today|get it tomorrow|delivery/.test(x))return'in_stock';if(/pre order|preorder/.test(x))return'preorder';return null};
function query(b){return [...new Set([b.brand,b.model,b.query||b.name||b.object].map(clean).filter(Boolean))].join(' ').replace(/\s+/g,' ').trim().slice(0,180)}
function score(text,q,b){const n=norm(text),qt=toks(q);if(!n||!qt.length)return 0;let hits=qt.filter(t=>n.includes(t)).length;let s=(hits/qt.length)*.62;const brand=norm(b.brand),model=norm(b.model);if(brand&&n.includes(brand))s+=.18;if(model&&n.includes(model))s+=.28;return Math.min(1,s)}
function exactEnough(text,q,b){const s=score(text,q,b),n=norm(text),brand=norm(b.brand),model=norm(b.model);if(brand&&!n.includes(brand))return false;if(model&&!n.includes(model))return false;return s>=.72}
function strip(s){return clean(String(s||'').replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/&nbsp;|&#160;/gi,' ').replace(/&quot;/gi,'"').replace(/&#39;|&apos;/gi,"'").replace(/&amp;/gi,'&').replace(/\s+/g,' '))}
function walk(n,out=[]){if(!n)return out;if(Array.isArray(n)){n.forEach(x=>walk(x,out));return out}if(typeof n!=='object')return out;const t=Array.isArray(n['@type'])?n['@type'].join(' '):n['@type'];if(/product/i.test(String(t||'')))out.push(n);for(const k of ['@graph','itemListElement','item'])if(n[k])walk(n[k],out);return out}
async function fetchHtml(url,timeout=7500){try{const r=await fetch(url,{headers:{'User-Agent':'Mozilla/5.0 (compatible; FindItNearby/5.0)','Accept':'text/html,application/xhtml+xml','Accept-Language':'en-ZA,en;q=0.9'},redirect:'follow',signal:AbortSignal.timeout(timeout)});if(!r.ok||!(r.headers.get('content-type')||'').includes('text/html'))return null;return{url:r.url||url,html:(await r.text()).slice(0,2000000)}}catch{return null}}
function productFromHtml(page,q,b){const out=[];const re=/<script[^>]+type=["']application\/ld\+json["'][^>]*>([\s\S]*?)<\/script>/gi;let m;while((m=re.exec(page.html))){try{const d=JSON.parse(m[1].trim().replace(/&quot;/g,'"'));for(const p of walk(d)){const name=clean(p.name||p.item?.name),off=Array.isArray(p.offers)?p.offers[0]:(p.offers||{});if(!name||!exactEnough([name,p.brand?.name||p.brand,p.model,p.sku,p.description].join(' '),q,b))continue;const u=clean(p.url||off.url||page.url);out.push({product_name:name,price:price(off.price||off.lowPrice),currency:clean(off.priceCurrency||'ZAR')||'ZAR',availability:availability(off.availability),product_url:u.startsWith('http')?u:page.url,verified:true,source:'Takealot product page',retailer:{name:'Takealot',country:'ZA',source:'takealot_live'},matchScore:score(name,q,b),branchStockVerified:false,listingType:'takealot_verified',onlineListing:true})}}catch{}}return out.sort((a,z)=>z.matchScore-a.matchScore)[0]||null}
function anchorCandidates(page,q,b){const out=[],re=/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi;let m;while((m=re.exec(page.html))&&out.length<300){const label=strip(m[2]);if(!label||label.length>260||!exactEnough(label,q,b))continue;try{const u=new URL(m[1],page.url);if(!/(^|\.)takealot\.com$/i.test(u.hostname))continue;if(!/\/PLID\d+/i.test(u.pathname))continue;out.push({url:u.href,label,score:score(label,q,b)})}catch{}}return out.sort((a,z)=>z.score-a.score).slice(0,6)}
async function groundedTakealot(q,b){const key=process.env.GEMINI_API_KEY;if(!key)return[];const prompt=`Find direct current Takealot product pages for the exact product: ${q}. Return only takealot.com product URLs that strongly match the exact brand/model/pack/variant. Do not return category/search pages. Never claim physical branch stock.`;for(const model of ['gemini-3.6-flash','gemini-3.5-flash-lite']){try{const r=await fetch(`https://generativelanguage.googleapis.com/v1beta/models/${model}:generateContent`,{method:'POST',headers:{'Content-Type':'application/json','x-goog-api-key':key},body:JSON.stringify({contents:[{parts:[{text:prompt}]}],tools:[{google_search:{}}],generationConfig:{temperature:.01}}),signal:AbortSignal.timeout(10000)});const d=await r.json().catch(()=>({}));if(!r.ok)continue;const chunks=d?.candidates?.[0]?.groundingMetadata?.groundingChunks||[];return chunks.map(x=>x?.web?.uri).filter(u=>{try{const x=new URL(u);return /(^|\.)takealot\.com$/i.test(x.hostname)&&/\/PLID\d+/i.test(x.pathname)}catch{return false}}).slice(0,6)}catch{}}return[]}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');if(req.method!=='POST')return res.status(405).json({error:'Method not allowed'});const b=req.body||{},q=query(b);if(!q)return res.status(400).json({error:'Product details required'});if(BLOCKED.test([q,b.category,b.retailCategory].join(' ')))return res.status(403).json({error:'Unsupported product type'});const searchUrl=`https://www.takealot.com/all?qsearch=${encodeURIComponent(q)}`;const checked=[];let offer=null;const search=await fetchHtml(searchUrl);if(search){for(const c of anchorCandidates(search,q,b)){checked.push(c.url);const p=await fetchHtml(c.url,5000);if(!p)continue;offer=productFromHtml(p,q,b);if(offer)break;const text=strip(p.html).slice(0,180000);if(exactEnough(text,q,b)){const pm=text.match(/(?:R|ZAR)\s*([0-9][0-9\s,.]{1,12})/i);offer={product_name:c.label||q,price:price(pm?.[1]),currency:'ZAR',availability:availability(text),product_url:p.url,verified:true,source:'Takealot exact product page',retailer:{name:'Takealot',country:'ZA',source:'takealot_live'},matchScore:c.score,branchStockVerified:false,listingType:'takealot_verified',onlineListing:true};break}}}
if(!offer){for(const u of await groundedTakealot(q,b)){if(checked.includes(u))continue;checked.push(u);const p=await fetchHtml(u,5000);if(!p)continue;offer=productFromHtml(p,q,b);if(offer)break;const text=strip(p.html).slice(0,180000);if(exactEnough(text,q,b)){const title=(text.match(/^(.{5,180}?)(?:\s+R\s*[0-9]|\s+Takealot)/i)||[])[1]||q,pm=text.match(/(?:R|ZAR)\s*([0-9][0-9\s,.]{1,12})/i);offer={product_name:title,price:price(pm?.[1]),currency:'ZAR',availability:availability(text),product_url:p.url,verified:true,source:'Takealot exact product page',retailer:{name:'Takealot',country:'ZA',source:'takealot_live'},matchScore:score(text.slice(0,5000),q,b),branchStockVerified:false,listingType:'takealot_verified',onlineListing:true};break}}}
return res.json({ok:true,matched:Boolean(offer),offer,offers:offer?[offer]:[],verifiedOfferCount:offer?1:0,verifiedSellerCount:offer?1:0,branchStockVerified:false,directionsAvailable:false,searchUrl,normalizedQuery:q,checkedPages:checked.length,message:offer?'Verified exact Takealot product listing found. Takealot availability is online/fulfilment availability, not physical branch stock.':'No exact Takealot product page could be verified. A direct exact-item Takealot search is provided instead.'})}
